[build]
  base = "client"
  command = "npm run build"
  publish = "build"

[environment]
  REACT_APP_API_URL = "https://hippie-sciences.onrender.com"

[[redirects]]
  from = "https://www.thehippiescientist.net/*"
  to = "https://thehippiescientist.net/:splat"
  status = 301
  force = true
