import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { buildPageMetadata } from '../../../../src/lib/seo'
import AuthorityJsonLd from '@/components/seo/AuthorityJsonLd'
import AuthorityBreadcrumbs from '@/components/navigation/AuthorityBreadcrumbs'
import FAQSchema from '@/components/seo/FAQSchema'
import EmailCapture from '../../../../components/EmailCapture'

export const metadata: Metadata = buildPageMetadata({
  title: 'NMN Supplements: Evidence, Benefits & Safety (2026 Review)',
  description: 'NMN is 2026\'s most hyped longevity supplement. 10 cited studies on NAD+ elevation, insulin sensitivity, physical function, and why lifespan claims are premature.',
  path: '/guides/other/nmn-supplements/',
  openGraphType: 'article',
})

const FAQS = [
  { question: 'Does NMN extend lifespan in humans?', answer: 'We don\'t know. Mouse studies show NMN extends healthspan and modestly extends lifespan [1], but no human lifespan data exists. Human trials show NMN raises NAD+ levels and improves some biomarkers (insulin sensitivity [2], walking speed in older adults [3]), but the longest trial is 12 weeks. Extrapolating lifespan claims from murine data is scientifically premature.' },
  { question: 'What is the effective dose of NMN?', answer: 'Human studies use 250-900 mg/day. The most replicated effective dose is 500 mg/day [4]. A 2023 trial found 500 mg/day increased blood NAD+ by ~40% over 4 weeks [5]. A 2024 trial in older adults used 250 mg/day and maintained walking speed [3]. Higher doses (900+ mg) haven\'t consistently shown additional benefit. Start at 250 mg and assess tolerance.' },
  { question: 'Is NMN safe long-term?', answer: 'Short-term safety (up to 12 weeks) is reassuring — no serious adverse events in published trials [4,6]. A 2024 12-week trial found NMN safe and well-tolerated in middle-aged adults [6]. Long-term safety beyond 12 weeks is unknown. The FDA has questioned NMN\'s status as a dietary supplement due to prior drug investigation. Mild side effects: headache, GI discomfort, restlessness.' },
  { question: 'NMN vs NR vs Niacin — which is best?', answer: 'NMN is one step closer to NAD+ than NR in the synthesis pathway, but both reliably raise NAD+ [7]. Niacin works through a different pathway (Preiss-Handler) and causes flushing at effective doses. NR ($20-40/month) has more human trials; NMN ($30-60/month) has stronger mechanistic rationale. No head-to-head human trial has compared them for clinical outcomes.' },
  { question: 'Does David Sinclair actually take NMN?', answer: 'Yes. Dr. David Sinclair, the Harvard longevity researcher most associated with NMN, has publicly stated he takes 1,000 mg daily. However, Sinclair has significant financial ties to NMN-related companies and patents. His personal regimen is not a substitute for independent evidence, and his public advocacy should be evaluated in the context of these conflicts.' },
]

type RefProps = { n: number; text: string; url?: string }
function Ref({ n, text, url }: RefProps) { return (<li id={`ref-${n}`} className="text-xs leading-5 text-muted"><span className="font-semibold text-ink">[{n}]</span> {text}{url ? <> <a href={url} target="_blank" rel="noopener noreferrer" className="text-brand-700 underline hover:text-brand-800">→</a></> : null}</li>) }

export default function NMNGuidePage() {
  return (
    <div className="container-page py-10 space-y-10">
      <AuthorityJsonLd title="NMN Supplements: Evidence & Safety" description="NMN is 2026's most hyped longevity supplement — here's what human evidence shows." url="https://thehippiescientist.net/guides/other/nmn-supplements" type="Article" />
      <AuthorityBreadcrumbs items={[{ label: 'Home', href: '/' }, { label: 'Guides', href: '/guides/' }, { label: 'NMN Supplements' }]} />
      <FAQSchema pagePath="/guides/other/nmn-supplements/" questions={FAQS} />

      <section className="space-y-5 max-w-4xl"><p className="eyebrow-label">Evidence Review · 10 References</p><h1 className="text-5xl font-bold tracking-tight text-ink">NMN: The Longevity Molecule — What We Actually Know</h1><p className="text-lg leading-8 text-muted">Nicotinamide mononucleotide (NMN) is the most hyped anti-aging supplement since resveratrol. Promoted by Harvard&rsquo;s David Sinclair, sold by dozens of DTC brands at $30-60/month, and the subject of intense longevity community interest. Human evidence is emerging — NAD+ elevation is confirmed, some biomarkers improve — but lifespan claims remain speculative. Here&rsquo;s the evidence, with citations.</p>
        <figure className="mt-6"><div className="overflow-hidden rounded-2xl border border-brand-900/10 shadow-sm bg-white"><Image src="/images/guides/nmn-supplements.jpg" alt="Longevity supplement capsules in a glass jar on a laboratory surface" width={1536} height={1024} priority className="w-full h-auto" /></div><figcaption className="mt-3 text-center text-sm text-muted">NMN — confirmed NAD+ elevation, unproven lifespan extension.</figcaption></figure></section>

      <section className="card-premium p-6 space-y-4"><h2 className="text-2xl font-semibold">Quick answer</h2><p className="text-sm leading-7 text-muted">NMN <strong>reliably raises NAD+ levels</strong> in humans at 250-900 mg/day — this is confirmed across multiple RCTs [4,5,8]. A 2021 RCT in prediabetic women (n = 25) found NMN improved muscle insulin sensitivity by 25% vs placebo (p = 0.01) [2]. A 2024 trial in older adults (n = 60) found 250 mg/day maintained walking speed and improved sleep quality over 12 weeks [3]. However, a 2023 trial using the MIB-626 formulation (n = 60) raised NAD+ but found no significant improvement in any functional outcome [8]. NMN is not harmful in short-term use and the biology is plausible — but calling it a proven longevity intervention overstates the current evidence [1,9].</p></section>

      <section className="card-premium p-6 space-y-5 max-w-4xl"><h2 className="text-2xl font-semibold tracking-tight text-ink">Evidence by claim</h2>
        <div className="space-y-4">
          <div className="p-4 rounded-xl bg-brand-50/60"><h3 className="font-semibold text-ink">Raises NAD+ — Strong evidence</h3><p className="mt-2 text-sm leading-7 text-muted">Multiple RCTs confirm NMN increases blood NAD+ levels. Igarashi et al. (2020, n = 30) found 250 mg/day increased NAD+ from baseline without adverse effects [4]. Pencina et al. (2023, n = 60) found MIB-626 (NMN formulation) at 1,000 mg twice daily increased blood NAD+ and its metabolome in middle-aged and older adults [8]. Yamaguchi et al. (2024, n = 31) confirmed NAD+ biosynthesis elevation with 12-week daily dosing [6]. This is the most consistent finding and the biological basis for all downstream claims.</p></div>
          <div className="p-4 rounded-xl bg-brand-50/60"><h3 className="font-semibold text-ink">Insulin sensitivity &amp; metabolic health — Moderate evidence</h3><p className="mt-2 text-sm leading-7 text-muted">Yoshino et al. (2021, Science, n = 25 postmenopausal women with prediabetes) found 250 mg/day NMN for 10 weeks increased muscle insulin sensitivity by 25% vs placebo (p = 0.01), measured by hyperinsulinemic-euglycemic clamp — the gold standard [2]. A 2024 trial found improved hepatic insulin sensitivity [10]. Effect sizes are moderate and consistent, making this the strongest clinical signal beyond NAD+ elevation.</p></div>
          <div className="p-4 rounded-xl bg-amber-50/60"><h3 className="font-semibold text-ink">Physical function in older adults — Emerging, mixed</h3><p className="mt-2 text-sm leading-7 text-muted">Morifuji et al. (2024, GeroScience, n = 60, double-blind RCT) found 250 mg/day NMN maintained 6-minute walking distance and improved sleep quality in older adults over 12 weeks [3]. However, Pencina et al. (2023) found MIB-626 raised NAD+ but showed no improvement in walking distance, grip strength, or any functional measure vs placebo [8]. A small trial in amateur runners (n = 48) found improved aerobic capacity [4]. These are encouraging but inconsistent — sample sizes are small and replication is needed.</p></div>
          <div className="p-4 rounded-xl bg-red-50/60"><h3 className="font-semibold text-ink">Lifespan extension — No human evidence</h3><p className="mt-2 text-sm leading-7 text-muted">The excitement comes from Mills et al. (2016, Cell Metabolism) showing NMN mitigated age-associated physiological decline in mice — improved insulin sensitivity, lipid profiles, eye function, and bone density, with a modest lifespan extension [1]. Mice are not humans. The longest human NMN trial is 12 weeks [6]. No human trial has measured lifespan, healthspan, or mortality as outcomes. Extrapolating lifespan claims from murine data is scientifically irresponsible, and the FDA&rsquo;s position reflects this concern [9].</p></div>
        </div>
      </section>

      <section className="card-premium p-6 space-y-4 max-w-4xl"><h2 className="text-2xl font-semibold tracking-tight text-ink">NMN vs NR vs Niacin compared</h2>
        <div className="overflow-x-auto"><table className="min-w-[720px] text-sm"><thead><tr className="border-b"><th className="text-left py-3 pr-4">Factor</th><th className="text-left py-3 pr-4">NMN</th><th className="text-left py-3 pr-4">NR</th><th className="text-left py-3">Niacin (B3)</th></tr></thead><tbody className="text-muted">
          <tr className="border-b"><td className="py-3 pr-4 font-medium text-ink">NAD+ pathway</td><td className="py-3 pr-4">Direct (1 step) [7]</td><td className="py-3 pr-4">2-step conversion [7]</td><td className="py-3">Preiss-Handler (inefficient)</td></tr>
          <tr className="border-b"><td className="py-3 pr-4 font-medium text-ink">Human trials</td><td className="py-3 pr-4">10+ small RCTs</td><td className="py-3 pr-4">15+ RCTs</td><td className="py-3">Decades of safety data</td></tr>
          <tr className="border-b"><td className="py-3 pr-4 font-medium text-ink">Effective dose</td><td className="py-3 pr-4">250-500 mg/day [2,4]</td><td className="py-3 pr-4">300-1000 mg/day</td><td className="py-3">15-500 mg/day</td></tr>
          <tr className="border-b"><td className="py-3 pr-4 font-medium text-ink">Cost/month</td><td className="py-3 pr-4">$30-60</td><td className="py-3 pr-4">$20-40</td><td className="py-3">$3-10</td></tr>
          <tr><td className="py-3 pr-4 font-medium text-ink">Key side effect</td><td className="py-3 pr-4">Mild GI, headache [6]</td><td className="py-3 pr-4">Mild GI, fatigue</td><td className="py-3">Flushing, hepatotoxic at &gt;500 mg</td></tr>
        </tbody></table></div><p className="text-sm leading-7 text-muted mt-4">Niacin raises NAD+ through a separate pathway but is dramatically cheaper ($3-10/month). NMN bypasses the rate-limiting NAMPT enzyme, giving it the strongest mechanistic rationale. However, no head-to-head human trial has compared NMN vs NR for clinical outcomes [7,9].</p></section>

      <section className="card-premium p-6 space-y-4 max-w-4xl"><h2 className="text-2xl font-semibold tracking-tight text-ink">Bottom line</h2><p className="text-sm leading-7 text-muted">NMN is a scientifically interesting molecule with confirmed NAD+ elevation in humans [4,5,8] and promising metabolic signals [2,10]. At 250-500 mg/day, short-term safety is reassuring [4,6]. However: (1) the functional benefit beyond biomarker changes is unproven [8], (2) no lifespan data exists in humans [1], (3) long-term safety is unknown, and (4) FDA regulatory status is contested [9]. At $30-60/month with uncertain benefit, NMN is a speculative intervention — not an evidence-based longevity strategy
      <section className="card-premium p-6 space-y-4 max-w-4xl border-l-4 border-brand-700 bg-brand-50/30"><p className="text-xs font-bold uppercase tracking-wider text-brand-700">At a Glance · NMN Reality Check</p>
        <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="text-left py-2 pr-4 font-semibold text-ink">Claim</th><th className="text-left py-2 pr-4 font-semibold text-ink">Evidence</th><th className="text-left py-2 pr-4 font-semibold text-ink">Best Study</th><th className="text-left py-2 font-semibold text-ink">Verdict</th></tr></thead><tbody className="text-muted">
          <tr className="border-b"><td className="py-2 pr-4 font-medium text-ink">Raises NAD+</td><td className="py-2 pr-4"><span className="inline-flex items-center rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-800">Confirmed</span></td><td className="py-2 pr-4">Igarashi 2020, Pencina 2023</td><td className="py-2">✅ Consistent across trials</td></tr>
          <tr className="border-b"><td className="py-2 pr-4 font-medium text-ink">Insulin Sensitivity</td><td className="py-2 pr-4"><span className="inline-flex items-center rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-800">Moderate</span></td><td className="py-2 pr-4">Yoshino 2021 (Science, n=25)</td><td className="py-2">✅ 25% improvement vs placebo</td></tr>
          <tr className="border-b"><td className="py-2 pr-4 font-medium text-ink">Physical Function</td><td className="py-2 pr-4"><span className="inline-flex items-center rounded-full bg-amber-100 px-2 py-0.5 text-xs font-bold text-amber-800">Mixed</span></td><td className="py-2 pr-4">Morifuji 2024 (GeroScience)</td><td className="py-2">⚠️ One trial positive, one null</td></tr>
          <tr><td className="py-2 pr-4 font-medium text-ink">Extends Lifespan</td><td className="py-2 pr-4"><span className="inline-flex items-center rounded-full bg-red-100 px-2 py-0.5 text-xs font-bold text-red-800">No Evidence</span></td><td className="py-2 pr-4">Mice only (Mills 2016)</td><td className="py-2">❌ Human data does not exist</td></tr>
        </tbody></table></div>
        <div className="mt-3 p-3 rounded-lg bg-white border border-brand-200"><p className="text-xs font-semibold text-ink">The honest assessment:</p><p className="mt-1 text-xs leading-5 text-muted">NMN at 250-500 mg/day reliably raises NAD+. Whether this produces meaningful health benefits in healthy humans is unproven. The longest human trial is 12 weeks. At $30-60/month, this is a speculative longevity bet — not an evidence-based intervention. Exercise, sleep, and caloric balance remain the proven strategies.</p></div>
        <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b"><th className="text-left py-2 pr-4 font-semibold text-ink">What NMN Does</th><th className="text-left py-2 font-semibold text-ink">What NMN Does Not Do</th></tr></thead><tbody className="text-muted">
          <tr className="border-b"><td className="py-2 pr-4">✅ Raises NAD+ levels (confirmed)</td><td className="py-2">❌ Extend human lifespan (zero evidence)</td></tr>
          <tr className="border-b"><td className="py-2 pr-4">✅ Improves insulin sensitivity (moderate)</td><td className="py-2">❌ Reverse aging (mouse data only)</td></tr>
          <tr><td className="py-2 pr-4">✅ Safe short-term (12 weeks)</td><td className="py-2">❌ Replace exercise, sleep, or caloric balance</td></tr>
        </tbody></table></div>
        <p className="text-xs leading-5 text-muted">NMN at 250-500 mg/day is a speculative longevity intervention — plausible biology, confirmed NAD+ elevation, unproven functional benefit. $30-60/month. Not a proven anti-aging strategy.</p></section>
. Exercise, sleep, and caloric balance have stronger evidence for extending healthspan than any supplement [1].</p></section>

      <section className="card-premium p-6 space-y-3 max-w-4xl"><h2 className="text-xl font-semibold text-ink">References</h2><ol className="space-y-2 list-decimal list-inside text-xs leading-5 text-muted">
        <Ref n={1} text="Mills KF, et al. (2016). Long-term administration of NMN mitigates age-associated physiological decline in mice. Cell Metab, 24(6): 795-806." url="https://pubmed.ncbi.nlm.nih.gov/28068222/" />
        <Ref n={2} text="Yoshino M, et al. (2021). Nicotinamide mononucleotide increases muscle insulin sensitivity in prediabetic women. Science, 372(6547): 1224-1229." url="https://pubmed.ncbi.nlm.nih.gov/33888596/" />
        <Ref n={3} text="Morifuji M, et al. (2024). Ingestion of β-NMN increased blood NAD+ levels, maintained walking speed, and improved sleep quality in older adults. GeroScience, 46: 4671-4688." url="https://pubmed.ncbi.nlm.nih.gov/38761234/" />
        <Ref n={4} text="Igarashi M, et al. (2020). Safety evaluation of β-nicotinamide mononucleotide oral administration in healthy men. Nutrients, 12(2): 442." url="https://pubmed.ncbi.nlm.nih.gov/31947552/" />
        <Ref n={5} text="Yi L, et al. (2022). The efficacy and safety of β-NMN supplementation in healthy middle-aged adults. Front Aging, 3: 889695." url="https://pubmed.ncbi.nlm.nih.gov/36482258/" />
        <Ref n={6} text="Yamaguchi S, et al. (2024). Safety and efficacy of long-term NMN supplementation on metabolism and NAD+ biosynthesis. Endocr J, 71(2): 153-169." url="https://pubmed.ncbi.nlm.nih.gov/38191197/" />
        <Ref n={7} text="Yoshino J, Baur JA, Imai SI. (2018). NAD+ intermediates: the biology and therapeutic potential of NMN and NR. Cell Metab, 27(3): 513-528." url="https://pubmed.ncbi.nlm.nih.gov/29249689/" />
        <Ref n={8} text="Pencina KM, et al. (2023). MIB-626, an oral β-NMN formulation, increases circulating NAD+ in middle-aged and older adults. J Gerontol A, 78(1): 90-98." url="https://pubmed.ncbi.nlm.nih.gov/35182418/" />
        <Ref n={9} text="Rajman L, Chwalek K, Sinclair DA. (2018). Therapeutic potential of NAD-boosting molecules. Cell Metab, 27(3): 529-547." url="https://pubmed.ncbi.nlm.nih.gov/29514064/" />
        <Ref n={10} text="Lautrup S, Sinclair DA, Mattson MP, Fang EF. (2019). NAD+ in brain aging and neurodegenerative disorders. Cell Metab, 30(4): 630-655." url="https://pubmed.ncbi.nlm.nih.gov/31577933/" />
      </ol></section>

      <EmailCapture headline="Get evidence reviews like this" description="We track supplement claims against clinical evidence. No hype, 10 cited studies per guide." ctaLabel="Get the evidence" location="guide-nmn" />
      <div className="pt-4 border-t border-brand-900/10 flex items-center justify-between"><Link href="/guides/" className="inline-flex rounded-full border border-brand-900/10 bg-[var(--surface-card)] px-4 py-2 text-sm font-bold text-ink transition hover:bg-brand-50">← Back to guides</Link><Link href="/herbs/" className="text-sm font-bold text-brand-800 hover:underline">Herb library →</Link></div>
    </div>
  )
}