export const CORE_INDEXABLE_ROUTES = [
  '/',
  '/about',
  '/articles',
  '/compounds',
  '/contact',
  '/dosing',
  '/evidence-digest',
  '/faq',
  '/goals',
  '/guides',
  '/herbs',
  '/learn',
  '/methodology',
  '/privacy',
  '/disclaimer',
  '/safety-checker',
  '/supplement-safety-checklist',
  '/stacks',
  '/tools',
] as const

export const MONEY_ENTRY_ROUTES = [
  '/best-supplements-for-sleep',
  '/best-supplements-for-stress',
  '/best-supplements-for-focus',
  '/best-supplements-for-fat-loss',
  '/best-supplements-for-blood-pressure',
  '/best-supplements-for-gut-health',
  '/best-supplements-for-joint-support',
  '/best-herbs-for-anxiety',
  '/best-nootropics-for-focus',
  '/best-adaptogens-for-stress',
] as const

export const CURATED_INDEXABLE_HERB_SLUGS = [
  'ashwagandha',
  'rhodiola',
  'kava',
  'turmeric',
  'ginger',
  'peppermint',
  'black-cohosh',
  'berberine',
  'momordica-charantia',
  'black-seed',
  'bacopa',
  'ginkgo',
  'saffron',
  'lemon-balm',
  'valerian',
] as const

export const CURATED_INDEXABLE_COMPOUND_SLUGS = [
  'l-theanine',
  'magnesium',
  'omega-3',
  'caffeine',
  'egcg',
  'nac',
  'coenzyme-q10',
  'curcumin',
  'berberine',
  'alpha-gpc',
  'citicoline-cdp-choline',
  'phosphatidylserine',
  'acetyl-l-carnitine',
  'l-tyrosine',
  'huperzine-a',
] as const
