// Auto-generated master herb+compound list
// Extracted 141 entries
// Generated on 2025-07-23T13:59:31.010336

export default [
  {
    name: "Pimenta dioica",
    slug: "pimenta-dioica",
    description: "Also known as Allspice, this Caribbean plant has mild uplifting and warming effects, sometimes used in ritual incense.",
    region: "Caribbean, Central America",
    effects: ["stimulant", "aromatic euphoria", "warming"],
    compounds: ["Eugenol", "Quercetin"],
    mechanismOfAction: "GABAergic + serotonergic",
    tags: ["aromatic", "ritual", "mild stimulant"]
  },
  {
    name: "Lactuca virosa",
    slug: "lactuca-virosa",
    description: "Wild Lettuce, a traditional sedative and pain reliever in folk medicine, sometimes called 'lettuce opium'.",
    region: "Europe",
    effects: ["sedative", "analgesic", "dreamy"],
    compounds: ["Lactucopicrin", "Lactucin"],
    mechanismOfAction: "Opioid receptor modulation",
    tags: ["sedative", "folk medicine", "dream aid"]
  },
  {
    name: "Achillea millefolium",
    slug: "achillea-millefolium",
    description: "Yarrow, used for divination and as a calming tea. Some varieties contain mild psychoactive compounds.",
    region: "Europe, North America",
    effects: ["mild euphoria", "relaxation", "ritual clarity"],
    compounds: ["Thujone (trace)", "Flavonoids"],
    mechanismOfAction: "GABAergic + serotonergic",
    tags: ["folk remedy", "ritual", "divination"]
  },
  {
    name: "Peumus boldus",
    slug: "peumus-boldus",
    description: "Boldo is a South American medicinal herb with liver-supportive and mild hypnotic properties.",
    region: "Chile",
    effects: ["calming", "digestive aid", "dreamy"],
    compounds: ["Boldine", "Ascaridole"],
    mechanismOfAction: "Cholinergic + serotonergic",
    tags: ["digestive", "sleep aid", "folk medicine"]
  },
  {
    name: "Vitex agnus-castus",
    slug: "vitex-agnus-castus",
    description: "Chasteberry is traditionally used for hormonal balancing, mood stabilization, and dream clarity.",
    region: "Mediterranean",
    effects: ["mood stabilization", "lucidity", "balance"],
    compounds: ["Agnuside", "Flavonoids"],
    mechanismOfAction: "Dopaminergic + hormonal",
    tags: ["hormonal", "mood", "dream"]
  },
  {
    name: "Myristica fragrans",
    slug: "myristica-fragrans",
    description: "Nutmeg, psychoactive in high doses, has deliriant and sedative properties. Historically used in mystic rituals.",
    region: "Indonesia",
    effects: ["dreaminess", "euphoria", "disorientation"],
    compounds: ["Myristicin", "Elemicin"],
    mechanismOfAction: "Monoamine oxidase inhibition + anticholinergic",
    tags: ["deliriant", "visionary", "ritual"]
  },
  {
    name: "Amorpha fruticosa",
    slug: "amorpha-fruticosa",
    description: "False Indigo Bush, native to North America, was historically smoked for relaxation and vision-induction.",
    region: "North America",
    effects: ["relaxation", "mental softening", "trance"],
    compounds: ["Amorphigenin"],
    mechanismOfAction: "Likely GABAergic",
    tags: ["folk", "smokable", "visionary"]
  },
  {
    name: "Eleutherococcus senticosus",
    slug: "eleutherococcus-senticosus",
    description: "Siberian Ginseng is an adaptogen used to enhance endurance, mental resilience, and reduce fatigue.",
    region: "Siberia, China",
    effects: ["clarity", "resilience", "mental energy"],
    compounds: ["Eleutherosides"],
    mechanismOfAction: "Adaptogenic + neuroprotective",
    tags: ["adaptogen", "tonic", "nootropic"]
  },
  {
    name: "Verbena officinalis",
    slug: "verbena-officinalis",
    description: "Vervain is a calming and spiritually symbolic herb used in ritual baths and teas.",
    region: "Europe, North Africa",
    effects: ["mild sedation", "relaxation", "spiritual clarity"],
    compounds: ["Verbenalin", "Iridoids"],
    mechanismOfAction: "GABAergic + serotonergic",
    tags: ["ritual", "relaxant", "dream"]
  },
  {
    name: "Melissa officinalis",
    slug: "melissa-officinalis",
    description: "Lemon Balm is a gentle nervine herb that promotes calmness and sleep with subtle mood elevation.",
    region: "Europe, Middle East",
    effects: ["calming", "mood lifting", "sleep aid"],
    compounds: ["Citral", "Rosmarinic acid"],
    mechanismOfAction: "GABA-T inhibition + serotonergic",
    tags: ["calming", "folk remedy", "tea"]
  },
  {
    Acacia maidenii: "Acacia maidenii is known for its Entheogenic, Dream-like, Expansive effects.",
    Acorus calamus: "Acorus calamus is known for its Sedative, Dream-enhancing, Stimulant (low dose) effects.",
    Acorus gramineus: "Acorus gramineus is known for its Mildly calming, Cognitive-enhancing, Dream potentiator effects.",
    Adhatoda vasica: "Adhatoda vasica is known for its Bronchodilator, Mild stimulant, Expectorant effects.",
    Aegle marmelos: "Aegle marmelos is known for its Digestive tonic, Anti-inflammatory, Cooling effects.",
    African Dream Root: "African Dream Root is known for its Vivid dreams, Lucid dreaming, Mild sedative effects.",
    Albizia julibrissin: "Albizia julibrissin is known for its Mood-lifting, Anti-anxiety, Sedative effects.",
    Alchornea castaneifolia: "Alchornea castaneifolia is known for its Anti-inflammatory, Analgesic, Ayahuasca synergist effects.",
    Alpinia galanga: "Alpinia galanga is known for its Stimulant, Cognitive-enhancing, Aphrodisiac effects.",
    Amanita muscaria: "Amanita muscaria is known for its Sedation, Euphoria, Confusion effects.",
    Anadenanthera colubrina: "Anadenanthera colubrina is known for its Visual hallucinations, Disorientation, Euphoria effects.",
    Anadenanthera peregrina: "Anadenanthera peregrina is known for its Intense visuals, Out-of-body experience, Altered time perception effects.",
    Argyreia nervosa: "Argyreia nervosa is known for its Euphoria, Time distortion, Closed-eye visuals effects.",
    Argyreia speciosa: "Argyreia speciosa is known for its Aphrodisiac, Mild sedative, Nootropic (traditional) effects.",
    Artemisia absinthium: "Artemisia absinthium is known for its Euphoria, Mild hallucinations, Stimulation effects.",
    Arundo donax: "Arundo donax is known for its Unverified hallucinations, Mild sedation, Traditionally visionary (claimed) effects.",
    Asarum canadense: "Asarum canadense is known for its Warming, Digestive stimulant, Mild sedation effects.",
    Asclepias syriaca: "Asclepias syriaca is known for its Mild sedation, Cardiac influence, Anti-inflammatory effects.",
    Avena sativa: "Avena sativa is known for its Mild euphoria, Anxiolytic, Nourishing tonic effects.",
    Banisteriopsis caapi: "Banisteriopsis caapi is known for its MAOI potentiation, Euphoria, Emotional release effects.",
    Brunfelsia grandiflora: "Brunfelsia grandiflora is known for its Altered perception, Hallucinations, Sedation effects.",
    Brugmansia suaveolens: "Brugmansia suaveolens is known for its True hallucinations, Amnesia, Delirium effects.",
    Caesalpinia sepiaria: "Caesalpinia sepiaria is known for its Stimulation, Increased stamina, Traditional energizing effects.",
    Calliandra angustifolia: "Calliandra angustifolia is known for its Heart-opening, Dreamlike calm, Energetic cleansing effects.",
    Camellia sinensis: "Camellia sinensis is known for its Alertness, Calm focus, Mood elevation effects.",
    Camellia japonica: "Camellia japonica is known for its Skin soothing, Antioxidant, Mild anti-inflammatory effects.",
    Cananga odorata: "Cananga odorata is known for its Euphoria, Relaxation, Aphrodisiac effects.",
    Cannabis sativa: "Cannabis sativa is known for its Euphoria, Relaxation, Altered perception effects.",
    Capsicum annuum: "Capsicum annuum is known for its Stimulation, Endorphin release, Heat sensation effects.",
    Celastrus paniculatus: "Celastrus paniculatus is known for its Memory enhancement, Mental clarity, Mild stimulation effects.",
    Calea ternifolia: "Calea ternifolia is known for its Lucid dreaming, Vivid dreams, Mild sedation effects.",
    Campsiandra angustifolia: "Campsiandra angustifolia is known for its Anti-inflammatory, Aphrodisiac, Tonic effects.",
    Carica papaya: "Carica papaya is known for its Digestive support, Antiparasitic, Anti-inflammatory effects.",
    Catha edulis: "Catha edulis is known for its Euphoria, Increased alertness, Sociability effects.",
    Catuaba: "Catuaba is known for its Stimulation, Enhanced libido, Mild euphoria effects.",
    Centella asiatica: "Centella asiatica is known for its Memory enhancement, Wound healing, Stress reduction effects.",
    Cestrum nocturnum: "Cestrum nocturnum is known for its Sedation, Headache (aroma), Potential hallucinations (in folklore) effects.",
    Cichorium intybus: "Cichorium intybus is known for its Liver support, Mild stimulant (roasted), Prebiotic effects.",
    Cissampelos pareira: "Cissampelos pareira is known for its Uterine tonic, Muscle relaxant, Antimalarial effects.",
    Claviceps purpurea: "Claviceps purpurea is known for its Vasoconstriction, Hallucinations, Convulsions effects.",
    Clitoria ternatea: "Clitoria ternatea is known for its Cognitive enhancement, Anxiolytic, Neuroprotective effects.",
    Cola acuminata: "Cola acuminata is known for its Stimulation, Increased alertness, Mood elevation effects.",
    Combretum quadrangulare: "Combretum quadrangulare is known for its Mild stimulation, Mental clarity, Sociability effects.",
    Shankhpushpi: "Shankhpushpi is known for its Memory enhancement, Stress reduction, Mental clarity effects.",
    Corydalis yanhusuo: "Corydalis yanhusuo is known for its Pain relief, Sedation, Muscle relaxation effects.",
    Crataegus monogyna: "Crataegus monogyna is known for its Heart tonic, Circulation support, Anxiolytic effects.",
    Crocus sativus: "Crocus sativus is known for its Euphoria, Antidepressant, Cognitive support effects.",
    Turmeric: "Turmeric is known for its Anti-inflammatory, Antioxidant, Liver tonic effects.",
    Cytisus scoparius: "Cytisus scoparius is known for its Cardiac stimulation, Diuretic, Mood elevation effects.",
    Datura inoxia: "Datura inoxia is known for its Intense delirium, Anticholinergic trance, Hallucinations effects.",
    Desmodium gangeticum: "Desmodium gangeticum is known for its Nervine support, Anti-inflammatory, Rejuvenation effects.",
    Derris elliptica: "Derris elliptica is known for its Paralysis (insects/fish), Mild euphoria (folklore), Toxicity effects.",
    Dioscorea villosa: "Dioscorea villosa is known for its Hormone balance, Menstrual relief, Anti-inflammatory effects.",
    Duboisia hopwoodii: "Duboisia hopwoodii is known for its Stimulation, Alertness, Appetite suppression effects.",
    Echinopsis pachanoi: "Echinopsis pachanoi is known for its Euphoria, Hallucinations, Empathy effects.",
    Siberian Ginseng: "Siberian Ginseng is known for its Fatigue resistance, Immune modulation, Mental stamina effects.",
    Ephedra sinica: "Ephedra sinica is known for its Stimulation, Appetite suppression, Bronchodilation effects.",
    California Poppy: "California Poppy is known for its Mild sedation, Anxiety relief, Sleep enhancement effects.",
    Erythrina mulungu: "Erythrina mulungu is known for its Anxiety relief, Sedation, Muscle relaxation effects.",
    Espeletia grandiflora: "Espeletia grandiflora is known for its Cough relief, Lung support, Anti-inflammatory effects.",
    Tongkat Ali: "Tongkat Ali is known for its Testosterone boost, Energy, Stress resilience effects.",
    Galphimia glauca: "Galphimia glauca is known for its Anxiety relief, Tranquility, Sleep aid effects.",
    Gastrodia elata: "Gastrodia elata is known for its Calms the liver, Relieves tremors, Supports cognition effects.",
    Gelsemium sempervirens: "Gelsemium sempervirens is known for its Muscle relaxation, Nervous system inhibition, Pain relief effects.",
    Genipa americana: "Genipa americana is known for its Skin staining, Mild antibacterial, Cooling sensation effects.",
    Ginkgo biloba: "Ginkgo biloba is known for its Cognitive enhancement, Circulation support, Antioxidant effects.",
    Gliricidia sepium: "Gliricidia sepium is known for its Topical antiparasitic, Wound healing, Insect repellent effects.",
    Gymnema sylvestre: "Gymnema sylvestre is known for its Suppresses sweet taste, Regulates blood sugar, Supports pancreas effects.",
    Heimia salicifolia: "Heimia salicifolia is known for its Dream enhancement, Auditory distortion, Relaxation effects.",
    Lion’s Mane: "Lion’s Mane is known for its Nerve growth, Memory enhancement, Mood support effects.",
    Roselle: "Roselle is known for its Blood pressure reduction, Cooling, Diuretic effects.",
    Hyoscyamus niger: "Hyoscyamus niger is known for its Hallucinations, Disorientation, Sedation effects.",
    Guayusa: "Guayusa is known for its Smooth stimulation, Vivid dreams, Antioxidant effects.",
    Yerba Mate: "Yerba Mate is known for its Mental alertness, Appetite control, Social energy effects.",
    Garden Balsam: "Garden Balsam is known for its Wound healing, Antimicrobial, Anti-itch effects.",
    Morning Glory (Heavenly Blue): "Morning Glory (Heavenly Blue) is known for its Visual distortions, Dream-like state, Nausea effects.",
    Justicia pectoralis: "Justicia pectoralis is known for its Mild euphoria, Calm, Slight analgesia effects.",
    Kanna: "Kanna is known for its Euphoria, Reduced anxiety, Social enhancement effects.",
    Wild Lettuce: "Wild Lettuce is known for its Pain relief, Sedation, Muscle relaxation effects.",
    Peppermint: "Peppermint is known for its Soothes digestion, Stimulates focus, Relieves cramps effects.",
    Wild Dagga: "Wild Dagga is known for its Mild euphoria, Relaxation, Tranquility effects.",
    Motherwort: "Motherwort is known for its Heart regulation, Menstrual balance, Anxiety relief effects.",
    Lobelia inflata: "Lobelia inflata is known for its Bronchodilation, Muscle relaxation, Emetic (high dose) effects.",
    Peyote: "Peyote is known for its Visuals, Emotional opening, Ego dissolution effects.",
    Club Moss: "Club Moss is known for its Cognitive stimulation (mild), Digestive tonic, Symbolic use effects.",
    Maca: "Maca is known for its Hormone balancing, Energy boost, Libido enhancement effects.",
    Mandrake: "Mandrake is known for its Hallucinations, Sedation, Amnesia effects.",
    White Horehound: "White Horehound is known for its Expectorant, Digestion support, Cough relief effects.",
    Chamomile: "Chamomile is known for its Calming, Sleep aid, Soothes digestion effects.",
    Lemon Balm: "Lemon Balm is known for its Anti-anxiety, Cognitive clarity, Mood boost effects.",
    Mimosa pudica: "Mimosa pudica is known for its Intestinal cleanse, Antiparasitic, Calming effects.",
    Mitragyna hirsuta: "Mitragyna hirsuta is known for its Mild euphoria, Calm stimulation, Analgesia effects.",
    Kratom: "Kratom is known for its Energy, Euphoria, Pain relief effects.",
    Mucuna pruriens: "Mucuna pruriens is known for its Mood boost, Motivation, Hormonal support effects.",
    Nutmeg: "Nutmeg is known for its Sedation, Euphoria, Hallucinations (high dose) effects.",
    Blue Lotus: "Blue Lotus is known for its Euphoria, Relaxation, Lucid dreams effects.",
    Sacred Lotus: "Sacred Lotus is known for its Relaxation, Tranquility, Aphrodisiac effects.",
    White Lotus: "White Lotus is known for its Euphoria, Lucid dreaming, Tranquility effects.",
    American Yellow Lotus: "American Yellow Lotus is known for its Tranquility, Heart-opening, Sensual awareness effects.",
    Red/Blue Water Lily: "Red/Blue Water Lily is known for its Calm euphoria, Sensual clarity, Dream enhancement effects.",
    Catnip: "Catnip is known for its Relaxation, Mild euphoria, Digestive aid effects.",
    Holy Basil: "Holy Basil is known for its Stress reduction, Mental clarity, Immune modulation effects.",
    Guaraná: "Guaraná is known for its Energy, Focus, Mood boost effects.",
    Passionflower: "Passionflower is known for its Calm, Anxiety reduction, Sleep support effects.",
    Syrian Rue: "Syrian Rue is known for its MAOI activity, Psychedelic potentiation, Meditative calm effects.",
    Kava: "Kava is known for its Relaxation, Euphoria, Anxiety relief effects.",
    Mexican Pepperleaf: "Mexican Pepperleaf is known for its Digestive aid, Calming, Flavor enhancer effects.",
    Voacanga africana: "Voacanga africana is known for its Altered perception, CNS stimulation, Dream enhancement effects.",
    Sinicuichi: "Sinicuichi is known for its Euphoria, Auditory hallucinations, Memory enhancement effects.",
    Damiana: "Damiana is known for its Mood elevation, Mild euphoria, Aphrodisiac effects.",
    Indian Tobacco: "Indian Tobacco is known for its Bronchodilation, Spasm relief, Nausea (high doses) effects.",
    Mimosa hostilis: "Mimosa hostilis is known for its Vivid dreams, Entheogenic visions (with MAOI), Wound healing effects.",
    Hawaiian Baby Woodrose: "Hawaiian Baby Woodrose is known for its Psychedelic visions, Sedation, Time distortion effects.",
    Calamus: "Calamus is known for its Mental clarity, Energy, Dream enhancement effects.",
    Yopo: "Yopo is known for its Euphoria, Visionary state, Dissociation effects.",
    Marshmallow Root: "Marshmallow Root is known for its Mucosal soothing, Cough relief, Gut lining protection effects.",
    Uva Ursi: "Uva Ursi is known for its Urinary tract support, Astringent, Anti-inflammatory effects.",
    Wormwood: "Wormwood is known for its Digestive stimulation, Lucid dreams, Mental clarity effects.",
    Wild Ginger: "Wild Ginger is known for its Warming, Carminative, Stimulating effects.",
    Mugwort: "Mugwort is known for its Lucid dreaming, Digestive stimulation, Mild euphoria effects.",
    Guarana: "Guarana is known for its Stimulation, Increased alertness, Mood boost effects.",
    Chacruna: "Chacruna is known for its Psychedelic visions, Emotional processing, Spiritual insight effects.",
    Iboga: "Iboga is known for its Intense visions, Addiction interruption, Ego dissolution effects.",
    Valerian: "Valerian is known for its Deep relaxation, Sleep induction, Stress relief effects.",
    Ashwagandha: "Ashwagandha is known for its Stress resilience, Energy balance, Hormonal support effects.",
    Yohimbe: "Yohimbe is known for its Sexual stimulation, Increased arousal, Central nervous stimulation effects.",
    Toothache Tree: "Toothache Tree is known for its Mouth numbing, Tingling, Pain relief effects.",
    Root Beer Plant: "Root Beer Plant is known for its Calming, Digestive aid, Appetite stimulation effects.",
    Rhodiola rosea: "Rhodiola rosea is known for its Fatigue reduction, Stress resilience, Mental clarity effects.",
    Xhosa Dream Root: "Xhosa Dream Root is known for its Lucid dreaming, Vivid dreams, Subtle euphoria effects.",
    Pinkroot: "Pinkroot is known for its Parasitic cleanse, Mild sedation, Vision changes (in excess) effects.",
    Linden: "Linden is known for its Calming, Antispasmodic, Cardiovascular support effects.",
    Mexican Tarragon: "Mexican Tarragon is known for its Mild euphoria, Vision enhancement, Lucid dreaming effects.",
    Coltsfoot: "Coltsfoot is known for its Cough suppression, Lung soothing, Mild sedation effects.",
    Yellow Alder: "Yellow Alder is known for its Relaxation, Mood uplift, Digestive ease effects.",
    Vervain: "Vervain is known for its Stress relief, Menstrual support, Digestive calming effects.",
    Sweet Violet: "Sweet Violet is known for its Cough relief, Mild sedation, Uplifting mood effects.",
    Corn Silk: "Corn Silk is known for its Urinary support, Anti-inflammatory, Kidney soothing effects.",
    Ginger: "Ginger is known for its Digestive stimulant, Nausea relief, Anti-inflammatory effects.",
    Indian Valerian: "Indian Valerian is known for its Sleep aid, Anxiety reduction, Mental calm effects.",
    Stinging Nettle: "Stinging Nettle is known for its Joint support, Urinary flow, Histamine modulation effects.",
    Chaste Tree: "Chaste Tree is known for its Hormone regulation, Menstrual cycle balancing, Mood support effects.",
    Cat’s Claw: "Cat’s Claw is known for its Immune support, Anti-inflammatory, Digestive aid effects.",
    Tylophora indica: "Tylophora indica is known for its Asthma relief, Anti-allergy, Immunoregulation effects.",
    Prickly Ash: "Prickly Ash is known for its Tingling, Local analgesia, Salivation effects.",
    Grains of Selim: "Grains of Selim is known for its Warming, Decongestant, Digestive aid effects.",
    Yarrow: "Yarrow is known for its Wound healing, Fever reduction, Digestive support effects.",
    Heartsease: "Heartsease is known for its Calming, Anti-inflammatory, Expectorant effects.",
    Lesser Periwinkle: "Lesser Periwinkle is known for its Cognitive enhancement, Vasodilation, Memory support effects.",
    Mistletoe: "Mistletoe is known for its Immune regulation, Sedation, Nervous system balance effects.",
    Sweet Acacia: "Sweet Acacia is known for its Relaxation, Calming, Uplifting mood effects.",
    Cramp Bark: "Cramp Bark is known for its Muscle relaxation, Menstrual relief, Sedative effects.",
    Chaste Tree Berry: "Chaste Tree Berry is known for its Hormone balance, PMS relief, Luteal phase support effects.",
    Grape Seed: "Grape Seed is known for its Vascular support, Free radical scavenging, Skin protection effects.",
    Gorse: "Gorse is known for its Mood elevation, Hope restoration, Mild nervous system support effects.",
    Valerian Root: "Valerian Root is known for its Sleep aid, Anxiety reduction, Muscle relaxation effects.",
    Mullein: "Mullein is known for its Lung soothing, Cough relief, Anti-inflammatory effects.",
    Five-Leaved Chaste Tree: "Five-Leaved Chaste Tree is known for its Pain relief, Anti-inflammatory, Respiratory support effects.",
    Himalayan Valerian: "Himalayan Valerian is known for its Sleep aid, Mental calm, Muscle relaxant effects.",
    Acacia Nilotica: "Acacia Nilotica is known for its Wound healing, Oral health, Diarrhea relief effects.",
    Dwarf Nettle: "Dwarf Nettle is known for its Skin soothing, Detox support, Mineral boost effects.",
    Blue Vervain: "Blue Vervain is known for its Stress relief, Mood regulation, Tension release effects.",
    Southern Prickly Ash: "Southern Prickly Ash is known for its Local anesthetic, Circulation stimulant, Nerve tonic effects.",
    Jujube: "Jujube is known for its Sleep support, Stress reduction, Digestive regulation effects.",
    Sichuan Pepper: "Sichuan Pepper is known for its Tingling sensation, Digestive stimulant, Mild analgesia effects.",
    Wild Jujube Seed: "Wild Jujube Seed is known for its Sleep promotion, Anxiety relief, Dream regulation effects.",
    Shampoo Ginger: "Shampoo Ginger is known for its Skin and hair care, Topical anti-inflammatory, Digestive aid effects.",
    Maconha Brava: "Maconha Brava is known for its Mild euphoria, Mental calm, Lucid dreaming effects.",
    Northern Prickly Ash: "Northern Prickly Ash is known for its Local numbness, Circulation boost, Lymphatic stimulation effects.",
    Twinleaf Zornia: "Twinleaf Zornia is known for its Relaxation, Mild psychoactive, Cough soothing effects.",
    Toothache Plant: "Toothache Plant is known for its Numbing, Tingling, Salivation effects.",
    Bael Fruit: "Bael Fruit is known for its Digestive regulation, Gut lining protection, Mild calm effects.",
    Oatstraw: "Oatstraw is known for its Stress relief, Mood stabilization, Endocrine tonic effects."
  },
  {
    name: "Artemisia abrotanum",
    slug: "artemisia-abrotanum",
    description: "Southernwood is a fragrant herb used traditionally as a stimulant, memory aid, and dream enhancer.",
    region: "Mediterranean, Europe",
    effects: ["mental clarity", "dream enhancement", "stimulant"],
    compounds: ["Camphor", "Thujone"],
    mechanismOfAction: "GABAergic + cholinergic modulation",
    tags: ["aromatic", "folk remedy", "uplifting"]
  },
  {
    name: "Heimia salicifolia",
    slug: "heimia-salicifolia",
    description: "Known as Sun Opener, this herb was used by the Aztecs for visionary and divinatory purposes.",
    region: "Mexico, Central America",
    effects: ["visionary", "relaxation", "lucid dream enhancement"],
    compounds: ["Cryogenine", "Lyfoline"],
    mechanismOfAction: "Serotonergic + anticholinergic",
    tags: ["oneirogen", "visionary", "shamanic"]
  },
  {
    name: "Bacopa monnieri",
    slug: "bacopa-monnieri",
    description: "Brahmi is an Ayurvedic nootropic herb that improves memory, learning, and mental clarity.",
    region: "India, Southeast Asia",
    effects: ["memory enhancement", "calm focus", "adaptogen"],
    compounds: ["Bacosides A and B"],
    mechanismOfAction: "Cholinergic + antioxidant",
    tags: ["nootropic", "Ayurvedic", "mental clarity"]
  },
  {
    name: "Nymphaea caerulea",
    slug: "nymphaea-caerulea",
    description: "The Blue Lotus of the Nile, used historically for sedative, aphrodisiac, and euphoric effects.",
    region: "Egypt, Africa",
    effects: ["euphoria", "relaxation", "mild sedation"],
    compounds: ["Aporphine", "Nuciferine"],
    mechanismOfAction: "Dopaminergic + serotonergic",
    tags: ["aphrodisiac", "sedative", "ritual"]
  },
  {
    name: "Huperzia serrata",
    slug: "huperzia-serrata",
    description: "A moss rich in Huperzine A, used for memory enhancement and neuroprotection.",
    region: "China, Southeast Asia",
    effects: ["focus", "memory boost", "lucid dreaming"],
    compounds: ["Huperzine A"],
    mechanismOfAction: "Acetylcholinesterase inhibition",
    tags: ["nootropic", "lucidity", "memory"]
  },
  {
    name: "Justicia adhatoda",
    slug: "justicia-adhatoda",
    description: "Also called Malabar Nut, this herb has traditional uses as a respiratory aid and mild sedative.",
    region: "India, Sri Lanka",
    effects: ["calming", "respiratory clearing", "mild sedation"],
    compounds: ["Vasicine", "Vasicinone"],
    mechanismOfAction: "Bronchodilation + GABAergic",
    tags: ["sedative", "respiratory", "Ayurvedic"]
  },
  {
    name: "Tilia europaea",
    slug: "tilia-europaea",
    description: "Common Linden, used in European herbalism for calming, dream-enhancing, and tension relief.",
    region: "Europe",
    effects: ["calming", "mild euphoria", "dream enhancement"],
    compounds: ["Volatile oils", "Tiliroside"],
    mechanismOfAction: "GABAergic + serotonergic",
    tags: ["folk medicine", "calming", "dream"]
  },
  {
    name: "Pogostemon cablin",
    slug: "pogostemon-cablin",
    description: "Patchouli, while mainly aromatic, has mild psychoactive effects in traditional incense rituals.",
    region: "Asia",
    effects: ["sensory enhancement", "calm focus", "uplifted mood"],
    compounds: ["Patchoulol", "Alpha-bulnesene"],
    mechanismOfAction: "Aromatherapeutic + serotonergic",
    tags: ["aromatic", "ritual", "uplifting"]
  },
  {
    name: "Anadenanthera colubrina",
    slug: "anadenanthera-colubrina",
    description: "Source of vilca snuff; contains powerful tryptamines used in South American shamanism.",
    region: "South America",
    effects: ["visionary", "intense dissociation", "time distortion"],
    compounds: ["Bufotenine", "DMT"],
    mechanismOfAction: "5-HT2A agonism",
    tags: ["shamanic", "tryptamine", "snuff"]
  },
  {
    name: "Aloysia citrodora",
    slug: "aloysia-citrodora",
    description: "Lemon Verbena, a gentle herbal tea with calming and mood-lifting effects.",
    region: "South America",
    effects: ["calm", "relaxation", "light euphoria"],
    compounds: ["Citral", "Verbascoside"],
    mechanismOfAction: "GABAergic + serotonergic",
    tags: ["tea", "folk remedy", "calming"]
  },
  {
    name: "Heimia salicifolia",
    slug: "heimia-salicifolia",
    description: "Also known as Sinicuichi, this Central American herb is used traditionally to induce auditory distortions and mild euphoria.",
    region: "Central America",
    effects: ["auditory distortion", "euphoria", "dreamlike"],
    compounds: ["Cryogenine"],
    mechanismOfAction: "GABAergic modulation",
    tags: ["ethnobotanical", "dream", "mildly psychoactive"]
  },
  {
    name: "Acorus calamus",
    slug: "acorus-calamus",
    description: "Sweet Flag has a complex pharmacology: stimulant in low doses, sedative in high. Historically used in Ayurvedic and Native American medicine.",
    region: "Eurasia / North America",
    effects: ["sedative", "stimulant", "anxiolytic"],
    compounds: ["Beta-Asarone"],
    mechanismOfAction: "GABAergic and cholinergic modulation",
    tags: ["calming", "traditional", "aromatic"]
  },
  {
    name: "Leonurus sibiricus",
    slug: "leonurus-sibiricus",
    description: "Known as Siberian Motherwort, this herb is a relaxing nervine used in Asian medicine with mild psychoactive and aphrodisiac effects.",
    region: "Siberia, China",
    effects: ["relaxation", "mood lift", "aphrodisiac"],
    compounds: ["Leonurine"],
    mechanismOfAction: "Dopaminergic modulation",
    tags: ["aphrodisiac", "nervine", "calming"]
  },
  {
    name: "Dysphania ambrosioides",
    slug: "dysphania-ambrosioides",
    description: "Also known as Epazote, used in Mesoamerican rituals. Contains CNS-stimulating compounds but is toxic at high doses.",
    region: "Mexico",
    effects: ["dreamlike", "stimulant"],
    compounds: ["Ascaridole", "p-Cymene"],
    mechanismOfAction: "CNS excitation at high doses",
    tags: ["ritual", "visionary", "potentially toxic"]
  },
  {
    name: "Casimiroa edulis",
    slug: "casimiroa-edulis",
    description: "The fruit of the White Sapote tree is used as a sedative in traditional Mexican herbal medicine.",
    region: "Central America",
    effects: ["sedative", "sleep aid"],
    compounds: ["Zapotin"],
    mechanismOfAction: "Possible GABAergic activity",
    tags: ["sedative", "fruit", "folk medicine"]
  },
  {
    name: "Mitchella repens",
    slug: "mitchella-repens",
    description: "Known as Partridgeberry, used as a uterine tonic and mild relaxing agent in North American herbalism.",
    region: "North America",
    effects: ["relaxation", "nervine"],
    compounds: ["Saponins", "Iridoids"],
    mechanismOfAction: "Smooth muscle relaxant",
    tags: ["calming", "uterine", "folk remedy"]
  },
  {
    name: "Perilla frutescens",
    slug: "perilla-frutescens",
    description: "Used in East Asian cuisine and medicine, this leaf contains mild mood-elevating and cognitive enhancing properties.",
    region: "East Asia",
    effects: ["uplifting", "calm clarity"],
    compounds: ["Perillaldehyde", "Rosmarinic Acid"],
    mechanismOfAction: "Cholinergic + antioxidant effects",
    tags: ["mild nootropic", "culinary", "relaxing"]
  },
  {
    name: "Turnera diffusa var. aphrodisiaca",
    slug: "turnera-diffusa-aphrodisiaca",
    description: "A variant of Damiana known for its aphrodisiac and mood-brightening properties. Traditionally used as a tonic.",
    region: "Mexico",
    effects: ["aphrodisiac", "mood enhancer"],
    compounds: ["Damianin", "Flavonoids"],
    mechanismOfAction: "Dopaminergic and GABAergic synergy",
    tags: ["aphrodisiac", "tonic", "euphoric"]
  },
  {
    name: "Thymus vulgaris",
    slug: "thymus-vulgaris",
    description: "Common thyme is a culinary herb with mild neurostimulant properties, thanks to its essential oils like thymol.",
    region: "Europe",
    effects: ["clarity", "alertness"],
    compounds: ["Thymol"],
    mechanismOfAction: "AChE inhibition, antioxidant",
    tags: ["culinary", "clarity", "aromatic"]
  },
  {
    name: "Helichrysum odoratissimum",
    slug: "helichrysum-odoratissimum",
    description: "Known as Imphepho in South African ritual use, this herb induces visions and is burned to invoke ancestors.",
    region: "Southern Africa",
    effects: ["visionary", "trance", "spiritual"],
    compounds: ["Essential oils", "Flavonoids"],
    mechanismOfAction: "Possibly serotonergic/GABAergic",
    tags: ["dream herb", "ritual", "African traditional medicine"]
  },
  {
    name: "Thujone",
    type: "monoterpene ketone",
    description: "A GABA receptor antagonist found in Mugwort and Wormwood, known for its psychoactive and convulsant potential.",
    foundIn: ["Artemisia vulgaris"],
    psychoactivity: "moderate",
    mechanismOfAction: "GABA-A receptor antagonism"
  },
  {
    name: "Camphor",
    type: "terpenoid",
    description: "An aromatic terpenoid with mild stimulant and decongestant effects, present in Mugwort and other herbs.",
    foundIn: ["Artemisia vulgaris"],
    psychoactivity: "mild",
    mechanismOfAction: "TRP channel modulation"
  },
  {
    name: "Asarone",
    type: "phenylpropanoid",
    description: "A bioactive component of Acorus species, structurally similar to psychoactive compounds and mildly sedative.",
    foundIn: ["Acorus gramineus"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic modulation"
  },
  {
    name: "Mesembrine",
    type: "alkaloid",
    description: "The primary alkaloid in Sceletium tortuosum (Kanna), acting as a serotonin reuptake inhibitor and mood enhancer.",
    foundIn: ["Sceletium tortuosum"],
    psychoactivity: "moderate",
    mechanismOfAction: "SERT inhibition"
  },
  {
    name: "Mesembrenone",
    type: "alkaloid",
    description: "A mood-lifting alkaloid in Kanna, shown to inhibit PDE4 and increase dopaminergic tone.",
    foundIn: ["Sceletium tortuosum"],
    psychoactivity: "moderate",
    mechanismOfAction: "PDE4 inhibition"
  },
  {
    name: "Germacranolides",
    type: "sesquiterpene lactone",
    description: "Bitter-tasting compounds in Calea ternifolia associated with oneirogenic effects.",
    foundIn: ["Calea ternifolia"],
    psychoactivity: "mild",
    mechanismOfAction: "Unknown, possibly cholinergic"
  },
  {
    name: "Triterpenoid saponins",
    type: "saponin",
    description: "Bioactive glycosides found in dream herbs like Silene capensis, often linked to vivid dreaming.",
    foundIn: ["Silene capensis"],
    psychoactivity: "mild",
    mechanismOfAction: "Unknown"
  },
  {
    name: "Quercetin",
    type: "flavonoid",
    description: "An antioxidant flavonoid with calming and neuroprotective properties.",
    foundIn: ["Tilia tomentosa"],
    psychoactivity: "mild",
    mechanismOfAction: "Anti-inflammatory + GABAergic support"
  },
  {
    name: "Volatile oils",
    type: "essential oil blend",
    description: "Aromatic oils in Tilia and other herbs that promote calm through olfactory and chemical pathways.",
    foundIn: ["Tilia tomentosa"],
    psychoactivity: "mild",
    mechanismOfAction: "Aromatherapy + mild sedation"
  },
  {
    name: "Estragole",
    type: "phenylpropene",
    description: "A sweet-smelling compound with mild psychoactive effects, found in Tagetes lucida.",
    foundIn: ["Tagetes lucida"],
    psychoactivity: "mild",
    mechanismOfAction: "Serotonergic + cholinergic activity"
  },
  {
    name: "Anethole",
    type: "phenylpropene",
    description: "A mildly psychoactive aromatic compound found in herbs like Mexican tarragon and anise.",
    foundIn: ["Tagetes lucida"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic modulation"
  },
  {
    name: "Coumarin",
    type: "benzopyrone",
    description: "A fragrant compound with sedative and anticoagulant properties found in Justicia pectoralis.",
    foundIn: ["Justicia pectoralis"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic modulation"
  },
  {
    name: "Umelliferone",
    type: "coumarin derivative",
    description: "A bioactive coumarin compound found in Justicia pectoralis, with possible serotonergic action.",
    foundIn: ["Justicia pectoralis"],
    psychoactivity: "mild",
    mechanismOfAction: "Serotonergic modulation"
  },
  {
    name: "Saponins",
    type: "glycoside",
    description: "Natural glycosides with foaming properties and mild relaxing effects, found in various dream herbs.",
    foundIn: ["Entada rheedii"],
    psychoactivity: "mild",
    mechanismOfAction: "Unknown"
  },
  {
    name: "Celastrine",
    type: "alkaloid",
    description: "A nootropic compound found in Celastrus paniculatus (Intellect tree), used to improve memory and clarity.",
    foundIn: ["Celastrus paniculatus"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic enhancement"
  },
  {
    name: "Paniculatin",
    type: "alkaloid",
    description: "One of the active components of Celastrus paniculatus, believed to promote alert calmness and mental energy.",
    foundIn: ["Celastrus paniculatus"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic activity"
  },
  {
    name: "Artemisia ludoviciana",
    slug: "artemisia-ludoviciana",
    description: "Also known as white sagebrush, used by Native American tribes for cleansing, dreams, and mild sedation.",
    region: "North America",
    effects: ["mild sedation", "visionary", "cleansing"],
    compounds: ["Thujone", "Camphor"],
    mechanismOfAction: "GABAergic + anticholinergic",
    tags: ["ritual", "dream", "folk medicine"]
  },
  {
    name: "Turnera diffusa",
    slug: "turnera-diffusa",
    description: "Damiana is an aphrodisiac and mood enhancer used in Mexican herbal traditions and modern blends.",
    region: "Mexico, Central America",
    effects: ["euphoria", "stimulation", "aphrodisiac"],
    compounds: ["Damianin", "Flavonoids"],
    mechanismOfAction: "Dopaminergic + GABAergic",
    tags: ["aphrodisiac", "tea", "tonic"]
  },
  {
    name: "Viola odorata",
    slug: "viola-odorata",
    description: "Sweet Violet, mildly sedative and anxiolytic, traditionally used for grief, tension, and calm dreams.",
    region: "Europe, Asia",
    effects: ["relaxation", "emotional clarity", "sleep aid"],
    compounds: ["Violine", "Methyl salicylate"],
    mechanismOfAction: "GABAergic + anti-inflammatory",
    tags: ["folk remedy", "sedative", "emotional"]
  },
  {
    name: "Petasites hybridus",
    slug: "petasites-hybridus",
    description: "Butterbur, once used for headaches and anxiety. Contains pyrrolizidine alkaloids — caution advised.",
    region: "Europe",
    effects: ["anti-anxiety", "vasodilation", "headache relief"],
    compounds: ["Petasin", "Isopetasin"],
    mechanismOfAction: "Smooth muscle relaxant + serotonergic",
    tags: ["nervine", "headache", "caution"]
  },
  {
    name: "Zanthoxylum clava-herculis",
    slug: "zanthoxylum-clava-herculis",
    description: "The Toothache Tree, used for numbing, mild stimulation, and ritual practices in the American South.",
    region: "Southeastern USA",
    effects: ["numbing", "alertness", "tingling"],
    compounds: ["Zanthoxylin", "Lignans"],
    mechanismOfAction: "Local anesthetic + sensory modulation",
    tags: ["ritual", "numbing", "tingle"]
  },
  {
    name: "Arundo donax",
    slug: "arundo-donax",
    description: "A tall reed containing trace tryptamines; rarely used, but investigated for its chemical potential.",
    region: "Mediterranean, Asia",
    effects: ["visionary (potential)", "altered state (speculative)"],
    compounds: ["DMT (trace)", "Bufotenine (trace)"],
    mechanismOfAction: "5-HT2A agonist (hypothetical)",
    tags: ["tryptamine", "experimental", "rare"]
  },
  {
    name: "Betula lenta",
    slug: "betula-lenta",
    description: "Sweet Birch, aromatic and uplifting; contains methyl salicylate, offering mild euphoria and clarity.",
    region: "North America",
    effects: ["uplifting", "mental clarity", "aromatic"],
    compounds: ["Methyl salicylate"],
    mechanismOfAction: "Anti-inflammatory + mild serotonergic",
    tags: ["tea", "uplifting", "aromatic"]
  },
  {
    name: "Nepeta cataria",
    slug: "nepeta-cataria",
    description: "Catnip, while famous for feline effects, produces mild sedation and mood elevation in humans.",
    region: "Europe, Asia, North America",
    effects: ["mild euphoria", "relaxation", "calming"],
    compounds: ["Nepetalactone", "Iridoids"],
    mechanismOfAction: "GABAergic + calming",
    tags: ["tea", "folk remedy", "calming"]
  },
  {
    name: "Scutellaria lateriflora",
    slug: "scutellaria-lateriflora",
    description: "American Skullcap is a revered nervine herb promoting relaxation, calm, and sleep.",
    region: "North America",
    effects: ["sedation", "calm", "anxiety relief"],
    compounds: ["Baicalin", "Scutellarin"],
    mechanismOfAction: "GABAergic",
    tags: ["nervine", "folk remedy", "sleep aid"]
  },
  {
    name: "Tussilago farfara",
    slug: "tussilago-farfara",
    description: "Coltsfoot, used in traditional teas for respiratory support and light sedation.",
    region: "Europe, Asia",
    effects: ["soothing", "light sedation", "respiratory ease"],
    compounds: ["Mucilage", "Tussilagone"],
    mechanismOfAction: "Smooth muscle relaxation + respiratory support",
    tags: ["respiratory", "sedative", "folk medicine"]
  },
  {
    name: "Thujone",
    type: "monoterpene ketone",
    description: "A GABA receptor antagonist with stimulating and dream-enhancing effects, found in Artemisia species.",
    foundIn: ["Artemisia ludoviciana"],
    psychoactivity: "mild",
    mechanismOfAction: "GABA-A receptor antagonist"
  },
  {
    name: "Damianin",
    type: "terpenoid compound",
    description: "A compound in Damiana believed to contribute to its aphrodisiac and euphoric effects.",
    foundIn: ["Turnera diffusa"],
    psychoactivity: "mild",
    mechanismOfAction: "Unknown; dopaminergic and GABAergic suspected"
  },
  {
    name: "Violine",
    type: "alkaloid",
    description: "A compound in Sweet Violet with sedative and mildly hypnotic effects.",
    foundIn: ["Viola odorata"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic"
  },
  {
    name: "Petasin",
    type: "sesquiterpene",
    description: "A compound in Butterbur used to relieve headaches and anxiety through smooth muscle relaxation.",
    foundIn: ["Petasites hybridus"],
    psychoactivity: "mild",
    mechanismOfAction: "Smooth muscle relaxant + serotonergic"
  },
  {
    name: "Zanthoxylin",
    type: "alkylamide",
    description: "A numbing and tingling agent in the Toothache Tree with mild sensory effects.",
    foundIn: ["Zanthoxylum clava-herculis"],
    psychoactivity: "mild",
    mechanismOfAction: "Local anesthetic"
  },
  {
    name: "Methyl salicylate",
    type: "ester",
    description: "An aromatic compound with anti-inflammatory and uplifting properties found in birch and violet.",
    foundIn: ["Betula lenta", "Viola odorata"],
    psychoactivity: "mild",
    mechanismOfAction: "Anti-inflammatory + serotonergic"
  },
  {
    name: "Nepetalactone",
    type: "iridoid monoterpene",
    description: "Primary compound in Catnip with calming, euphoric, and slightly hallucinogenic effects in animals and mild effects in humans.",
    foundIn: ["Nepeta cataria"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + olfactory"
  },
  {
    name: "Baicalin",
    type: "flavone glycoside",
    description: "A GABAergic flavonoid in Skullcap responsible for its calming and anxiolytic properties.",
    foundIn: ["Scutellaria lateriflora"],
    psychoactivity: "mild",
    mechanismOfAction: "GABA-A receptor modulation"
  },
  {
    name: "Tussilagone",
    type: "sesquiterpene",
    description: "A compound in Coltsfoot with antitussive and calming properties.",
    foundIn: ["Tussilago farfara"],
    psychoactivity: "mild",
    mechanismOfAction: "Smooth muscle relaxation"
  },
  {
    name: "DMT",
    type: "tryptamine",
    description: "A powerful hallucinogenic compound found in trace amounts in Arundo donax and various entheogens.",
    foundIn: ["Arundo donax"],
    psychoactivity: "strong",
    mechanismOfAction: "5-HT2A receptor agonist"
  },
  {
    name: "Bufotenine",
    type: "tryptamine",
    description: "A powerful entheogenic compound, trace in Arundo donax, with visual and dissociative effects.",
    foundIn: ["Arundo donax"],
    psychoactivity: "strong",
    mechanismOfAction: "5-HT2A receptor agonist"
  },
  {
    name: "Camphor",
    type: "terpenoid ketone",
    description: "A cooling aromatic compound with stimulating and mildly dissociative effects in high doses.",
    foundIn: ["Artemisia abrotanum"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + sensory modulation"
  },
  {
    name: "Cryogenine",
    type: "alkaloid",
    description: "A psychoactive compound in Heimia salicifolia, associated with altered perception and lucid dreaming.",
    foundIn: ["Heimia salicifolia"],
    psychoactivity: "moderate",
    mechanismOfAction: "Serotonergic + anticholinergic"
  },
  {
    name: "Bacosides A and B",
    type: "triterpenoid saponins",
    description: "Primary active nootropic agents in Bacopa, supporting memory, learning, and neuroplasticity.",
    foundIn: ["Bacopa monnieri"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic + neuroprotective"
  },
  {
    name: "Aporphine",
    type: "aporphine alkaloid",
    description: "A dopamine agonist with sedative and euphoric effects found in Blue Lotus.",
    foundIn: ["Nymphaea caerulea"],
    psychoactivity: "moderate",
    mechanismOfAction: "Dopamine receptor agonist"
  },
  {
    name: "Huperzine A",
    type: "alkaloid",
    description: "A potent acetylcholinesterase inhibitor that enhances memory and dream lucidity.",
    foundIn: ["Huperzia serrata"],
    psychoactivity: "moderate",
    mechanismOfAction: "Acetylcholinesterase inhibition"
  },
  {
    name: "Vasicine",
    type: "quinazoline alkaloid",
    description: "A bronchodilator and mild sedative found in Justicia adhatoda.",
    foundIn: ["Justicia adhatoda"],
    psychoactivity: "mild",
    mechanismOfAction: "Bronchodilation + GABAergic"
  },
  {
    name: "Tiliroside",
    type: "flavonoid glycoside",
    description: "A calming compound in Linden with antioxidant and mild GABAergic activity.",
    foundIn: ["Tilia europaea"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + antioxidant"
  },
  {
    name: "Patchoulol",
    type: "sesquiterpene alcohol",
    description: "A main compound in Patchouli oil with grounding, relaxing properties in aromatherapy.",
    foundIn: ["Pogostemon cablin"],
    psychoactivity: "mild",
    mechanismOfAction: "Aromatherapeutic + serotonergic"
  },
  {
    name: "Bufotenine",
    type: "tryptamine",
    description: "A powerful psychedelic compound found in vilca and toad venom, causing intense visual effects.",
    foundIn: ["Anadenanthera colubrina"],
    psychoactivity: "strong",
    mechanismOfAction: "5-HT2A receptor agonist"
  },
  {
    name: "Verbascoside",
    type: "phenylpropanoid glycoside",
    description: "A calming antioxidant compound with potential mood-brightening effects found in Lemon Verbena.",
    foundIn: ["Aloysia citrodora"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + serotonergic"
  },
  {
    name: "Cryogenine",
    type: "alkaloid",
    description: "A sedating alkaloid found in Heimia salicifolia, known for its auditory distortion and calm-inducing properties.",
    foundIn: ["Heimia salicifolia"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic modulation"
  },
  {
    name: "Beta-Asarone",
    type: "phenylpropanoid",
    description: "A compound found in Acorus calamus with controversial stimulant and sedative properties depending on dose.",
    foundIn: ["Acorus calamus"],
    psychoactivity: "moderate",
    mechanismOfAction: "Cholinergic and GABAergic modulation"
  },
  {
    name: "Leonurine",
    type: "alkaloid",
    description: "An alkaloid found in Leonurus sibiricus with relaxing and dopaminergic effects.",
    foundIn: ["Leonurus sibiricus"],
    psychoactivity: "mild",
    mechanismOfAction: "Dopamine receptor modulation"
  },
  {
    name: "Ascaridole",
    type: "terpene",
    description: "A monoterpene peroxide in Epazote, responsible for stimulant and toxic properties at high doses.",
    foundIn: ["Dysphania ambrosioides"],
    psychoactivity: "mild",
    mechanismOfAction: "CNS stimulation (dose-dependent)"
  },
  {
    name: "p-Cymene",
    type: "terpene",
    description: "A naturally occurring aromatic terpene with stimulant and antioxidant properties.",
    foundIn: ["Dysphania ambrosioides"],
    psychoactivity: "mild",
    mechanismOfAction: "Neurostimulant and antioxidant effects"
  },
  {
    name: "Zapotin",
    type: "flavonoid",
    description: "A sedating flavonoid compound from Casimiroa edulis used in traditional medicine for insomnia.",
    foundIn: ["Casimiroa edulis"],
    psychoactivity: "moderate",
    mechanismOfAction: "Possibly GABAergic"
  },
  {
    name: "Saponins",
    type: "glycoside",
    description: "A class of plant glycosides with soothing and adaptogenic properties, found in Mitchella repens.",
    foundIn: ["Mitchella repens"],
    psychoactivity: "mild",
    mechanismOfAction: "Smooth muscle modulation"
  },
  {
    name: "Iridoids",
    type: "glycoside",
    description: "Bioactive compounds with anti-inflammatory and nervine properties, often used in traditional herbalism.",
    foundIn: ["Mitchella repens"],
    psychoactivity: "mild",
    mechanismOfAction: "Calming central nervous system modulation"
  },
  {
    name: "Perillaldehyde",
    type: "terpenoid",
    description: "An aromatic compound found in Perilla leaf with uplifting and calming properties.",
    foundIn: ["Perilla frutescens"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic activation"
  },
  {
    name: "Rosmarinic Acid",
    type: "phenolic acid",
    description: "An antioxidant and mood-stabilizing compound found in Perilla and other herbs.",
    foundIn: ["Perilla frutescens"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic + anti-inflammatory"
  },
  {
    name: "Damianin",
    type: "terpenoid",
    description: "A compound from Damiana associated with mood-enhancing and aphrodisiac properties.",
    foundIn: ["Turnera diffusa var. aphrodisiaca"],
    psychoactivity: "moderate",
    mechanismOfAction: "Dopaminergic stimulation + GABA synergy"
  },
  {
    name: "Flavonoids",
    type: "polyphenol",
    description: "A broad group of antioxidant compounds with mood-modulating and sedative effects.",
    foundIn: ["Turnera diffusa var. aphrodisiaca", "Helichrysum odoratissimum"],
    psychoactivity: "mild",
    mechanismOfAction: "Neuroprotective + receptor modulation"
  },
  {
    name: "Thymol",
    type: "monoterpene phenol",
    description: "An aromatic compound from thyme with stimulating and antimicrobial effects.",
    foundIn: ["Thymus vulgaris"],
    psychoactivity: "mild",
    mechanismOfAction: "AChE inhibition"
  },
  {
    name: "Essential oils",
    type: "volatile blend",
    description: "A mixture of bioactive volatile compounds used in rituals and aromatherapy with psychoactive potential.",
    foundIn: ["Helichrysum odoratissimum"],
    psychoactivity: "mild",
    mechanismOfAction: "Aromatherapy + serotonergic modulation"
  },
  {
    name: "Eugenol",
    type: "phenylpropene",
    description: "A fragrant oil with calming and mildly euphoric properties found in allspice and clove.",
    foundIn: ["Pimenta dioica"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + serotonergic modulation"
  },
  {
    name: "Lactucopicrin",
    type: "sesquiterpene lactone",
    description: "A bitter compound in Wild Lettuce associated with sedative and analgesic effects.",
    foundIn: ["Lactuca virosa"],
    psychoactivity: "mild",
    mechanismOfAction: "Opioid receptor modulation"
  },
  {
    name: "Lactucin",
    type: "sesquiterpene lactone",
    description: "Mildly psychoactive compound in Wild Lettuce contributing to its calming effects.",
    foundIn: ["Lactuca virosa"],
    psychoactivity: "mild",
    mechanismOfAction: "Opioid receptor modulation"
  },
  {
    name: "Boldine",
    type: "alkaloid",
    description: "An antioxidant alkaloid in Boldo with sedative and hepatoprotective properties.",
    foundIn: ["Peumus boldus"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic + serotonergic"
  },
  {
    name: "Ascaridole",
    type: "monoterpenoid peroxide",
    description: "A volatile compound in Boldo with hypnotic and anti-parasitic properties.",
    foundIn: ["Peumus boldus"],
    psychoactivity: "mild",
    mechanismOfAction: "Unknown, possible GABAergic"
  },
  {
    name: "Agnuside",
    type: "iridoid glycoside",
    description: "A dopaminergic compound in Chasteberry thought to influence hormonal balance and mood.",
    foundIn: ["Vitex agnus-castus"],
    psychoactivity: "mild",
    mechanismOfAction: "Dopaminergic + hormonal modulation"
  },
  {
    name: "Myristicin",
    type: "phenylpropene",
    description: "A deliriant and hallucinogenic compound in Nutmeg, psychoactive at high doses.",
    foundIn: ["Myristica fragrans"],
    psychoactivity: "moderate",
    mechanismOfAction: "MAOI + anticholinergic"
  },
  {
    name: "Elemicin",
    type: "phenylpropene",
    description: "Another psychoactive compound in Nutmeg, structurally related to mescaline.",
    foundIn: ["Myristica fragrans"],
    psychoactivity: "moderate",
    mechanismOfAction: "Anticholinergic + serotonergic"
  },
  {
    name: "Amorphigenin",
    type: "rotenoid compound",
    description: "A compound in Amorpha fruticosa with unclear psychoactivity, possibly relaxing or trance-inducing.",
    foundIn: ["Amorpha fruticosa"],
    psychoactivity: "mild",
    mechanismOfAction: "Possibly GABAergic"
  },
  {
    name: "Eleutherosides",
    type: "glycosides",
    description: "A group of adaptogenic compounds found in Siberian Ginseng with neuroprotective properties.",
    foundIn: ["Eleutherococcus senticosus"],
    psychoactivity: "mild",
    mechanismOfAction: "Adaptogenic + neuroregulatory"
  },
  {
    name: "Verbenalin",
    type: "iridoid glycoside",
    description: "A compound found in vervain, associated with sedative and spiritually clarifying effects.",
    foundIn: ["Verbena officinalis"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic"
  },
  {
    name: "Citral",
    type: "monoterpene aldehyde",
    description: "A lemon-scented terpene with calming and mood-brightening effects.",
    foundIn: ["Melissa officinalis"],
    psychoactivity: "mild",
    mechanismOfAction: "GABA-T inhibition + serotonergic"
  },
  {
    name: "Rosmarinic acid",
    type: "polyphenol",
    description: "An anxiolytic compound in lemon balm with antioxidant and calming effects.",
    foundIn: ["Melissa officinalis"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + anti-inflammatory"
  },
  {
    name: "Alpha-asarone",
    type: "phenylpropanoid",
    description: "A psychoactive compound from Acorus species known for stimulant and cognition-enhancing effects.",
    foundIn: ["Acorus americanus"],
    psychoactivity: "mild",
    mechanismOfAction: "Cholinergic + dopaminergic modulation"
  },
  {
    name: "DMT",
    type: "tryptamine",
    description: "A powerful serotonergic psychedelic found in Virola and numerous other plants.",
    foundIn: ["Virola theiodora"],
    psychoactivity: "strong",
    mechanismOfAction: "5-HT2A receptor agonist"
  },
  {
    name: "5-MeO-DMT",
    type: "tryptamine",
    description: "A potent serotonergic compound with fast-acting dissociative and mystical effects.",
    foundIn: ["Virola theiodora"],
    psychoactivity: "strong",
    mechanismOfAction: "5-HT1A and 5-HT2A receptor agonist"
  },
  {
    name: "Rutarin",
    type: "alkaloid",
    description: "A bitter alkaloid in Ruta graveolens, traditionally used for sedative and mystical purposes.",
    foundIn: ["Ruta graveolens"],
    psychoactivity: "mild",
    mechanismOfAction: "GABA-A modulation"
  },
  {
    name: "Graveoline",
    type: "alkaloid",
    description: "An alkaloid from Rue associated with sedative and possible antispasmodic effects.",
    foundIn: ["Ruta graveolens"],
    psychoactivity: "mild",
    mechanismOfAction: "Unclear, likely GABAergic"
  },
  {
    name: "Chrysin",
    type: "flavonoid",
    description: "A bioflavonoid with anxiolytic and MAO-inhibiting properties found in Passionflower.",
    foundIn: ["Passiflora incarnata"],
    psychoactivity: "mild",
    mechanismOfAction: "GABA-A agonist + MAOI"
  },
  {
    name: "Harmine (trace)",
    type: "beta-carboline",
    description: "A reversible MAOI found in low levels in Passionflower, structurally related to compounds in Ayahuasca.",
    foundIn: ["Passiflora incarnata"],
    psychoactivity: "mild",
    mechanismOfAction: "MAO-A inhibition"
  },
  {
    name: "Cytisine",
    type: "alkaloid",
    description: "A toxic yet psychoactive compound that acts on nicotinic receptors; found in Mescal bean.",
    foundIn: ["Sophora secundiflora"],
    psychoactivity: "moderate",
    mechanismOfAction: "Nicotinic receptor agonist"
  },
  {
    name: "Desmodin",
    type: "alkaloid",
    description: "An alkaloid compound with neuroprotective and adaptogenic properties found in Desmodium.",
    foundIn: ["Desmodium gangeticum"],
    psychoactivity: "mild",
    mechanismOfAction: "Neuroprotective + serotonergic modulation"
  },
  {
    name: "Triterpenoids",
    type: "triterpene",
    description: "Compounds with anti-inflammatory and tonic properties found in Desmodium species.",
    foundIn: ["Desmodium gangeticum"],
    psychoactivity: "mild",
    mechanismOfAction: "Anti-inflammatory, adaptogenic"
  },
  {
    name: "Ergoline alkaloids (trace)",
    type: "ergoline",
    description: "Ergoline derivatives possibly present in Bindweed, structurally related to LSD precursors.",
    foundIn: ["Convolvulus arvensis"],
    psychoactivity: "mild",
    mechanismOfAction: "5-HT2A receptor activity"
  },
  {
    name: "Linalyl acetate",
    type: "ester",
    description: "A fragrant ester found in clary sage, with mood-lifting and calming effects.",
    foundIn: ["Salvia sclarea"],
    psychoactivity: "mild",
    mechanismOfAction: "GABAergic + aromatherapeutic"
  },
  {
    name: "Sclareol",
    type: "diterpene alcohol",
    description: "A compound from clary sage with mild euphoria, possible hormonal modulation, and relaxing effects.",
    foundIn: ["Salvia sclarea"],
    psychoactivity: "mild",
    mechanismOfAction: "Estrogenic + GABAergic activity"
  },
  {
    name: "Artemisia vulgaris",
    slug: "artemisia-vulgaris",
    description: "Known as Mugwort, traditionally used in European and Asian cultures for vivid dreaming, menstrual relief, and mild psychedelic effects.",
    region: "Europe, Asia",
    effects: ["vivid dreaming", "relaxation", "mild hallucination"],
    compounds: ["Thujone", "Camphor"],
    mechanismOfAction: "GABA-A modulation, possible NMDA antagonist",
    tags: ["dream", "ritual", "traditional"]
  },
  {
    name: "Acorus gramineus",
    slug: "acorus-gramineus",
    description: "Japanese Sweet Flag used in Shinto and Buddhist rituals, mildly stimulating and cognition-enhancing.",
    region: "East Asia",
    effects: ["clarity", "stimulant", "focus"],
    compounds: ["Asarone"],
    mechanismOfAction: "Cholinergic and GABAergic modulation",
    tags: ["traditional", "mild nootropic", "aromatic"]
  },
  {
    name: "Sceletium tortuosum",
    slug: "sceletium-tortuosum",
    description: "Known as Kanna, this South African succulent elevates mood and reduces anxiety. Used as a fermented chew.",
    region: "South Africa",
    effects: ["euphoria", "anxiolytic", "social enhancer"],
    compounds: ["Mesembrine", "Mesembrenone"],
    mechanismOfAction: "SERT inhibition, PDE4 inhibition",
    tags: ["mood", "euphoric", "entactogen"]
  },
  {
    name: "Calea ternifolia",
    slug: "calea-ternifolia",
    description: "Mexican Dream Herb used in lucid dreaming rituals by the Chontal people. Bitter but effective in inducing hypnagogic visions.",
    region: "Mexico",
    effects: ["lucid dreaming", "hypnagogia", "mental clarity"],
    compounds: ["Germacranolides"],
    mechanismOfAction: "Unknown, possible cholinergic",
    tags: ["dream", "visionary", "ritual"]
  },
  {
    name: "Silene capensis",
    slug: "silene-capensis",
    description: "African Dream Root, revered by the Xhosa people for enhancing vivid and prophetic dreams.",
    region: "Southern Africa",
    effects: ["vivid dreaming", "trance", "vision"],
    compounds: ["Triterpenoid saponins"],
    mechanismOfAction: "Unknown, possibly cholinergic",
    tags: ["dream", "African traditional", "visionary"]
  },
  {
    name: "Tilia tomentosa",
    slug: "tilia-tomentosa",
    description: "Silver Linden, used as a calming tea in Europe. Shows sedative and anti-anxiety effects.",
    region: "Europe",
    effects: ["calming", "sleep aid", "nervine"],
    compounds: ["Quercetin", "Volatile oils"],
    mechanismOfAction: "GABAergic, anti-inflammatory",
    tags: ["relaxing", "tea", "folk medicine"]
  },
  {
    name: "Tagetes lucida",
    slug: "tagetes-lucida",
    description: "Mexican Tarragon, used by the Aztecs and modern shamans as a mild psychedelic and incense.",
    region: "Mexico",
    effects: ["euphoria", "visionary", "clarity"],
    compounds: ["Estragole", "Anethole"],
    mechanismOfAction: "Serotonergic and cholinergic",
    tags: ["ritual", "psychoactive incense", "traditional"]
  },
  {
    name: "Justicia pectoralis",
    slug: "justicia-pectoralis",
    description: "Known as tilo or chambá, this Amazonian herb is mildly relaxing and sometimes added to snuffs and brews.",
    region: "Amazon basin",
    effects: ["relaxing", "mild euphoria"],
    compounds: ["Coumarin", "Umelliferone"],
    mechanismOfAction: "GABAergic and serotonergic",
    tags: ["mild sedative", "additive", "traditional"]
  },
  {
    name: "Entada rheedii",
    slug: "entada-rheedii",
    description: "African Dream Bean, used to access ancestor spirits in dreams; seeds are large and traditionally worn as talismans.",
    region: "Africa",
    effects: ["dream enhancement", "spiritual connection"],
    compounds: ["Saponins"],
    mechanismOfAction: "Unknown",
    tags: ["dream", "ethnobotanical", "ritual"]
  },
  {
    name: "Celastrus paniculatus",
    slug: "celastrus-paniculatus",
    description: "Intellect tree from Ayurveda; used to enhance memory and mental clarity, with mild stimulation.",
    region: "India",
    effects: ["focus", "mental clarity", "calm alertness"],
    compounds: ["Celastrine", "Paniculatin"],
    mechanismOfAction: "Cholinergic",
    tags: ["nootropic", "Ayurvedic", "seed oil"]
  },
  {
    id: "acacia-confusa",
    name: "Acacia confusa",
    slug: "acacia-confusa",
    scientificName: "Acacia confusa",
    category: "Psychedelic",
    effects: ["Psychedelic", "Introspective", "Sedating"],
    description: "A root bark source of DMT and other tryptamines traditionally used in Pacific Island cultures.",
    mechanismOfAction: "Contains N,N-DMT and related tryptamines; acts as a serotonergic psychedelic via 5-HT2A receptor agonism.",
    pharmacokinetics: "Inactive orally unless taken with an MAOI. Smoked or brewed in analog ayahuasca preparations.",
    therapeuticUses: "Exploration, visionary states, introspection. Not medically approved.",
    sideEffects: "Nausea, anxiety, dissociation. Potentiated when used with MAOIs.",
    contraindications: "Do not combine with SSRIs, MAOIs, or substances affecting serotonin. Not for use with heart or mental health conditions.",
    drugInteractions: "Strong interaction with MAOIs. Risk of serotonin syndrome with SSRIs or other psychedelics.",
    toxicity: "Not well studied. Risk primarily from MAOI co-administration.",
    toxicityLD50: "Unknown",
    preparation: "Root bark is shredded and either smoked or brewed with MAOIs like Syrian Rue.",
    onset: "20–60 min (with MAOI)",
    intensity: "Strong",
    safetyRating: "low",
    legalStatus: "DMT-containing; illegal in many jurisdictions.",
    region: "Southeast Asia, Pacific Islands",
    tags: [" Tryptamine", "⛔ MAOI-sensitive", " Visionary"],
    sources: ["https://erowid.org/plants/acacia_confusa/", "PubChem CID: 6089", "J Ethnopharmacol. 2005"],
    needsReview: false
  },
  {
    id: "acacia-maidenii",
    name: "Acacia maidenii",
    slug: "acacia-maidenii",
    scientificName: "Acacia maidenii",
    category: "Psychedelic",
    effects: ["Entheogenic", "Dream-like"],
    description: "An Australian Acacia species containing DMT and other tryptamines in its bark.",
    mechanismOfAction: "Tryptamine alkaloids (primarily N,N-DMT) act as 5-HT2A receptor agonists producing psychedelic effects.",
    pharmacokinetics: "Requires MAOI for oral activity; often used in ayahuasca analogues or vaporized.",
    therapeuticUses: "Exploration, spiritual insight, not recognized for medical use.",
    sideEffects: "Dizziness, confusion, nausea when combined with MAOIs.",
    contraindications: "Avoid combining with antidepressants, stimulants, or cardiovascular medications.",
    drugInteractions: "Dangerous with MAOIs or SSRIs. Risk of hypertensive crisis.",
    toxicity: "Potentially toxic with improper MAOI use.",
    toxicityLD50: "Unknown",
    preparation: "Shredded bark brewed in ayahuasca-style tea or vaporized.",
    onset: "30–60 min (with MAOI)",
    intensity: "High",
    safetyRating: "low",
    legalStatus: "Controlled in many countries due to DMT.",
    region: "Australia",
    tags: ["⛔ Controlled", " Entheogen", " DMT"],
    sources: ["https://erowid.org/plants/acacia_maidenii/", "PubMed ID: 21798319"],
    needsReview: false
  },
  {
    id: "acorus-calamus",
    name: "Acorus calamus",
    slug: "acorus-calamus",
    scientificName: "Acorus calamus",
    category: "Deliriant",
    effects: ["Hallucinogenic", "Sedative", "Stimulant (low dose)"],
    description: "A marshland rhizome used in Ayurveda and folklore for its aromatic and psychoactive properties.",
    mechanismOfAction: "Beta-asarone is a major active, possibly GABAergic and anticholinergic at high doses. Deliriant-like in excess.",
    pharmacokinetics: "Orally active. Effects vary by subspecies (American vs. Asian).",
    therapeuticUses: "Traditionally used for digestion, memory, and calming the mind.",
    sideEffects: "Nausea, hallucinations, confusion at high doses.",
    contraindications: "Pregnancy, epilepsy, liver disease.",
    drugInteractions: "Unknown; caution with CNS depressants.",
    toxicity: "Beta-asarone is carcinogenic in rodents. High doses may be neurotoxic.",
    toxicityLD50: "1,230 mg/kg (rats, oral, beta-asarone)",
    preparation: "Dried rhizome chewed or infused.",
    onset: "1 hour",
    intensity: "Mild–Moderate",
    safetyRating: "medium",
    legalStatus: "Restricted or banned in some countries (e.g. USA)",
    region: "Asia, North America, Europe",
    tags: [" Root", " Nootropic", "⚠️ Deliriant"],
    sources: ["https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6383205/", "PubChem CID: 73568"],
    needsReview: false
  },
  {
    name: "Acorus americanus",
    slug: "acorus-americanus",
    description: "American Sweet Flag, native to North America, used by indigenous groups for its psychoactive and stimulant properties.",
    region: "North America",
    effects: ["alertness", "mental clarity", "mild euphoria"],
    compounds: ["Alpha-asarone"],
    mechanismOfAction: "Cholinergic + dopaminergic modulation",
    tags: ["native medicine", "calamus species", "uplifting"]
  },
  {
    name: "Virola theiodora",
    slug: "virola-theiodora",
    description: "A South American tree whose resin contains potent tryptamines. Used in snuffs by Amazonian tribes.",
    region: "Amazon Basin",
    effects: ["visionary", "intense euphoria", "dissociation"],
    compounds: ["DMT", "5-MeO-DMT"],
    mechanismOfAction: "Serotonin receptor agonist (5-HT2A)",
    tags: ["snuff", "shamanic", "tryptamine"]
  },
  {
    name: "Ruta graveolens",
    slug: "ruta-graveolens",
    description: "Common Rue, used historically as a sedative, an abortifacient, and for spiritual protection.",
    region: "Mediterranean",
    effects: ["relaxation", "hypnotic", "mystical"],
    compounds: ["Rutarin", "Graveoline"],
    mechanismOfAction: "GABA-A modulation, alkaloid effects",
    tags: ["ritual", "bitter", "traditional medicine"]
  },
  {
    name: "Arundo donax",
    slug: "arundo-donax",
    description: "Giant Reed contains trace tryptamines and has been proposed as an Ayahuasca analog component.",
    region: "Mediterranean, Asia",
    effects: ["light euphoria", "dreaminess"],
    compounds: ["DMT (trace)", "Bufotenine (trace)"],
    mechanismOfAction: "Serotonergic (possible)",
    tags: ["analogue", "reed grass", "entheogenic interest"]
  },
  {
    name: "Passiflora incarnata",
    slug: "passiflora-incarnata",
    description: "Passionflower is a mild sedative and anxiolytic with MAO-inhibiting flavonoids. Common in herbal teas.",
    region: "North & Central America",
    effects: ["calming", "dreamy", "sedative"],
    compounds: ["Chrysin", "Harmine (trace)"],
    mechanismOfAction: "GABA-A agonist + mild MAOI",
    tags: ["sleep", "relaxant", "folk medicine"]
  },
  {
    name: "Sophora secundiflora",
    slug: "sophora-secundiflora",
    description: "Mescal bean, used ceremonially by Native American tribes. Highly toxic, formerly used as an ordeal poison.",
    region: "Southwestern US, Mexico",
    effects: ["delirium", "visions", "dizziness"],
    compounds: ["Cytisine"],
    mechanismOfAction: "Nicotinic receptor agonist",
    tags: ["ceremonial", "toxic", "visionary"]
  },
  {
    name: "Desmodium gangeticum",
    slug: "desmodium-gangeticum",
    description: "An Ayurvedic herb with antistress, adaptogenic, and cognitive benefits. Traditionally used to support vitality.",
    region: "India, Southeast Asia",
    effects: ["calm clarity", "adaptogenic", "restorative"],
    compounds: ["Desmodin", "Triterpenoids"],
    mechanismOfAction: "Neuroprotective, serotonergic modulation",
    tags: ["Ayurvedic", "tonic", "mild nootropic"]
  },
  {
    name: "Acorus calamus var. angustatus",
    slug: "acorus-calamus-angustatus",
    description: "A rare calamus variant high in beta-asarone, used in Tibetan medicine and ritual incense.",
    region: "Himalayas",
    effects: ["trance", "mental clarity", "light hallucinations"],
    compounds: ["Beta-asarone"],
    mechanismOfAction: "GABAergic + cholinergic",
    tags: ["ritual", "variant", "aromatic stimulant"]
  },
  {
    name: "Convolvulus arvensis",
    slug: "convolvulus-arvensis",
    description: "Bindweed, a relative of morning glory, contains ergoline alkaloids and is under investigation for mild entheogenic potential.",
    region: "Europe, North America",
    effects: ["light euphoria", "subtle visual shifts"],
    compounds: ["Ergoline alkaloids (trace)"],
    mechanismOfAction: "5-HT2A agonist (potential)",
    tags: ["entheogen", "ergoline", "wild plant"]
  },
  {
    name: "Salvia sclarea",
    slug: "salvia-sclarea",
    description: "Clary Sage, used aromatically and medicinally for mild euphoria, hormonal balancing, and clarity.",
    region: "Mediterranean",
    effects: ["clarity", "relief", "uplifting"],
    compounds: ["Linalyl acetate", "Sclareol"],
    mechanismOfAction: "GABA-A modulation, estrogenic activity",
    tags: ["aromatic", "elevating", "folk remedy"]
  }
];
