[build]
  base    = "client"
  command = "npm run build"
  publish = "client/build"

[functions]
  directory    = "client/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "http://thehippiescientist.net/*"
  to   = "https://www.thehippiescientist.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://thehippiescientist.net/*"
  to   = "https://www.thehippiescientist.net/:splat"
  status = 301
  force = true

# Required for SPAs using React, Vue, etc.
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
