import type { Herb } from "../types";

export const newHerbs: Herb[] = [
{
  name: "Heimia salicifolia",
  slug: "heimia-salicifolia",
  description: "Also known as Sinicuichi, this Central American herb is used traditionally to induce auditory distortions and mild euphoria.",
  region: "Central America",
  effects: [
    "auditory distortion",
    "euphoria",
    "dreamlike",
  ],
  compounds: [
    "Cryogenine",
  ],
  mechanismOfAction: "GABAergic modulation",
  tags: [
    "ethnobotanical",
    "dream",
    "mildly psychoactive",
  ],
},
{
  name: "Acorus calamus",
  slug: "acorus-calamus",
  description: "Sweet Flag has a complex pharmacology: stimulant in low doses, sedative in high. Historically used in Ayurvedic and Native American medicine.",
  region: "Eurasia / North America",
  effects: [
    "sedative",
    "stimulant",
    "anxiolytic",
  ],
  compounds: [
    "Beta-Asarone",
  ],
  mechanismOfAction: "GABAergic and cholinergic modulation",
  tags: [
    "calming",
    "traditional",
    "aromatic",
  ],
},
{
  name: "Leonurus sibiricus",
  slug: "leonurus-sibiricus",
  description: "Known as Siberian Motherwort, this herb is a relaxing nervine used in Asian medicine with mild psychoactive and aphrodisiac effects.",
  region: "Siberia, China",
  effects: [
    "relaxation",
    "mood lift",
    "aphrodisiac",
  ],
  compounds: [
    "Leonurine",
  ],
  mechanismOfAction: "Dopaminergic modulation",
  tags: [
    "aphrodisiac",
    "nervine",
    "calming",
  ],
},
{
  name: "Dysphania ambrosioides",
  slug: "dysphania-ambrosioides",
  description: "Also known as Epazote, used in Mesoamerican rituals. Contains CNS-stimulating compounds but is toxic at high doses.",
  region: "Mexico",
  effects: [
    "dreamlike",
    "stimulant",
  ],
  compounds: [
    "Ascaridole",
    "p-Cymene",
  ],
  mechanismOfAction: "CNS excitation at high doses",
  tags: [
    "ritual",
    "visionary",
    "potentially toxic",
  ],
},
{
  name: "Casimiroa edulis",
  slug: "casimiroa-edulis",
  description: "The fruit of the White Sapote tree is used as a sedative in traditional Mexican herbal medicine.",
  region: "Central America",
  effects: [
    "sedative",
    "sleep aid",
  ],
  compounds: [
    "Zapotin",
  ],
  mechanismOfAction: "Possible GABAergic activity",
  tags: [
    "sedative",
    "fruit",
    "folk medicine",
  ],
},
{
  name: "Mitchella repens",
  slug: "mitchella-repens",
  description: "Known as Partridgeberry, used as a uterine tonic and mild relaxing agent in North American herbalism.",
  region: "North America",
  effects: [
    "relaxation",
    "nervine",
  ],
  compounds: [
    "Saponins",
    "Iridoids",
  ],
  mechanismOfAction: "Smooth muscle relaxant",
  tags: [
    "calming",
    "uterine",
    "folk remedy",
  ],
},
{
  name: "Perilla frutescens",
  slug: "perilla-frutescens",
  description: "Used in East Asian cuisine and medicine, this leaf contains mild mood-elevating and cognitive enhancing properties.",
  region: "East Asia",
  effects: [
    "uplifting",
    "calm clarity",
  ],
  compounds: [
    "Perillaldehyde",
    "Rosmarinic Acid",
  ],
  mechanismOfAction: "Cholinergic + antioxidant effects",
  tags: [
    "mild nootropic",
    "culinary",
    "relaxing",
  ],
},
{
  name: "Turnera diffusa var. aphrodisiaca",
  slug: "turnera-diffusa-aphrodisiaca",
  description: "A variant of Damiana known for its aphrodisiac and mood-brightening properties. Traditionally used as a tonic.",
  region: "Mexico",
  effects: [
    "aphrodisiac",
    "mood enhancer",
  ],
  compounds: [
    "Damianin",
    "Flavonoids",
  ],
  mechanismOfAction: "Dopaminergic and GABAergic synergy",
  tags: [
    "aphrodisiac",
    "tonic",
    "euphoric",
  ],
},
{
  name: "Thymus vulgaris",
  slug: "thymus-vulgaris",
  description: "Common thyme is a culinary herb with mild neurostimulant properties, thanks to its essential oils like thymol.",
  region: "Europe",
  effects: [
    "clarity",
    "alertness",
  ],
  compounds: [
    "Thymol",
  ],
  mechanismOfAction: "AChE inhibition, antioxidant",
  tags: [
    "culinary",
    "clarity",
    "aromatic",
  ],
},
{
  name: "Helichrysum odoratissimum",
  slug: "helichrysum-odoratissimum",
  description: "Known as Imphepho in South African ritual use, this herb induces visions and is burned to invoke ancestors.",
  region: "Southern Africa",
  effects: [
    "visionary",
    "trance",
    "spiritual",
  ],
  compounds: [
    "Essential oils",
    "Flavonoids",
  ],
  mechanismOfAction: "Possibly serotonergic/GABAergic",
  tags: [
    "dream herb",
    "ritual",
    "African traditional medicine",
  ],
},
{
  name: "Artemisia vulgaris",
  slug: "artemisia-vulgaris",
  description: "Known as Mugwort, traditionally used in European and Asian cultures for vivid dreaming, menstrual relief, and mild psychedelic effects.",
  region: "Europe, Asia",
  effects: [
    "vivid dreaming",
    "relaxation",
    "mild hallucination",
  ],
  compounds: [
    "Thujone",
    "Camphor",
  ],
  mechanismOfAction: "GABA-A modulation, possible NMDA antagonist",
  tags: [
    "dream",
    "ritual",
    "traditional",
  ],
},
{
  name: "Acorus gramineus",
  slug: "acorus-gramineus",
  description: "Japanese Sweet Flag used in Shinto and Buddhist rituals, mildly stimulating and cognition-enhancing.",
  region: "East Asia",
  effects: [
    "clarity",
    "stimulant",
    "focus",
  ],
  compounds: [
    "Asarone",
  ],
  mechanismOfAction: "Cholinergic and GABAergic modulation",
  tags: [
    "traditional",
    "mild nootropic",
    "aromatic",
  ],
},
{
  name: "Sceletium tortuosum",
  slug: "sceletium-tortuosum",
  description: "Known as Kanna, this South African succulent elevates mood and reduces anxiety. Used as a fermented chew.",
  region: "South Africa",
  effects: [
    "euphoria",
    "anxiolytic",
    "social enhancer",
  ],
  compounds: [
    "Mesembrine",
    "Mesembrenone",
  ],
  mechanismOfAction: "SERT inhibition, PDE4 inhibition",
  tags: [
    "mood",
    "euphoric",
    "entactogen",
  ],
},
{
  name: "Calea ternifolia",
  slug: "calea-ternifolia",
  description: "Mexican Dream Herb used in lucid dreaming rituals by the Chontal people. Bitter but effective in inducing hypnagogic visions.",
  region: "Mexico",
  effects: [
    "lucid dreaming",
    "hypnagogia",
    "mental clarity",
  ],
  compounds: [
    "Germacranolides",
  ],
  mechanismOfAction: "Unknown, possible cholinergic",
  tags: [
    "dream",
    "visionary",
    "ritual",
  ],
},
{
  name: "Silene capensis",
  slug: "silene-capensis",
  description: "African Dream Root, revered by the Xhosa people for enhancing vivid and prophetic dreams.",
  region: "Southern Africa",
  effects: [
    "vivid dreaming",
    "trance",
    "vision",
  ],
  compounds: [
    "Triterpenoid saponins",
  ],
  mechanismOfAction: "Unknown, possibly cholinergic",
  tags: [
    "dream",
    "African traditional",
    "visionary",
  ],
},
{
  name: "Tilia tomentosa",
  slug: "tilia-tomentosa",
  description: "Silver Linden, used as a calming tea in Europe. Shows sedative and anti-anxiety effects.",
  region: "Europe",
  effects: [
    "calming",
    "sleep aid",
    "nervine",
  ],
  compounds: [
    "Quercetin",
    "Volatile oils",
  ],
  mechanismOfAction: "GABAergic, anti-inflammatory",
  tags: [
    "relaxing",
    "tea",
    "folk medicine",
  ],
},
{
  name: "Tagetes lucida",
  slug: "tagetes-lucida",
  description: "Mexican Tarragon, used by the Aztecs and modern shamans as a mild psychedelic and incense.",
  region: "Mexico",
  effects: [
    "euphoria",
    "visionary",
    "clarity",
  ],
  compounds: [
    "Estragole",
    "Anethole",
  ],
  mechanismOfAction: "Serotonergic and cholinergic",
  tags: [
    "ritual",
    "psychoactive incense",
    "traditional",
  ],
},
{
  name: "Justicia pectoralis",
  slug: "justicia-pectoralis",
  description: "Known as tilo or chamb\u00e1, this Amazonian herb is mildly relaxing and sometimes added to snuffs and brews.",
  region: "Amazon basin",
  effects: [
    "relaxing",
    "mild euphoria",
  ],
  compounds: [
    "Coumarin",
    "Umelliferone",
  ],
  mechanismOfAction: "GABAergic and serotonergic",
  tags: [
    "mild sedative",
    "additive",
    "traditional",
  ],
},
{
  name: "Entada rheedii",
  slug: "entada-rheedii",
  description: "African Dream Bean, used to access ancestor spirits in dreams; seeds are large and traditionally worn as talismans.",
  region: "Africa",
  effects: [
    "dream enhancement",
    "spiritual connection",
  ],
  compounds: [
    "Saponins",
  ],
  mechanismOfAction: "Unknown",
  tags: [
    "dream",
    "ethnobotanical",
    "ritual",
  ],
},
{
  name: "Celastrus paniculatus",
  slug: "celastrus-paniculatus",
  description: "Intellect tree from Ayurveda; used to enhance memory and mental clarity, with mild stimulation.",
  region: "India",
  effects: [
    "focus",
    "mental clarity",
    "calm alertness",
  ],
  compounds: [
    "Celastrine",
    "Paniculatin",
  ],
  mechanismOfAction: "Cholinergic",
  tags: [
    "nootropic",
    "Ayurvedic",
    "seed oil",
  ],
},
{
  name: "Acorus americanus",
  slug: "acorus-americanus",
  description: "American Sweet Flag, native to North America, used by indigenous groups for its psychoactive and stimulant properties.",
  region: "North America",
  effects: [
    "alertness",
    "mental clarity",
    "mild euphoria",
  ],
  compounds: [
    "Alpha-asarone",
  ],
  mechanismOfAction: "Cholinergic + dopaminergic modulation",
  tags: [
    "native medicine",
    "calamus species",
    "uplifting",
  ],
},
{
  name: "Virola theiodora",
  slug: "virola-theiodora",
  description: "A South American tree whose resin contains potent tryptamines. Used in snuffs by Amazonian tribes.",
  region: "Amazon Basin",
  effects: [
    "visionary",
    "intense euphoria",
    "dissociation",
  ],
  compounds: [
    "DMT",
    "5-MeO-DMT",
  ],
  mechanismOfAction: "Serotonin receptor agonist (5-HT2A)",
  tags: [
    "snuff",
    "shamanic",
    "tryptamine",
  ],
},
{
  name: "Ruta graveolens",
  slug: "ruta-graveolens",
  description: "Common Rue, used historically as a sedative, an abortifacient, and for spiritual protection.",
  region: "Mediterranean",
  effects: [
    "relaxation",
    "hypnotic",
    "mystical",
  ],
  compounds: [
    "Rutarin",
    "Graveoline",
  ],
  mechanismOfAction: "GABA-A modulation, alkaloid effects",
  tags: [
    "ritual",
    "bitter",
    "traditional medicine",
  ],
},
{
  name: "Arundo donax",
  slug: "arundo-donax",
  description: "Giant Reed contains trace tryptamines and has been proposed as an Ayahuasca analog component.",
  region: "Mediterranean, Asia",
  effects: [
    "light euphoria",
    "dreaminess",
  ],
  compounds: [
    "DMT (trace)",
    "Bufotenine (trace)",
  ],
  mechanismOfAction: "Serotonergic (possible)",
  tags: [
    "analogue",
    "reed grass",
    "entheogenic interest",
  ],
},
{
  name: "Passiflora incarnata",
  slug: "passiflora-incarnata",
  description: "Passionflower is a mild sedative and anxiolytic with MAO-inhibiting flavonoids. Common in herbal teas.",
  region: "North & Central America",
  effects: [
    "calming",
    "dreamy",
    "sedative",
  ],
  compounds: [
    "Chrysin",
    "Harmine (trace)",
  ],
  mechanismOfAction: "GABA-A agonist + mild MAOI",
  tags: [
    "sleep",
    "relaxant",
    "folk medicine",
  ],
},
{
  name: "Sophora secundiflora",
  slug: "sophora-secundiflora",
  description: "Mescal bean, used ceremonially by Native American tribes. Highly toxic, formerly used as an ordeal poison.",
  region: "Southwestern US, Mexico",
  effects: [
    "delirium",
    "visions",
    "dizziness",
  ],
  compounds: [
    "Cytisine",
  ],
  mechanismOfAction: "Nicotinic receptor agonist",
  tags: [
    "ceremonial",
    "toxic",
    "visionary",
  ],
},
{
  name: "Desmodium gangeticum",
  slug: "desmodium-gangeticum",
  description: "An Ayurvedic herb with antistress, adaptogenic, and cognitive benefits. Traditionally used to support vitality.",
  region: "India, Southeast Asia",
  effects: [
    "calm clarity",
    "adaptogenic",
    "restorative",
  ],
  compounds: [
    "Desmodin",
    "Triterpenoids",
  ],
  mechanismOfAction: "Neuroprotective, serotonergic modulation",
  tags: [
    "Ayurvedic",
    "tonic",
    "mild nootropic",
  ],
},
{
  name: "Acorus calamus var. angustatus",
  slug: "acorus-calamus-angustatus",
  description: "A rare calamus variant high in beta-asarone, used in Tibetan medicine and ritual incense.",
  region: "Himalayas",
  effects: [
    "trance",
    "mental clarity",
    "light hallucinations",
  ],
  compounds: [
    "Beta-asarone",
  ],
  mechanismOfAction: "GABAergic + cholinergic",
  tags: [
    "ritual",
    "variant",
    "aromatic stimulant",
  ],
},
{
  name: "Convolvulus arvensis",
  slug: "convolvulus-arvensis",
  description: "Bindweed, a relative of morning glory, contains ergoline alkaloids and is under investigation for mild entheogenic potential.",
  region: "Europe, North America",
  effects: [
    "light euphoria",
    "subtle visual shifts",
  ],
  compounds: [
    "Ergoline alkaloids (trace)",
  ],
  mechanismOfAction: "5-HT2A agonist (potential)",
  tags: [
    "entheogen",
    "ergoline",
    "wild plant",
  ],
},
{
  name: "Salvia sclarea",
  slug: "salvia-sclarea",
  description: "Clary Sage, used aromatically and medicinally for mild euphoria, hormonal balancing, and clarity.",
  region: "Mediterranean",
  effects: [
    "clarity",
    "relief",
    "uplifting",
  ],
  compounds: [
    "Linalyl acetate",
    "Sclareol",
  ],
  mechanismOfAction: "GABA-A modulation, estrogenic activity",
  tags: [
    "aromatic",
    "elevating",
    "folk remedy",
  ],
},
{
  name: "Pimenta dioica",
  slug: "pimenta-dioica",
  description: "Also known as Allspice, this Caribbean plant has mild uplifting and warming effects, sometimes used in ritual incense.",
  region: "Caribbean, Central America",
  effects: [
    "stimulant",
    "aromatic euphoria",
    "warming",
  ],
  compounds: [
    "Eugenol",
    "Quercetin",
  ],
  mechanismOfAction: "GABAergic + serotonergic",
  tags: [
    "aromatic",
    "ritual",
    "mild stimulant",
  ],
},
{
  name: "Lactuca virosa",
  slug: "lactuca-virosa",
  description: "Wild Lettuce, a traditional sedative and pain reliever in folk medicine, sometimes called 'lettuce opium'.",
  region: "Europe",
  effects: [
    "sedative",
    "analgesic",
    "dreamy",
  ],
  compounds: [
    "Lactucopicrin",
    "Lactucin",
  ],
  mechanismOfAction: "Opioid receptor modulation",
  tags: [
    "sedative",
    "folk medicine",
    "dream aid",
  ],
},
{
  name: "Achillea millefolium",
  slug: "achillea-millefolium",
  description: "Yarrow, used for divination and as a calming tea. Some varieties contain mild psychoactive compounds.",
  region: "Europe, North America",
  effects: [
    "mild euphoria",
    "relaxation",
    "ritual clarity",
  ],
  compounds: [
    "Thujone (trace)",
    "Flavonoids",
  ],
  mechanismOfAction: "GABAergic + serotonergic",
  tags: [
    "folk remedy",
    "ritual",
    "divination",
  ],
},
{
  name: "Peumus boldus",
  slug: "peumus-boldus",
  description: "Boldo is a South American medicinal herb with liver-supportive and mild hypnotic properties.",
  region: "Chile",
  effects: [
    "calming",
    "digestive aid",
    "dreamy",
  ],
  compounds: [
    "Boldine",
    "Ascaridole",
  ],
  mechanismOfAction: "Cholinergic + serotonergic",
  tags: [
    "digestive",
    "sleep aid",
    "folk medicine",
  ],
},
{
  name: "Vitex agnus-castus",
  slug: "vitex-agnus-castus",
  description: "Chasteberry is traditionally used for hormonal balancing, mood stabilization, and dream clarity.",
  region: "Mediterranean",
  effects: [
    "mood stabilization",
    "lucidity",
    "balance",
  ],
  compounds: [
    "Agnuside",
    "Flavonoids",
  ],
  mechanismOfAction: "Dopaminergic + hormonal",
  tags: [
    "hormonal",
    "mood",
    "dream",
  ],
},
{
  name: "Myristica fragrans",
  slug: "myristica-fragrans",
  description: "Nutmeg, psychoactive in high doses, has deliriant and sedative properties. Historically used in mystic rituals.",
  region: "Indonesia",
  effects: [
    "dreaminess",
    "euphoria",
    "disorientation",
  ],
  compounds: [
    "Myristicin",
    "Elemicin",
  ],
  mechanismOfAction: "Monoamine oxidase inhibition + anticholinergic",
  tags: [
    "deliriant",
    "visionary",
    "ritual",
  ],
},
{
  name: "Amorpha fruticosa",
  slug: "amorpha-fruticosa",
  description: "False Indigo Bush, native to North America, was historically smoked for relaxation and vision-induction.",
  region: "North America",
  effects: [
    "relaxation",
    "mental softening",
    "trance",
  ],
  compounds: [
    "Amorphigenin",
  ],
  mechanismOfAction: "Likely GABAergic",
  tags: [
    "folk",
    "smokable",
    "visionary",
  ],
},
{
  name: "Eleutherococcus senticosus",
  slug: "eleutherococcus-senticosus",
  description: "Siberian Ginseng is an adaptogen used to enhance endurance, mental resilience, and reduce fatigue.",
  region: "Siberia, China",
  effects: [
    "clarity",
    "resilience",
    "mental energy",
  ],
  compounds: [
    "Eleutherosides",
  ],
  mechanismOfAction: "Adaptogenic + neuroprotective",
  tags: [
    "adaptogen",
    "tonic",
    "nootropic",
  ],
},
{
  name: "Verbena officinalis",
  slug: "verbena-officinalis",
  description: "Vervain is a calming and spiritually symbolic herb used in ritual baths and teas.",
  region: "Europe, North Africa",
  effects: [
    "mild sedation",
    "relaxation",
    "spiritual clarity",
  ],
  compounds: [
    "Verbenalin",
    "Iridoids",
  ],
  mechanismOfAction: "GABAergic + serotonergic",
  tags: [
    "ritual",
    "relaxant",
    "dream",
  ],
},
{
  name: "Melissa officinalis",
  slug: "melissa-officinalis",
  description: "Lemon Balm is a gentle nervine herb that promotes calmness and sleep with subtle mood elevation.",
  region: "Europe, Middle East",
  effects: [
    "calming",
    "mood lifting",
    "sleep aid",
  ],
  compounds: [
    "Citral",
    "Rosmarinic acid",
  ],
  mechanismOfAction: "GABA-T inhibition + serotonergic",
  tags: [
    "calming",
    "folk remedy",
    "tea",
  ],
},
{
  name: "Artemisia abrotanum",
  slug: "artemisia-abrotanum",
  description: "Southernwood is a fragrant herb used traditionally as a stimulant, memory aid, and dream enhancer.",
  region: "Mediterranean, Europe",
  effects: [
    "mental clarity",
    "dream enhancement",
    "stimulant",
  ],
  compounds: [
    "Camphor",
    "Thujone",
  ],
  mechanismOfAction: "GABAergic + cholinergic modulation",
  tags: [
    "aromatic",
    "folk remedy",
    "uplifting",
  ],
},
{
  name: "Heimia salicifolia",
  slug: "heimia-salicifolia",
  description: "Known as Sun Opener, this herb was used by the Aztecs for visionary and divinatory purposes.",
  region: "Mexico, Central America",
  effects: [
    "visionary",
    "relaxation",
    "lucid dream enhancement",
  ],
  compounds: [
    "Cryogenine",
    "Lyfoline",
  ],
  mechanismOfAction: "Serotonergic + anticholinergic",
  tags: [
    "oneirogen",
    "visionary",
    "shamanic",
  ],
},
{
  name: "Bacopa monnieri",
  slug: "bacopa-monnieri",
  description: "Brahmi is an Ayurvedic nootropic herb that improves memory, learning, and mental clarity.",
  region: "India, Southeast Asia",
  effects: [
    "memory enhancement",
    "calm focus",
    "adaptogen",
  ],
  compounds: [
    "Bacosides A and B",
  ],
  mechanismOfAction: "Cholinergic + antioxidant",
  tags: [
    "nootropic",
    "Ayurvedic",
    "mental clarity",
  ],
},
{
  name: "Nymphaea caerulea",
  slug: "nymphaea-caerulea",
  description: "The Blue Lotus of the Nile, used historically for sedative, aphrodisiac, and euphoric effects.",
  region: "Egypt, Africa",
  effects: [
    "euphoria",
    "relaxation",
    "mild sedation",
  ],
  compounds: [
    "Aporphine",
    "Nuciferine",
  ],
  mechanismOfAction: "Dopaminergic + serotonergic",
  tags: [
    "aphrodisiac",
    "sedative",
    "ritual",
  ],
},
{
  name: "Huperzia serrata",
  slug: "huperzia-serrata",
  description: "A moss rich in Huperzine A, used for memory enhancement and neuroprotection.",
  region: "China, Southeast Asia",
  effects: [
    "focus",
    "memory boost",
    "lucid dreaming",
  ],
  compounds: [
    "Huperzine A",
  ],
  mechanismOfAction: "Acetylcholinesterase inhibition",
  tags: [
    "nootropic",
    "lucidity",
    "memory",
  ],
},
{
  name: "Justicia adhatoda",
  slug: "justicia-adhatoda",
  description: "Also called Malabar Nut, this herb has traditional uses as a respiratory aid and mild sedative.",
  region: "India, Sri Lanka",
  effects: [
    "calming",
    "respiratory clearing",
    "mild sedation",
  ],
  compounds: [
    "Vasicine",
    "Vasicinone",
  ],
  mechanismOfAction: "Bronchodilation + GABAergic",
  tags: [
    "sedative",
    "respiratory",
    "Ayurvedic",
  ],
},
{
  name: "Tilia europaea",
  slug: "tilia-europaea",
  description: "Common Linden, used in European herbalism for calming, dream-enhancing, and tension relief.",
  region: "Europe",
  effects: [
    "calming",
    "mild euphoria",
    "dream enhancement",
  ],
  compounds: [
    "Volatile oils",
    "Tiliroside",
  ],
  mechanismOfAction: "GABAergic + serotonergic",
  tags: [
    "folk medicine",
    "calming",
    "dream",
  ],
},
{
  name: "Pogostemon cablin",
  slug: "pogostemon-cablin",
  description: "Patchouli, while mainly aromatic, has mild psychoactive effects in traditional incense rituals.",
  region: "Asia",
  effects: [
    "sensory enhancement",
    "calm focus",
    "uplifted mood",
  ],
  compounds: [
    "Patchoulol",
    "Alpha-bulnesene",
  ],
  mechanismOfAction: "Aromatherapeutic + serotonergic",
  tags: [
    "aromatic",
    "ritual",
    "uplifting",
  ],
},
{
  name: "Anadenanthera colubrina",
  slug: "anadenanthera-colubrina",
  description: "Source of vilca snuff; contains powerful tryptamines used in South American shamanism.",
  region: "South America",
  effects: [
    "visionary",
    "intense dissociation",
    "time distortion",
  ],
  compounds: [
    "Bufotenine",
    "DMT",
  ],
  mechanismOfAction: "5-HT2A agonism",
  tags: [
    "shamanic",
    "tryptamine",
    "snuff",
  ],
},
{
  name: "Aloysia citrodora",
  slug: "aloysia-citrodora",
  description: "Lemon Verbena, a gentle herbal tea with calming and mood-lifting effects.",
  region: "South America",
  effects: [
    "calm",
    "relaxation",
    "light euphoria",
  ],
  compounds: [
    "Citral",
    "Verbascoside",
  ],
  mechanismOfAction: "GABAergic + serotonergic",
  tags: [
    "tea",
    "folk remedy",
    "calming",
  ],
},
{
  name: "Artemisia ludoviciana",
  slug: "artemisia-ludoviciana",
  description: "Also known as white sagebrush, used by Native American tribes for cleansing, dreams, and mild sedation.",
  region: "North America",
  effects: [
    "mild sedation",
    "visionary",
    "cleansing",
  ],
  compounds: [
    "Thujone",
    "Camphor",
  ],
  mechanismOfAction: "GABAergic + anticholinergic",
  tags: [
    "ritual",
    "dream",
    "folk medicine",
  ],
},
{
  name: "Turnera diffusa",
  slug: "turnera-diffusa",
  description: "Damiana is an aphrodisiac and mood enhancer used in Mexican herbal traditions and modern blends.",
  region: "Mexico, Central America",
  effects: [
    "euphoria",
    "stimulation",
    "aphrodisiac",
  ],
  compounds: [
    "Damianin",
    "Flavonoids",
  ],
  mechanismOfAction: "Dopaminergic + GABAergic",
  tags: [
    "aphrodisiac",
    "tea",
    "tonic",
  ],
},
{
  name: "Viola odorata",
  slug: "viola-odorata",
  description: "Sweet Violet, mildly sedative and anxiolytic, traditionally used for grief, tension, and calm dreams.",
  region: "Europe, Asia",
  effects: [
    "relaxation",
    "emotional clarity",
    "sleep aid",
  ],
  compounds: [
    "Violine",
    "Methyl salicylate",
  ],
  mechanismOfAction: "GABAergic + anti-inflammatory",
  tags: [
    "folk remedy",
    "sedative",
    "emotional",
  ],
},
{
  name: "Petasites hybridus",
  slug: "petasites-hybridus",
  description: "Butterbur, once used for headaches and anxiety. Contains pyrrolizidine alkaloids \u2014 caution advised.",
  region: "Europe",
  effects: [
    "anti-anxiety",
    "vasodilation",
    "headache relief",
  ],
  compounds: [
    "Petasin",
    "Isopetasin",
  ],
  mechanismOfAction: "Smooth muscle relaxant + serotonergic",
  tags: [
    "nervine",
    "headache",
    "caution",
  ],
},
{
  name: "Zanthoxylum clava-herculis",
  slug: "zanthoxylum-clava-herculis",
  description: "The Toothache Tree, used for numbing, mild stimulation, and ritual practices in the American South.",
  region: "Southeastern USA",
  effects: [
    "numbing",
    "alertness",
    "tingling",
  ],
  compounds: [
    "Zanthoxylin",
    "Lignans",
  ],
  mechanismOfAction: "Local anesthetic + sensory modulation",
  tags: [
    "ritual",
    "numbing",
    "tingle",
  ],
},
{
  name: "Arundo donax",
  slug: "arundo-donax",
  description: "A tall reed containing trace tryptamines; rarely used, but investigated for its chemical potential.",
  region: "Mediterranean, Asia",
  effects: [
    "visionary (potential)",
    "altered state (speculative)",
  ],
  compounds: [
    "DMT (trace)",
    "Bufotenine (trace)",
  ],
  mechanismOfAction: "5-HT2A agonist (hypothetical)",
  tags: [
    "tryptamine",
    "experimental",
    "rare",
  ],
},
{
  name: "Betula lenta",
  slug: "betula-lenta",
  description: "Sweet Birch, aromatic and uplifting; contains methyl salicylate, offering mild euphoria and clarity.",
  region: "North America",
  effects: [
    "uplifting",
    "mental clarity",
    "aromatic",
  ],
  compounds: [
    "Methyl salicylate",
  ],
  mechanismOfAction: "Anti-inflammatory + mild serotonergic",
  tags: [
    "tea",
    "uplifting",
    "aromatic",
  ],
},
{
  name: "Nepeta cataria",
  slug: "nepeta-cataria",
  description: "Catnip, while famous for feline effects, produces mild sedation and mood elevation in humans.",
  region: "Europe, Asia, North America",
  effects: [
    "mild euphoria",
    "relaxation",
    "calming",
  ],
  compounds: [
    "Nepetalactone",
    "Iridoids",
  ],
  mechanismOfAction: "GABAergic + calming",
  tags: [
    "tea",
    "folk remedy",
    "calming",
  ],
},
{
  name: "Scutellaria lateriflora",
  slug: "scutellaria-lateriflora",
  description: "American Skullcap is a revered nervine herb promoting relaxation, calm, and sleep.",
  region: "North America",
  effects: [
    "sedation",
    "calm",
    "anxiety relief",
  ],
  compounds: [
    "Baicalin",
    "Scutellarin",
  ],
  mechanismOfAction: "GABAergic",
  tags: [
    "nervine",
    "folk remedy",
    "sleep aid",
  ],
},
{
  name: "Tussilago farfara",
  slug: "tussilago-farfara",
  description: "Coltsfoot, used in traditional teas for respiratory support and light sedation.",
  region: "Europe, Asia",
  effects: [
    "soothing",
    "light sedation",
    "respiratory ease",
  ],
  compounds: [
    "Mucilage",
    "Tussilagone",
  ],
  mechanismOfAction: "Smooth muscle relaxation + respiratory support",
  tags: [
    "respiratory",
    "sedative",
    "folk medicine",
  ],
},
];