local Prompts = {
        {
                id = "intro_arrival",
                title = "Welcome to the Run",
                body = "codex.intro.arrival.body",
                icon = "rbxassetid://0",
                category = "Basics",
                priority = 100,
                oncePerProfile = true,
                cooldownSec = 300,
                triggers = { "SESSION_JOIN" },
                gates = {
                        { type = "DayAtLeast", value = 1 },
                },
                actions = {
                        { label = "Open Codex", event = "OPEN_CODEX" },
                },
        },
        {
                id = "intro_build",
                title = "Build Your First Campfire",
                body = "codex.build.campfire.body",
                icon = "rbxassetid://0",
                category = "Basics",
                priority = 90,
                oncePerProfile = true,
                cooldownSec = 120,
                triggers = { "OPEN_BUILD_MENU", "NIGHT_START" },
                gates = {
                        { type = "DayAtLeast", value = 1 },
                        { type = "StructureCountBelow", struct = "campfire", value = 1 },
                },
                actions = {
                        { label = "Open Build", event = "OPEN_BUILD_MENU" },
                        { label = "Pin Objective", event = "PIN_OBJECTIVE", payload = { id = "build_campfire" } },
                },
        },
        {
                id = "intro_bed",
                title = "Claim Rest",
                body = "codex.build.bed.body",
                icon = "rbxassetid://0",
                category = "Basics",
                priority = 70,
                oncePerProfile = false,
                cooldownSec = 150,
                triggers = { "STRUCTURE_PLACED" },
                gates = {
                        { type = "StructureCountBelow", struct = "bed", value = 2 },
                },
                actions = {
                        { label = "Build Bed", event = "PIN_OBJECTIVE", payload = { id = "build_bed" } },
                },
        },
        {
                id = "rescue_milestone",
                title = "Rescue to Accelerate Days",
                body = "codex.rescue.multiplier.body",
                icon = "rbxassetid://0",
                category = "Milestones",
                priority = 80,
                oncePerProfile = false,
                cooldownSec = 180,
                triggers = { "RESCUE_COMPLETE" },
                gates = {
                        { type = "OncePerSession" },
                },
        },
        {
                id = "beacon_fuel",
                title = "Fuel the Beacon",
                body = "codex.beacon.fuel.body",
                icon = "rbxassetid://0",
                category = "Milestones",
                priority = 75,
                oncePerProfile = false,
                cooldownSec = 120,
                triggers = { "BEACON_LOW" },
                gates = {
                        { type = "BeaconFuelBelow", value = 200 },
                },
                actions = {
                        { label = "Refuel", event = "OPEN_INVENTORY" },
                },
        },
        {
                id = "omen_warning",
                title = "Omen Rising",
                body = "codex.omen.warning.body",
                icon = "rbxassetid://0",
                category = "Threats",
                priority = 95,
                oncePerProfile = false,
                cooldownSec = 240,
                triggers = { "OMEN_BEGIN" },
                gates = {
                        { type = "DayAtLeast", value = 5 },
                },
        },
        {
                id = "economy_shop",
                title = "Visit the Camp Merchant",
                body = "codex.economy.shop.body",
                icon = "rbxassetid://0",
                category = "Economy",
                priority = 60,
                oncePerProfile = true,
                cooldownSec = 300,
                triggers = { "CURRENCY_SPEND" },
                gates = {
                        { type = "CurrencyAtLeast", value = 50 },
                },
                actions = {
                        { label = "Open Shop", event = "OPEN_SHOP" },
                },
        },
        {
                id = "trap_usage",
                title = "Set Up Traps",
                body = "codex.build.trap.body",
                icon = "rbxassetid://0",
                category = "Defense",
                priority = 65,
                oncePerProfile = false,
                cooldownSec = 210,
                triggers = { "NIGHT_START" },
                gates = {
                        { type = "StructureCountBelow", struct = "trap", value = 3 },
                        { type = "DayAtLeast", value = 3 },
                },
        },
        {
                id = "accessibility_toggle",
                title = "Accessibility Options",
                body = "codex.settings.accessibility.body",
                icon = "rbxassetid://0",
                category = "Settings",
                priority = 50,
                oncePerProfile = true,
                cooldownSec = 600,
                triggers = { "SESSION_JOIN" },
                gates = {
                        { type = "ProfileHasSetting", category = "accessibility", key = "reduceFlashes", expected = true, invert = true },
                },
                actions = {
                        { label = "Open Settings", event = "OPEN_SETTINGS", payload = { tab = "Accessibility" } },
                },
        },
        {
                id = "watchtower_tip",
                title = "Secure the Perimeter",
                body = "codex.build.watchtower.body",
                icon = "rbxassetid://0",
                category = "Defense",
                priority = 55,
                oncePerProfile = false,
                cooldownSec = 180,
                triggers = { "DAY_ADVANCE" },
                gates = {
                        { type = "DayAtLeast", value = 7 },
                        { type = "StructureCountBelow", struct = "watchtower", value = 1 },
                },
        },
        {
                id = "late_join_coach",
                title = "Catch Up Quickly",
                body = "codex.latejoin.coach.body",
                icon = "rbxassetid://0",
                category = "Basics",
                priority = 85,
                oncePerProfile = false,
                cooldownSec = 300,
                triggers = { "LATE_JOIN" },
                gates = {
                        { type = "DayAtLeast", value = 10 },
                },
        },
}

return Prompts
