import { describe, expect, it } from 'vitest'
import { assessEligibility, scoreDistributionCandidate, selectDistributionOpportunity } from '../opportunity-engine.mjs'
const NOW=new Date('2026-08-27T00:00:00Z')
function governed(overrides={}){return{id:'sleep-human-trial',title:'Sleep intervention evidence',finding:'In the recorded randomized trial, the intervention improved the prespecified sleep outcome versus control.',evidenceType:'randomized human trial',evidenceGrade:'A',limitation:'This was one study and does not establish a universal effect.',sourceUrl:'https://thehippiescientist.net/evidence/sleep-intervention/',lastVerified:'2026-08-20',...overrides}}
describe('distribution opportunity engine',()=>{
it('selects the highest-scoring eligible governed page deterministically',()=>{const a=governed();const b=governed({id:'stress-human-trial',title:'Stress intervention evidence',sourceUrl:'https://thehippiescientist.net/evidence/stress-intervention/'});const signals={'sleep-human-trial':{impact:9,searchOpportunity:9,socialSuitability:8,informationUniqueness:9,existingAssetSaturation:0},'stress-human-trial':{impact:6,searchOpportunity:5,socialSuitability:5,informationUniqueness:5,existingAssetSaturation:4}};const first=selectDistributionOpportunity([b,a],signals,{now:NOW});const second=selectDistributionOpportunity([b,a],signals,{now:NOW});expect(first.status).toBe('selected');expect(first.schemaVersion).toBe('1.2.0');expect(first.selected.id).toBe('sleep-human-trial');expect(first).toEqual(second);expect(first.selected.sourceUrl).toBe(a.sourceUrl);expect(first.selected.successCriteria.measurementWindowDays).toBe(28)})
it('platform fit can change format but cannot break a tied page rank',()=>{const a=governed({id:'a-page',title:'A evidence',sourceUrl:'https://thehippiescientist.net/evidence/a/'});const z=governed({id:'z-page',title:'Z evidence',sourceUrl:'https://thehippiescientist.net/evidence/z/'});const baseline=selectDistributionOpportunity([z,a],{}, {now:NOW});const signals={'z-page':{platformFit:{'short-video':10,carousel:10,infographic:10,pinterest:10,newsletter:10},platformProductionCost:{'short-video':0,carousel:0,infographic:0,pinterest:0,newsletter:0}},'a-page':{platformFit:{'short-video':0,carousel:0,infographic:0,pinterest:0,newsletter:0},platformProductionCost:{'short-video':10,carousel:10,infographic:10,pinterest:10,newsletter:10}}};const fitted=selectDistributionOpportunity([z,a],signals,{now:NOW});expect(fitted.candidates.find(c=>c.id==='z-page').score).toBe(fitted.candidates.find(c=>c.id==='a-page').score);expect(fitted.candidates.find(c=>c.id==='z-page').platformScore).toBeGreaterThan(fitted.candidates.find(c=>c.id==='a-page').platformScore);expect(baseline.selected.id).toBe('a-page');expect(fitted.selected.id).toBe('a-page')})
it('uses platform-specific fit and cost to choose the best format without changing page rank',()=>{const object=governed();const baseline=scoreDistributionCandidate(object,{}, {now:NOW});const fitted=scoreDistributionCandidate(object,{'sleep-human-trial':{platformFit:{'short-video':10,carousel:1,infographic:1,pinterest:1,newsletter:1},platformProductionCost:{'short-video':1,carousel:8,infographic:8,pinterest:8,newsletter:8}}},{now:NOW});expect(baseline.platform).toBe('carousel');expect(fitted.platform).toBe('short-video');expect(fitted.score).toBe(baseline.score);expect(fitted.platformDecision).toMatchObject({fit:10,productionCost:1,evidence:{platformFitObserved:true,productionCostObserved:true}});expect(fitted.destination.canonicalUrl).toBe(object.sourceUrl)})
it('marks fallback platform-fit evidence explicitly when platform-specific signals are absent',()=>{const candidate=scoreDistributionCandidate(governed(),{}, {now:NOW});expect(candidate.platformDecision.evidence).toEqual({platformFitObserved:false,productionCostObserved:false});expect(candidate.platformDecision.fit).toBe(5);expect(candidate.platformDecision.productionCost).toBe(candidate.metrics.productionCost)})
it('emits deterministic canonical attribution and lossless discoverability metadata',()=>{const object=governed();const candidate=scoreDistributionCandidate(object,{}, {now:NOW});expect(candidate.destination.canonicalUrl).toBe(object.sourceUrl);expect(candidate.discoverability.description).toContain(object.finding);expect(candidate.discoverability.description).toContain(object.limitation);expect(candidate.discoverability.canonicalSource).toBe(object.sourceUrl)})
it('blocks an exact page/platform/angle cohort already present in distribution inventory',()=>{const object=governed();const baseline=scoreDistributionCandidate(object,{}, {now:NOW});const cohort=baseline.destination.attribution.cohort;const candidate=scoreDistributionCandidate(object,{'sleep-human-trial':{existingAngleCohorts:[cohort]}},{now:NOW});expect(candidate.eligible).toBe(true);expect(candidate.selectable).toBe(false);expect(candidate.duplicateAngle).toBe(true)})
it('uses the swarm scoring formula and subtracts growth risks rather than overriding safety',()=>{const candidate=scoreDistributionCandidate(governed(),{'sleep-human-trial':{impact:8,urgency:7,breadth:9,confidence:9,compoundingLeverage:9,opportunityAge:3,reversibility:10,technicalDebtInterest:7,effort:3,regressionRisk:2,blastRadius:2,existingAssetSaturation:4,cannibalizationRisk:3}},{now:NOW});expect(candidate.score).toBe(93);expect(candidate.eligible).toBe(true)})
it('platform fit cannot make a scientifically ineligible candidate distributable',()=>{const object=governed({id:'preclinical-platform-max',evidenceType:'mouse preclinical study',sourceUrl:'https://thehippiescientist.net/evidence/preclinical-platform-max/'});const result=selectDistributionOpportunity([object],{'preclinical-platform-max':{platformFit:{'short-video':10,carousel:10,infographic:10,pinterest:10,newsletter:10},platformProductionCost:{'short-video':0,carousel:0,infographic:0,pinterest:0,newsletter:0}}},{now:NOW});expect(result.status).toBe('waiting-for-governed-object');expect(result.selected).toBeNull()})
it('fails closed on stale or non-first-party evidence pages',()=>{expect(assessEligibility(governed({lastVerified:'2024-01-01'}),{now:NOW}).eligible).toBe(false);expect(assessEligibility(governed({sourceUrl:'https://example.com/evidence'}),{now:NOW}).eligible).toBe(false)})
it('returns an explicit waiting state when the governed research-object set is empty',()=>{expect(selectDistributionOpportunity([],{}, {now:NOW})).toEqual({schemaVersion:'1.2.0',status:'waiting-for-governed-object',selected:null,candidates:[]})})
})
