/**
 * Top 25 Expansion — structured spec source data.
 *
 * This is the machine-readable companion to `docs/top25-expansion-roadmap.md`.
 * `scripts/content/generate-page-specs.mjs` consumes it to emit one spec file
 * per page under `docs/page-specs/`.
 *
 * SCOPE: planning/infrastructure only. Editing this file changes the *spec*
 * for a page; it never touches page content. Re-run the generator after edits.
 *
 * Field reference:
 *   num            roadmap rank (#1–#25)
 *   phase          1 | 2 | 3 (90-day phasing)
 *   route          live route path (already exists)
 *   template       which reusable template applies (see docs/templates/)
 *   currentScore   / targetScore   weighted content score
 *   currentWords   / targetWords   body word count
 *   currentState   measured signals today (FAQ / schema / citations / links / affiliate)
 *   sections       missing body sections to add
 *   internalLinks  internal links to add (funnel toward money pages)
 *   affiliate      affiliate placement opportunities (always AFFILIATE_TAGS.amazon)
 *   faq            FAQ question opportunities
 *   schema         schema.org opportunities
 *   citations      citation opportunities (claims that need sourcing)
 *   evidence       evidence-grading opportunities (per-item tiers)
 *   ymyl           optional YMYL caution note
 */

/** @typedef {'commercial'|'guide'|'comparison'|'herb'|'compound'} TemplateKind */

export const TEMPLATE_FILES = {
  commercial: 'templates/commercial-page-template.md',
  guide: 'templates/guide-template.md',
  comparison: 'templates/comparison-page-template.md',
  herb: 'templates/herb-authority-template.md',
  compound: 'templates/compound-authority-template.md',
}

export const pages = [
  // ───────────────────────── Phase 1 — Money pages ─────────────────────────
  {
    num: 1,
    phase: 1,
    route: '/best-supplements-for-sleep',
    template: 'commercial',
    currentScore: 89,
    targetScore: 95,
    currentWords: 580,
    targetWords: 2400,
    currentState:
      'Rendered via `SeoEntryPage` (`app/seo-entry-pages.tsx`). Thin (~580w), strong commercial intent. Schema/FAQ/citations not yet built to target.',
    sections: [
      '"How we ranked these" methodology box',
      'Per-supplement breakdown: melatonin, magnesium glycinate, glycine, L-theanine, valerian, apigenin',
      'Dosing & timing table',
      'Safety / interaction notes',
      '"Who should avoid" section',
      "Buyer's checklist (form, dose, third-party testing)",
    ],
    internalLinks: [
      '/articles/best-herbs-for-sleep/',
      '/articles/magnesium-types-for-sleep/',
      '/compare/sleep-herbs-vs-melatonin',
      '/guides/magnesium-vs-melatonin',
      '/herbs/valerian',
      '/compounds/melatonin',
      '/compounds/l-theanine',
      '/articles/sleep-stack-guide',
    ],
    affiliate: ['magnesium glycinate', 'melatonin', 'L-theanine', 'glycine', 'valerian'],
    faq: [
      'What is the best supplement for sleep?',
      'Is magnesium or melatonin better?',
      'Are sleep supplements safe long-term?',
      'What dose of melatonin?',
      'Can I stack them?',
      'Do they cause grogginess?',
    ],
    schema: ['ItemList (ranked products)', 'FAQPage', 'BreadcrumbList'],
    citations: [
      'Melatonin dose/efficacy for sleep onset',
      'Magnesium glycinate and sleep quality',
      'Glycine pre-sleep evidence',
      'L-theanine relaxation evidence',
      'Valerian meta-analysis',
    ],
    evidence: [
      'Tier each ranked supplement (high / moderate / low) via EvidenceMeter / EvidenceSummaryBox',
    ],
  },
  {
    num: 2,
    phase: 1,
    route: '/articles/best-supplements-for-adhd/',
    template: 'commercial',
    currentScore: 89,
    targetScore: 95,
    currentWords: 1557,
    targetWords: 2500,
    currentState:
      'Component-driven (`FocusAdhdArticlePage` / `lib/focus-adhd-articles.ts`, ~1,557w across the focus set). Monetized via `AdhdMonetizationWidgets`.',
    sections: [
      'Evidence tiers per nutrient: omega-3, zinc, iron/ferritin, magnesium, L-theanine, saffron, bacopa',
      '"Deficiency-driven vs. adjunct" framing',
      'Kids vs. adults section',
      '"What the trials actually show"',
      'Stack-building section',
      'When to see a clinician',
    ],
    internalLinks: [
      '/articles/omega-3-and-adhd/',
      '/articles/zinc-and-adhd/',
      '/articles/iron-ferritin-and-adhd/',
      '/articles/magnesium-for-adhd/',
      '/articles/l-theanine-for-adhd/',
      '/articles/best-magnesium-supplement-for-adhd',
      '/articles/adhd-stack-guide/',
      '/guides/adhd-supplements',
    ],
    affiliate: ['omega-3', 'zinc', 'magnesium glycinate', 'iron', 'saffron'],
    faq: [
      'What supplements help ADHD?',
      'Do supplements replace medication?',
      'Best for adults vs children?',
      'How long until they work?',
      'Are they safe with stimulants?',
      'Which has the strongest evidence?',
    ],
    schema: ['Article', 'FAQPage', 'ItemList (ranked nutrients)'],
    citations: [
      'Omega-3 (EPA/DHA) ADHD RCT / meta-analysis',
      'Zinc supplementation in ADHD',
      'Iron/ferritin and ADHD symptom severity',
      'Magnesium and ADHD',
      'Saffron vs methylphenidate trial',
    ],
    evidence: ['Per-nutrient evidence tier with deficiency-context caveat'],
    ymyl: 'Do not frame supplements as replacements for prescribed ADHD medication; route to /disclaimer.',
  },
  {
    num: 3,
    phase: 1,
    route: '/best-supplements-for-stress',
    template: 'commercial',
    currentScore: 86,
    targetScore: 93,
    currentWords: 580,
    targetWords: 2200,
    currentState: 'Rendered via `SeoEntryPage`. Thin (~580w), high commercial intent.',
    sections: [
      'Adaptogen breakdown: ashwagandha, rhodiola, holy basil',
      'Cortisol mechanism primer',
      'Magnesium + L-theanine for acute stress',
      'Dosing table',
      'Safety section',
      '"Acute vs chronic stress" selection guide',
    ],
    internalLinks: [
      '/guides/best-adaptogens-for-stress/',
      '/guides/how-to-lower-cortisol-naturally',
      '/herbs/ashwagandha',
      '/herbs/rhodiola',
      '/compounds/l-theanine',
      '/articles/natural-anxiety-relief',
      '/compare/rhodiola-vs-ashwagandha',
      '/guides/best-supplements-for-overthinking',
    ],
    affiliate: ['ashwagandha (KSM-66)', 'rhodiola', 'magnesium', 'L-theanine'],
    faq: [
      'Best supplement for stress?',
      'Does ashwagandha lower cortisol?',
      'Ashwagandha vs rhodiola?',
      'How fast do adaptogens work?',
      'Safe daily?',
    ],
    schema: ['ItemList', 'FAQPage', 'BreadcrumbList'],
    citations: [
      'Ashwagandha cortisol reduction RCT',
      'Rhodiola fatigue/stress trials',
      'L-theanine acute stress',
      'Magnesium and perceived stress',
    ],
    evidence: ['Tier each adaptogen; note standardization (KSM-66, 3% rosavin)'],
  },
  {
    num: 4,
    phase: 1,
    route: '/best-supplements-for-focus',
    template: 'commercial',
    currentScore: 85,
    targetScore: 92,
    currentWords: 580,
    targetWords: 2200,
    currentState: 'Rendered via `SeoEntryPage`. Thin (~580w).',
    sections: [
      "Nootropic breakdown: L-theanine+caffeine, citicoline, alpha-GPC, bacopa, rhodiola, lion's mane",
      '"Stimulant vs calm-focus" framing',
      'Dosing/timing table',
      'Tolerance / cycling',
      'Safety section',
    ],
    internalLinks: [
      '/guides/best-nootropics-for-focus/',
      '/articles/l-theanine-vs-caffeine-for-focus',
      '/articles/citicoline-vs-alpha-gpc/',
      '/herbs/lions-mane',
      '/compounds/l-theanine',
      '/guides/focus-without-caffeine-crash/',
      '/compare/caffeine-vs-l-theanine-vs-bacopa-for-focus',
      '/articles/best-supplements-for-adhd/',
    ],
    affiliate: ['L-theanine', 'citicoline', 'alpha-GPC', "lion's mane", 'bacopa'],
    faq: [
      'Best supplement for focus?',
      'Nootropics that actually work?',
      'L-theanine + caffeine dose?',
      'Focus without jitters?',
      'Citicoline vs alpha-GPC?',
    ],
    schema: ['ItemList', 'FAQPage'],
    citations: [
      'L-theanine + caffeine attention studies',
      'Citicoline cognition trials',
      'Bacopa memory meta-analysis',
    ],
    evidence: ['Tier each nootropic; separate stimulant vs calm-focus mechanisms'],
  },
  {
    num: 5,
    phase: 1,
    route: '/articles/best-magnesium-supplement-for-adhd',
    template: 'commercial',
    currentScore: 87,
    targetScore: 94,
    currentWords: 1852,
    targetWords: 2600,
    currentState:
      'Strong base: 1,852w, 10 FAQ, 4 schema blocks, 22 affiliate markers. Needs form-comparison depth + ItemList.',
    sections: [
      'Form-by-form bioavailability table: glycinate, L-threonate, citrate, malate, oxide',
      '"Magnesium + ADHD evidence"',
      'Dosing by age/weight',
      'GI tolerance notes',
      'Timing guidance',
      '"Signs of deficiency"',
    ],
    internalLinks: [
      '/articles/magnesium-glycinate-vs-citrate-for-adhd',
      '/articles/magnesium-for-adhd/',
      '/compare/magnesium-glycinate-vs-l-threonate-for-sleep',
      '/compounds/magnesium',
      '/articles/l-theanine-magnesium-adhd-stack',
      '/articles/best-supplements-for-adhd/',
    ],
    affiliate: ['glycinate', 'L-threonate', 'citrate', 'malate'],
    faq: [
      'Magnesium L-threonate vs glycinate for ADHD? (add)',
      'Can kids take magnesium for ADHD? (add)',
      '(existing 10 FAQ retained)',
    ],
    schema: ['Add ItemList over form comparison', 'keep Article', 'keep FAQPage'],
    citations: [
      'Magnesium status in ADHD children',
      'L-threonate brain bioavailability',
      'Form-by-form absorption data',
    ],
    evidence: ['Bioavailability ranking per form; deficiency-context caveat'],
  },
  {
    num: 6,
    phase: 1,
    route: '/best-magnesium-supplements-for-adhd',
    template: 'commercial',
    currentScore: 84,
    targetScore: 92,
    currentWords: 580,
    targetWords: 2000,
    currentState:
      'Thin body (~580w) but 28 affiliate markers and 0 FAQ / 0 schema / 0 citations. Over-linked; needs consolidation + structure.',
    sections: [
      '"How to choose" section',
      'Bioavailability table',
      'Dose guidance',
      'Third-party testing checklist',
      '"Deficiency & ADHD" evidence summary',
      'Safety / GI notes',
    ],
    internalLinks: [
      '/articles/best-magnesium-supplement-for-adhd',
      '/articles/magnesium-glycinate-vs-citrate-for-adhd',
      '/articles/magnesium-for-adhd/',
      '/compounds/magnesium',
      '/articles/best-supplements-for-adhd/',
      '/guides/adhd-supplements',
    ],
    affiliate: ['Consolidate 28 markers → 3–4 vetted product cards (glycinate, L-threonate, citrate)'],
    faq: [
      'Best magnesium for ADHD?',
      'What form?',
      'Dose?',
      'Glycinate vs threonate?',
      'Safe with meds?',
      'How long to work?',
    ],
    schema: ['ItemList', 'FAQPage', 'BreadcrumbList (currently none)'],
    citations: [
      'Magnesium and ADHD symptom data',
      'Bioavailability by form',
      'Third-party testing rationale',
    ],
    evidence: ['Evidence summary for deficiency vs adjunct use'],
    ymyl: 'Near-duplicate intent with #5 — differentiate as product-roundup vs form-guide and cross-link; do NOT merge or redirect.',
  },
  {
    num: 7,
    phase: 1,
    route: '/guides/best-supplements-for-sleep',
    template: 'guide',
    currentScore: 84,
    targetScore: 92,
    currentWords: 1104,
    targetWords: 2200,
    currentState: '1,104w, 5 links, 0 FAQ / 0 schema / 0 citations.',
    sections: [
      'Ranked picks with rationale',
      'Dosing table',
      '"Stacking safely"',
      '"Natural vs melatonin"',
      'Circadian / timing guidance',
      'Safety & interactions',
    ],
    internalLinks: [
      '/best-supplements-for-sleep',
      '/articles/best-herbs-for-sleep/',
      '/compare/sleep-herbs-vs-melatonin',
      '/guides/magnesium-vs-melatonin',
      '/articles/magnesium-types-for-sleep/',
      '/herbs/valerian',
      '/compounds/melatonin',
    ],
    affiliate: ['magnesium', 'melatonin', 'L-theanine', 'valerian'],
    faq: [
      'Best sleep supplement?',
      'Natural vs melatonin?',
      'Safe nightly?',
      'Best dose?',
      'Stack or single?',
    ],
    schema: ['FAQPage', 'ItemList (currently none)'],
    citations: ['Per-aid efficacy sources', 'Melatonin timing/circadian evidence'],
    evidence: ['Evidence grade per ranked pick'],
  },
  {
    num: 8,
    phase: 1,
    route: '/best-supplements-for-gut-health',
    template: 'commercial',
    currentScore: 84,
    targetScore: 92,
    currentWords: 580,
    targetWords: 2200,
    currentState: 'Rendered via `SeoEntryPage`. Thin (~580w).',
    sections: [
      'Category breakdown: probiotics, prebiotics/fiber, L-glutamine, digestive enzymes, ginger, peppermint, zinc carnosine',
      '"By symptom" selector (bloating, IBS, regularity)',
      'Dosing section',
      'Safety section',
      '"What the evidence supports"',
    ],
    internalLinks: [
      '/compounds/l-glutamine',
      '/compounds/zinc',
      '/herbs/ginger',
      '/herbs/peppermint',
      '/best-supplements-for-blood-pressure',
      '/guides',
    ],
    affiliate: ['probiotic', 'psyllium/prebiotic fiber', 'L-glutamine', 'digestive enzymes', 'ginger'],
    faq: [
      'Best supplement for gut health?',
      'Probiotics vs prebiotics?',
      'Best for bloating?',
      'Do digestive enzymes help?',
      'How long to work?',
      'Safe daily?',
    ],
    schema: ['ItemList', 'FAQPage', 'BreadcrumbList'],
    citations: [
      'Probiotic strain-specific evidence',
      'Prebiotic fiber and microbiome',
      'Peppermint oil IBS trials',
    ],
    evidence: ['Tier each category; strain/form specificity caveats'],
  },
  {
    num: 9,
    phase: 1,
    route: '/best-supplements-for-fat-loss',
    template: 'commercial',
    currentScore: 84,
    targetScore: 92,
    currentWords: 580,
    targetWords: 2200,
    currentState: 'Rendered via `SeoEntryPage`. Thin (~580w). High-scrutiny YMYL topic.',
    sections: [
      'Evidence-graded breakdown: caffeine, green tea/EGCG, protein, fiber, berberine, L-carnitine',
      '"What works vs. hype"',
      'Realistic-expectations / safety section',
      '"Diet & training come first" disclaimer',
      'Dosing table',
    ],
    internalLinks: [
      '/compare/berberine-vs-metformin',
      '/compounds/berberine',
      '/compounds/caffeine',
      '/best-supplements-for-blood-pressure',
      '/best-supplements-for-gut-health',
      '/guides',
    ],
    affiliate: ['green tea extract', 'protein powder', 'fiber', 'berberine'],
    faq: [
      'Best supplement for fat loss?',
      'Does berberine help weight?',
      'Do fat burners work?',
      'Caffeine for fat loss?',
      'Safe?',
      'Realistic results?',
    ],
    schema: ['ItemList', 'FAQPage'],
    citations: [
      'Caffeine thermogenesis data',
      'EGCG/green tea fat oxidation',
      'Berberine metabolic trials',
      'Protein satiety/body composition',
    ],
    evidence: ['Strict evidence grading with prominent hype caveat'],
    ymyl: 'YMYL: keep claims conservative and evidence-linked; route disclaimer to /disclaimer.',
  },

  // ──────────────── Phase 2 — High-intent guide stubs ────────────────
  {
    num: 10,
    phase: 2,
    route: '/guides/how-to-lower-cortisol-naturally',
    template: 'guide',
    currentScore: 81,
    targetScore: 90,
    currentWords: 132,
    targetWords: 1900,
    currentState: 'Near-empty stub (132w).',
    sections: [
      'Cortisol 101',
      'Lifestyle levers (sleep, light, exercise, breathwork)',
      'Adaptogen evidence (ashwagandha, rhodiola, holy basil)',
      'Magnesium / L-theanine',
      '"Morning vs night cortisol"',
      'When high cortisol needs a doctor',
    ],
    internalLinks: [
      '/herbs/ashwagandha',
      '/herbs/rhodiola',
      '/best-supplements-for-stress',
      '/guides/best-adaptogens-for-stress/',
      '/education/how-stress-affects-the-brain',
      '/articles/natural-anxiety-relief',
      '/compounds/l-theanine',
    ],
    affiliate: ['ashwagandha', 'rhodiola', 'magnesium'],
    faq: [
      'How do I lower cortisol fast?',
      'Does ashwagandha lower cortisol?',
      'Foods that lower cortisol?',
      'Best time to take adaptogens?',
      'Signs of high cortisol?',
    ],
    schema: ['FAQPage', 'HowTo (lifestyle protocol)'],
    citations: ['Ashwagandha cortisol RCT', 'Exercise/sleep and cortisol rhythm'],
    evidence: ['Tier lifestyle vs supplement levers'],
  },
  {
    num: 11,
    phase: 2,
    route: '/guides/natural-alternatives-to-anxiety-medication',
    template: 'guide',
    currentScore: 80,
    targetScore: 90,
    currentWords: 120,
    targetWords: 1900,
    currentState: 'Near-empty stub (120w). Sensitive YMYL topic.',
    sections: [
      'Evidence-tiered options (ashwagandha, L-theanine, kava, passionflower, lemon balm, magnesium)',
      '"How they compare to SSRIs/benzos" (mechanism only, not medical advice)',
      'Safety & interactions (serotonergic risk)',
      '"Talk to your prescriber" guidance',
    ],
    internalLinks: [
      '/guides/best-herbs-for-anxiety/',
      '/articles/natural-anxiety-relief',
      '/herbs/kava',
      '/herbs/passionflower',
      '/compounds/l-theanine',
      '/psychoactive/serotonergic-stacking-risks',
      '/articles/cbd-vs-ashwagandha-for-anxiety',
    ],
    affiliate: ['L-theanine', 'ashwagandha', 'magnesium'],
    faq: [
      'Natural alternatives to anxiety meds?',
      'Strongest natural anxiolytic?',
      'Can I stop my meds?',
      'Kava safe?',
      'L-theanine vs medication?',
      'Interactions?',
    ],
    schema: ['FAQPage'],
    citations: ['Kava anxiety meta-analysis', 'L-theanine anxiety', 'Serotonergic interaction sources'],
    evidence: ['Tier each option; serotonergic-risk safety notes'],
    ymyl: 'Must NOT advise discontinuing prescribed medication; frame as complementary and prescriber-supervised. Route to /disclaimer.',
  },
  {
    num: 12,
    phase: 2,
    route: '/guides/best-supplements-for-overthinking',
    template: 'guide',
    currentScore: 78,
    targetScore: 88,
    currentWords: 145,
    targetWords: 1700,
    currentState: 'Near-empty stub (145w).',
    sections: [
      '"Overthinking vs anxiety"',
      'Calming stack (L-theanine, magnesium glycinate, ashwagandha, lemon balm, saffron)',
      'Evening rumination protocol',
      'Dosing section',
      'Safety section',
    ],
    internalLinks: [
      '/best-supplements-for-stress',
      '/guides/best-herbs-for-anxiety/',
      '/compounds/l-theanine',
      '/herbs/ashwagandha',
      '/articles/l-theanine-for-anxiety',
      '/guides/how-to-lower-cortisol-naturally',
    ],
    affiliate: ['L-theanine', 'magnesium glycinate', 'ashwagandha'],
    faq: [
      'Supplements to stop overthinking?',
      'Does L-theanine quiet the mind?',
      'Best for racing thoughts at night?',
      'Magnesium for rumination?',
      'How fast?',
    ],
    schema: ['FAQPage'],
    citations: ['L-theanine and rumination/anxiety', 'Magnesium and stress reactivity'],
    evidence: ['Tier calming-stack ingredients'],
  },
  {
    num: 13,
    phase: 2,
    route: '/guides/supplements-for-brain-fog-and-fatigue',
    template: 'guide',
    currentScore: 78,
    targetScore: 88,
    currentWords: 136,
    targetWords: 1800,
    currentState: 'Near-empty stub (136w).',
    sections: [
      'Common causes (sleep, B12/iron/vit-D deficiency, thyroid, dehydration)',
      "Evidence-based options (B-complex, iron, vit-D, rhodiola, lion's mane, citicoline)",
      '"Energy vs focus"',
      'When fog signals something medical',
    ],
    internalLinks: [
      '/herbs/rhodiola',
      '/herbs/lions-mane',
      '/guides/best-nootropics-for-focus/',
      '/best-supplements-for-focus',
      '/articles/vitamin-d-and-adhd',
      '/articles/iron-ferritin-and-adhd/',
      '/compounds/citicoline',
    ],
    affiliate: ['B-complex', 'vitamin D', 'rhodiola', "lion's mane"],
    faq: [
      'Best supplement for brain fog?',
      'What causes brain fog?',
      'Does rhodiola help fatigue?',
      'B12 for energy?',
      'How long to clear?',
    ],
    schema: ['FAQPage'],
    citations: ['B12/iron/vit-D deficiency fatigue', 'Rhodiola fatigue trials'],
    evidence: ['Distinguish deficiency-correction vs adjunct'],
  },
  {
    num: 14,
    phase: 2,
    route: '/guides/best-natural-sleep-aids-that-work/',
    template: 'guide',
    currentScore: 79,
    targetScore: 89,
    currentWords: 89,
    targetWords: 1800,
    currentState: 'Near-empty stub (89w).',
    sections: [
      'Ranked aids (magnesium glycinate, valerian, melatonin, glycine, L-theanine, passionflower, lemon balm)',
      'Evidence grade per aid',
      'Dosing/timing',
      '"What to try first"',
      'Safety / dependency notes',
    ],
    internalLinks: [
      '/best-supplements-for-sleep',
      '/guides/best-supplements-for-sleep',
      '/articles/best-herbs-for-sleep/',
      '/compare/sleep-herbs-vs-melatonin',
      '/herbs/valerian',
      '/herbs/passionflower',
      '/compounds/melatonin',
    ],
    affiliate: ['magnesium', 'valerian', 'melatonin', 'L-theanine'],
    faq: [
      'Natural sleep aids that work?',
      'Strongest natural sleep aid?',
      'Valerian vs melatonin?',
      'Safe nightly?',
      'Fastest-acting?',
    ],
    schema: ['ItemList', 'FAQPage'],
    citations: ['Per-aid efficacy meta-analyses'],
    evidence: ['Evidence grade per ranked aid'],
  },
  {
    num: 15,
    phase: 2,
    route: '/guides/best-herbs-for-anxiety/',
    template: 'guide',
    currentScore: 82,
    targetScore: 91,
    currentWords: 998,
    targetWords: 2000,
    currentState: '998w, 5 links, 0 FAQ / 0 schema / 0 citations.',
    sections: [
      'Per-herb evidence cards (ashwagandha, kava, passionflower, lemon balm, chamomile, lavender/silexan)',
      '"Fast-acting vs daily"',
      'Dosing table',
      'Serotonergic-interaction safety',
      '"Which to try first"',
    ],
    internalLinks: [
      '/herbs/kava',
      '/herbs/passionflower',
      '/herbs/ashwagandha',
      '/articles/natural-anxiety-relief',
      '/articles/l-theanine-for-anxiety',
      '/guides/natural-alternatives-to-anxiety-medication',
      '/psychoactive/serotonergic-stacking-risks',
    ],
    affiliate: ['ashwagandha', 'kava', 'passionflower', 'lemon balm'],
    faq: [
      'Best herb for anxiety?',
      'Fastest-acting?',
      'Kava safe?',
      'Ashwagandha for anxiety dose?',
      'Daily vs as-needed?',
      'Interactions with SSRIs?',
    ],
    schema: ['FAQPage', 'citations (currently none)'],
    citations: ['Kava meta-analysis', 'Lavender/silexan trials', 'Passionflower anxiety'],
    evidence: ['Per-herb evidence tier; fast-acting vs daily'],
  },
  {
    num: 16,
    phase: 2,
    route: '/guides/adhd-supplements',
    template: 'guide',
    currentScore: 83,
    targetScore: 91,
    currentWords: 795,
    targetWords: 2000,
    currentState: '795w, 12 FAQ markers + 10 schema markers (strong base, thin body).',
    sections: [
      'Evidence-graded nutrient cards (omega-3, zinc, iron, magnesium, L-theanine, saffron, bacopa)',
      '"Adjunct vs deficiency"',
      'Kids vs adults',
      'Stack examples',
      '"What not to expect"',
    ],
    internalLinks: [
      '/articles/best-supplements-for-adhd/',
      '/articles/omega-3-and-adhd/',
      '/articles/zinc-and-adhd/',
      '/articles/iron-ferritin-and-adhd/',
      '/articles/best-magnesium-supplement-for-adhd',
      '/articles/adhd-stack-guide/',
      '/best-magnesium-supplements-for-adhd',
    ],
    affiliate: ['omega-3', 'zinc', 'magnesium', 'saffron'],
    faq: ['Expand existing set with evidence depth (keep FAQPage)'],
    schema: ['Add ItemList to existing schema'],
    citations: ['Omega-3 ADHD', 'Zinc/iron ADHD', 'Saffron trial'],
    evidence: ['Per-nutrient evidence grade with deficiency caveat'],
    ymyl: 'Frame as adjunct, not medication replacement; route to /disclaimer.',
  },
  {
    num: 17,
    phase: 2,
    route: '/guides/best-nootropics-for-focus/',
    template: 'guide',
    currentScore: 82,
    targetScore: 90,
    currentWords: 985,
    targetWords: 2000,
    currentState: '985w, 5 links, 0 FAQ / 0 schema / 0 citations.',
    sections: [
      "Per-nootropic cards (L-theanine+caffeine, citicoline, alpha-GPC, bacopa, rhodiola, lion's mane, tyrosine)",
      '"Stimulant vs calm-focus"',
      'Stacking',
      'Tolerance / cycling',
      'Safety',
    ],
    internalLinks: [
      '/best-supplements-for-focus',
      '/articles/citicoline-vs-alpha-gpc/',
      '/articles/l-theanine-vs-caffeine-for-focus',
      '/compare/caffeine-vs-l-theanine-vs-bacopa-for-focus',
      '/herbs/lions-mane',
      '/herbs/rhodiola',
      '/guides/focus-without-caffeine-crash/',
    ],
    affiliate: ['L-theanine', 'citicoline', "lion's mane", 'bacopa'],
    faq: [
      'Best nootropic for focus?',
      'Natural vs synthetic?',
      'Strongest legal nootropic?',
      'L-theanine + caffeine?',
      'Do they build tolerance?',
      'Safe long-term?',
    ],
    schema: ['FAQPage', 'citations'],
    citations: ['L-theanine+caffeine', 'Citicoline', 'Bacopa', 'Alpha-GPC'],
    evidence: ['Per-nootropic evidence tier'],
  },
  {
    num: 18,
    phase: 2,
    route: '/guides/best-adaptogens-for-stress/',
    template: 'guide',
    currentScore: 80,
    targetScore: 89,
    currentWords: 935,
    targetWords: 2000,
    currentState: '935w, 5 links, 0 FAQ / 0 schema / 0 citations.',
    sections: [
      'Per-adaptogen cards (ashwagandha, rhodiola, holy basil, eleuthero, cordyceps, schisandra)',
      'Mechanism primer',
      '"Stimulating vs calming adaptogens"',
      'Dosing / cycling',
      'Safety / interactions',
    ],
    internalLinks: [
      '/herbs/ashwagandha',
      '/herbs/rhodiola',
      '/best-supplements-for-stress',
      '/compare/rhodiola-vs-ashwagandha',
      '/guides/how-to-lower-cortisol-naturally',
      '/guides/rhodiola-complete-guide/',
      '/articles/natural-anxiety-relief',
    ],
    affiliate: ['ashwagandha', 'rhodiola', 'holy basil', 'cordyceps'],
    faq: [
      'Best adaptogen for stress?',
      'Ashwagandha vs rhodiola?',
      'Do adaptogens really work?',
      'Cycle them?',
      'Stimulating vs calming?',
      'Safe daily?',
    ],
    schema: ['FAQPage', 'citations'],
    citations: ['Ashwagandha RCT', 'Rhodiola trials', 'Holy basil stress'],
    evidence: ['Per-adaptogen tier; stimulating vs calming classification'],
  },

  // ──────────── Phase 3 — Hubs, comparisons & authority ────────────
  {
    num: 19,
    phase: 3,
    route: '/herbs/ashwagandha',
    template: 'herb',
    currentScore: 81,
    targetScore: 90,
    currentWords: 200,
    targetWords: 1800,
    currentState: '~200w structured data + template scaffolding; thin body.',
    sections: [
      'Expanded mechanism (cortisol/GABAergic)',
      'Benefit-by-goal (stress, sleep, testosterone, anxiety)',
      'KSM-66 vs Sensoril',
      'Dosing / timing',
      'Side effects & contraindications (thyroid, pregnancy)',
      '"How to choose a product"',
    ],
    internalLinks: [
      '/best-supplements-for-stress',
      '/guides/best-adaptogens-for-stress/',
      '/compare/rhodiola-vs-ashwagandha',
      '/articles/ashwagandha-for-anxiety',
      '/articles/ashwagandha-for-sleep',
      '/articles/ashwagandha-for-adhd',
      '/compounds/withanolides',
      '/guides/how-to-lower-cortisol-naturally',
    ],
    affiliate: ['KSM-66', 'Sensoril', 'gummies'],
    faq: [
      'What does ashwagandha do?',
      'KSM-66 vs Sensoril?',
      'Best time to take?',
      'Side effects?',
      'How long to work?',
      'Safe with thyroid meds?',
    ],
    schema: ['Ensure FAQPage renders on template', 'BreadcrumbList'],
    citations: ['Cortisol RCT', 'Sleep trial', 'Anxiety trial', 'Testosterone study'],
    evidence: ['Benefit-by-goal evidence tiers'],
  },
  {
    num: 20,
    phase: 3,
    route: '/herbs/rhodiola',
    template: 'herb',
    currentScore: 79,
    targetScore: 88,
    currentWords: 170,
    targetWords: 1700,
    currentState: '~170w + template; thin body.',
    sections: [
      'Rosavin/salidroside standardization',
      'Fatigue/endurance/mood benefits',
      'Extract vs powder',
      'Dosing/timing (morning)',
      'Stimulating profile & caveats',
      'Contraindications',
    ],
    internalLinks: [
      '/guides/rhodiola-complete-guide/',
      '/guides/rhodiola-extract-vs-powder',
      '/guides/rhodiola-energy',
      '/compare/rhodiola-vs-ashwagandha',
      '/best-supplements-for-focus',
      '/best-supplements-for-stress',
      '/guides/supplements-for-brain-fog-and-fatigue',
      '/herbs/ashwagandha',
    ],
    affiliate: ['standardized 3% rosavin extract'],
    faq: [
      'What is rhodiola good for?',
      'Extract vs powder?',
      'Best dose?',
      'Morning or night?',
      'Rhodiola vs ashwagandha?',
    ],
    schema: ['FAQPage', 'BreadcrumbList'],
    citations: ['Fatigue RCT', 'Standardization data'],
    evidence: ['Benefit tiers; standardization quality'],
  },
  {
    num: 21,
    phase: 3,
    route: '/herbs/turmeric',
    template: 'herb',
    currentScore: 80,
    targetScore: 89,
    currentWords: 183,
    targetWords: 1700,
    currentState: '~183w + template; thin body.',
    sections: [
      'Curcumin bioavailability (piperine/phytosome/liposomal)',
      'Joint & inflammation evidence',
      'Dosing',
      '"With or without black pepper"',
      'Safety (blood thinners, gallbladder)',
      'Product-selection guide',
    ],
    internalLinks: [
      '/guides/turmeric-curcumin',
      '/best-supplements-for-joint-support',
      '/compare/curcumin-vs-boswellia-vs-omega-3',
      '/compounds/curcumin',
      '/education/inflammation',
      '/education/what-is-neuroinflammation',
      '/best-supplements-for-gut-health',
    ],
    affiliate: ['curcumin phytosome (Meriva)', 'curcumin + piperine'],
    faq: [
      'What is turmeric good for?',
      'Best curcumin form?',
      'Dose for inflammation?',
      'Need black pepper?',
      'Side effects?',
    ],
    schema: ['FAQPage', 'BreadcrumbList'],
    citations: ['Curcumin bioavailability', 'OA/joint trials', 'Piperine absorption'],
    evidence: ['Bioavailability-by-form ranking; joint evidence tier'],
    ymyl: 'Note blood-thinner / gallbladder contraindications.',
  },
  {
    num: 22,
    phase: 3,
    route: '/herbs/lions-mane',
    template: 'herb',
    currentScore: 80,
    targetScore: 89,
    currentWords: 177,
    targetWords: 1700,
    currentState: '~177w + template; thin body.',
    sections: [
      'Hericenones/erinacines & NGF mechanism',
      'Cognition/focus/mood evidence',
      'Fruiting body vs mycelium',
      'Dosing',
      'Safety',
      'Product-selection (beta-glucan %)',
    ],
    internalLinks: [
      '/best-supplements-for-focus',
      '/guides/best-nootropics-for-focus/',
      '/guides/supplements-for-brain-fog-and-fatigue',
      '/compounds/hericenones',
      '/education/how-learning-affects-neuroplasticity',
      '/articles/best-supplements-for-adhd/',
      '/herbs/rhodiola',
    ],
    affiliate: ['fruiting-body extract', 'dual-extract capsules'],
    faq: [
      "What does lion's mane do?",
      'Fruiting body vs mycelium?',
      'Best dose?',
      'How long to feel effects?',
      'Side effects?',
    ],
    schema: ['FAQPage', 'BreadcrumbList'],
    citations: ['NGF mechanism', 'Cognition trial', 'Mood trial'],
    evidence: ['Cognition evidence tier; fruiting-body vs mycelium quality'],
  },
  {
    num: 23,
    phase: 3,
    route: '/compare/rhodiola-vs-ashwagandha',
    template: 'comparison',
    currentScore: 80,
    targetScore: 89,
    currentWords: 679,
    targetWords: 2000,
    currentState: '679w, 3 schema markers, 1 FAQ, 0 citations.',
    sections: [
      'Head-to-head comparison table (mechanism, best-for, timing, side effects)',
      '"Stimulating vs calming"',
      '"Can you stack them"',
      'Dosing for each',
      'Decision tree',
    ],
    internalLinks: [
      '/herbs/rhodiola',
      '/herbs/ashwagandha',
      '/guides/best-adaptogens-for-stress/',
      '/best-supplements-for-stress',
      '/best-supplements-for-focus',
      '/guides/rhodiola-complete-guide/',
    ],
    affiliate: ['rhodiola (energy/focus)', 'ashwagandha (stress/sleep)'],
    faq: [
      'Rhodiola or ashwagandha?',
      'Can I take both?',
      'Which for anxiety?',
      'Which for energy?',
      'Which for sleep?',
    ],
    schema: ['Add citations', 'expand FAQPage', 'keep comparison schema'],
    citations: ['Rhodiola fatigue RCT', 'Ashwagandha cortisol RCT', 'Head-to-head/mechanism sources'],
    evidence: ['Side-by-side evidence tier per use-case'],
  },
  {
    num: 24,
    phase: 3,
    route: '/guides/magnesium-vs-melatonin',
    template: 'comparison',
    currentScore: 79,
    targetScore: 88,
    currentWords: 457,
    targetWords: 1800,
    currentState: '457w, 3 links, 0 FAQ / 0 schema / 0 citations.',
    sections: [
      'Mechanism comparison (GABA/NMDA vs circadian)',
      '"Which for which sleep problem"',
      'Can-you-combine section',
      'Dosing/timing',
      'Safety/dependency',
      'Decision guide',
    ],
    internalLinks: [
      '/compare/sleep-herbs-vs-melatonin',
      '/best-supplements-for-sleep',
      '/guides/best-supplements-for-sleep',
      '/articles/magnesium-types-for-sleep/',
      '/compounds/melatonin',
      '/compounds/magnesium',
    ],
    affiliate: ['magnesium glycinate', 'low-dose melatonin', 'combo product'],
    faq: [
      'Magnesium or melatonin for sleep?',
      'Can I take both?',
      'Which is safer?',
      'Best dose of each?',
      'Which for staying asleep?',
    ],
    schema: ['FAQPage', 'comparison schema'],
    citations: ['Melatonin circadian evidence', 'Magnesium sleep quality'],
    evidence: ['Mechanism-based fit per sleep problem'],
  },
  {
    num: 25,
    phase: 3,
    route: '/best-supplements-for-blood-pressure',
    template: 'commercial',
    currentScore: 83,
    targetScore: 91,
    currentWords: 580,
    targetWords: 2100,
    currentState: 'Rendered via `SeoEntryPage`. Thin (~580w). Highest medical-scrutiny page in set.',
    sections: [
      'Evidence-graded options (magnesium, potassium, CoQ10, omega-3, garlic, hibiscus, beetroot/nitrate)',
      '"Lifestyle first"',
      '"Talk to your doctor / med interactions"',
      'Dosing',
      'Monitoring guidance',
    ],
    internalLinks: [
      '/compounds/magnesium',
      '/compounds/coenzyme-q10',
      '/best-supplements-for-fat-loss',
      '/best-supplements-for-gut-health',
      '/herbs/garlic',
      '/herbs/hibiscus',
    ],
    affiliate: ['CoQ10', 'magnesium', 'omega-3', 'garlic/beetroot'],
    faq: [
      'Best supplement for blood pressure?',
      'Does magnesium lower BP?',
      'CoQ10 for BP?',
      'Garlic for blood pressure?',
      'Safe with BP meds?',
      'How fast?',
    ],
    schema: ['ItemList', 'FAQPage'],
    citations: [
      'Magnesium and BP meta-analysis',
      'CoQ10 hypertension',
      'Garlic BP trials',
      'Beetroot/nitrate BP',
      'Hibiscus BP',
    ],
    evidence: ['Strict evidence grading; explicit med-interaction caveats'],
    ymyl: 'Highest YMYL scrutiny: conservative, citation-backed claims; explicit "supplements are not a substitute for prescribed treatment" + /disclaimer.',
  },
]

/** Convert a route to a flat spec filename slug (unique across the set). */
export function routeToSlug(route) {
  return route.replace(/^\//, '').replace(/\//g, '-')
}
