import type { LocalizedProfileTranslation, LocalizedProfileUiCopy } from './localized-profile'

export type ExpandedProfileLocale = 'ar' | 'ru' | 'vi' | 'th' | 'sv'

export const EXPANDED_PROFILE_UI: Record<ExpandedProfileLocale, LocalizedProfileUiCopy> = {
  ar: { evidenceEyebrow: 'ملف بحثي مترجم', evidenceHeading: 'ماذا تُظهر الأدلة', evidenceIntro: 'تتوافق الادعاءات التالية واحداً لواحد مع الادعاءات المعتمدة في الملف العلمي الأصلي. تبقى المراجع العلمية بلغتها الأصلية.', safetyHeading: 'السلامة والاحتياطات', dosageHeading: 'الجرعة المدروسة والسياق', sourcesHeading: 'المصادر', sourcesIntro: 'المصادر المرتبطة بالادعاءات المعتمدة في هذا الملف.', evidenceLevelLabel: 'مستوى الدليل', confidenceLabel: 'الثقة التحريرية', sourceLabel: 'المصدر', originalLabel: 'الملف الأصلي بالإنجليزية', backToLibraryLabel: 'العودة إلى الأعشاب', educationalDisclaimer: 'محتوى تعليمي فقط. لا يحل محل التقييم الطبي الفردي أو المشورة المهنية.' },
  ru: { evidenceEyebrow: 'Переведённый исследовательский профиль', evidenceHeading: 'Что показывают доказательства', evidenceIntro: 'Каждое утверждение ниже соответствует одобренному утверждению исходного научного профиля. Источники сохраняются на языке оригинала.', safetyHeading: 'Безопасность и меры предосторожности', dosageHeading: 'Изученная дозировка и контекст', sourcesHeading: 'Источники', sourcesIntro: 'Источники, связанные с одобренными утверждениями этого профиля.', evidenceLevelLabel: 'Уровень доказательности', confidenceLabel: 'Редакционная уверенность', sourceLabel: 'Источник', originalLabel: 'Оригинальный профиль на английском', backToLibraryLabel: 'Назад к травам', educationalDisclaimer: 'Образовательный материал. Он не заменяет индивидуальную медицинскую оценку или профессиональную консультацию.' },
  vi: { evidenceEyebrow: 'Hồ sơ nghiên cứu đã dịch', evidenceHeading: 'Bằng chứng cho thấy gì', evidenceIntro: 'Mỗi nhận định dưới đây tương ứng với một nhận định đã được phê duyệt trong hồ sơ khoa học gốc. Tài liệu tham khảo được giữ nguyên ngôn ngữ.', safetyHeading: 'An toàn và thận trọng', dosageHeading: 'Liều đã được nghiên cứu và bối cảnh', sourcesHeading: 'Nguồn', sourcesIntro: 'Các nguồn được liên kết với những nhận định đã được phê duyệt của hồ sơ này.', evidenceLevelLabel: 'Mức độ bằng chứng', confidenceLabel: 'Độ tin cậy biên tập', sourceLabel: 'Nguồn', originalLabel: 'Hồ sơ gốc bằng tiếng Anh', backToLibraryLabel: 'Quay lại thư viện thảo dược', educationalDisclaimer: 'Nội dung chỉ nhằm mục đích giáo dục. Không thay thế đánh giá y tế cá nhân hoặc tư vấn chuyên môn.' },
  th: { evidenceEyebrow: 'โปรไฟล์งานวิจัยฉบับแปล', evidenceHeading: 'หลักฐานแสดงอะไร', evidenceIntro: 'ข้อกล่าวอ้างแต่ละข้อด้านล่างตรงกับข้อกล่าวอ้างที่ได้รับการอนุมัติในโปรไฟล์วิทยาศาสตร์ต้นฉบับ แหล่งอ้างอิงคงไว้ในภาษาต้นฉบับ', safetyHeading: 'ความปลอดภัยและข้อควรระวัง', dosageHeading: 'ขนาดที่ศึกษาและบริบท', sourcesHeading: 'แหล่งข้อมูล', sourcesIntro: 'แหล่งข้อมูลที่เชื่อมโยงกับข้อกล่าวอ้างที่ได้รับการอนุมัติของโปรไฟล์นี้', evidenceLevelLabel: 'ระดับหลักฐาน', confidenceLabel: 'ความเชื่อมั่นด้านบรรณาธิการ', sourceLabel: 'แหล่งข้อมูล', originalLabel: 'โปรไฟล์ต้นฉบับภาษาอังกฤษ', backToLibraryLabel: 'กลับไปยังคลังสมุนไพร', educationalDisclaimer: 'เนื้อหานี้มีไว้เพื่อการศึกษาเท่านั้น ไม่แทนที่การประเมินทางการแพทย์ส่วนบุคคลหรือคำแนะนำจากผู้เชี่ยวชาญ' },
  sv: { evidenceEyebrow: 'Översatt forskningsprofil', evidenceHeading: 'Vad evidensen visar', evidenceIntro: 'Varje påstående nedan motsvarar ett godkänt påstående i den ursprungliga vetenskapliga profilen. Källorna behålls på originalspråket.', safetyHeading: 'Säkerhet och försiktighet', dosageHeading: 'Studerad dos och sammanhang', sourcesHeading: 'Källor', sourcesIntro: 'Källor som är kopplade till profilens godkända påståenden.', evidenceLevelLabel: 'Evidensnivå', confidenceLabel: 'Redaktionell säkerhet', sourceLabel: 'Källa', originalLabel: 'Ursprunglig profil på engelska', backToLibraryLabel: 'Tillbaka till örter', educationalDisclaimer: 'Utbildningsinnehåll. Ersätter inte individuell medicinsk bedömning eller professionell rådgivning.' },
}

const CLAIMS = {
  ar: {
    clm_554b74f570d4: 'لا تزال قاعدة الأدلة السريرية محدودة بسبب صغر التجارب وتنوع المستخلصات وأنظمة الجرعات واختلاف مقاييس النتائج ومخاوف خطر التحيز؛ لذلك لا ينبغي تعميم نتائج مستحضر واحد على جميع منتجات الأشواغاندا.',
    clm_62d80de74d95: 'تُظهر التجارب العشوائية قصيرة المدى تحملاً جيداً عموماً، لكن قد تحدث أعراض هضمية خفيفة ونعاس، ولا تثبت الأدلة المتاحة سلامة الاستخدام طويل المدى عبر المنتجات أو الفئات السكانية المختلفة.',
    clm_78af0b376bf1: 'تشير المراجعات المنهجية للتجارب العشوائية إلى أن بعض مستخلصات الأشواغاندا قد تقلل التوتر المدرك وأعراض القلق لدى البالغين، لكن يجب تفسير الأدلة بحذر بسبب اختلاف التركيبات والجرعات والمشاركين ومقاييس النتائج.',
    clm_9318758bf577: 'يُنصح بتجنب الأشواغاندا أثناء الحمل ما لم يوجّه بها مختص مؤهل تحديداً، والحذر مع أمراض أو أدوية الغدة الدرقية والمهدئات وأدوية ضغط الدم والسكري ومثبطات المناعة لأن بيانات السلامة والتداخلات لدى البشر محدودة.',
    clm_d6711d6cd0c9: 'ارتبطت حالات نادرة وسلاسل حالات من إصابة الكبد المهمة سريرياً بمنتجات الأشواغاندا، وغالباً بأنماط ركودية صفراوية أو مختلطة؛ أوقف الاستخدام واطلب تقييماً طبياً عند ظهور اليرقان أو البول الداكن أو الحكة الشديدة أو أعراض مستمرة أعلى البطن.',
    clm_ead0ae0bd2e4: 'وجدت مراجعة منهجية وتحليل تلوي تحسناً إجمالياً متواضعاً في نتائج النوم مع مستخلص الأشواغاندا، مع إشارة أقوى لدى البالغين المصابين بالأرق، رغم محدودية عدد التجارب وعدم إمكانية تقييم تحيز النشر بشكل موثوق.'
  },
  ru: {
    clm_554b74f570d4: 'Клиническая доказательная база остаётся ограниченной из-за небольших исследований, неоднородных экстрактов и схем дозирования, разных показателей исходов и опасений по поводу риска систематической ошибки; результаты одного препарата нельзя переносить на все продукты ашваганды.',
    clm_62d80de74d95: 'Краткосрочные рандомизированные исследования обычно сообщают о хорошей переносимости, но возможны лёгкие желудочно-кишечные симптомы и сонливость; имеющиеся данные не устанавливают долгосрочную безопасность для разных продуктов и групп населения.',
    clm_78af0b376bf1: 'Систематические обзоры рандомизированных исследований предполагают, что некоторые экстракты ашваганды могут снижать воспринимаемый стресс и симптомы тревоги у взрослых, однако доказательства следует трактовать осторожно из-за различий в составах, дозах, популяциях и исходах.',
    clm_9318758bf577: 'Следует избегать ашваганды во время беременности, если только её специально не рекомендовал квалифицированный специалист; особая осторожность нужна при заболеваниях или приёме препаратов для щитовидной железы, седативных средств, антигипертензивных, противодиабетических и иммунодепрессивных препаратов.',
    clm_d6711d6cd0c9: 'Редкие случаи и серии случаев клинически значимого поражения печени связывали с продуктами ашваганды, часто с холестатическим или смешанным типом; прекратите приём и обратитесь за медицинской оценкой при желтухе, тёмной моче, выраженном зуде или стойких болях в верхней части живота.',
    clm_ead0ae0bd2e4: 'Систематический обзор и метаанализ выявил умеренное общее улучшение показателей сна при использовании экстракта ашваганды, более заметное у взрослых с бессонницей, хотя число исследований было ограниченным, а публикационное смещение нельзя было надёжно оценить.'
  },
  vi: {
    clm_554b74f570d4: 'Cơ sở bằng chứng lâm sàng vẫn bị hạn chế bởi các thử nghiệm nhỏ, chiết xuất và phác đồ liều không đồng nhất, thước đo kết quả khác nhau và lo ngại về nguy cơ sai lệch; vì vậy không nên khái quát kết quả của một chế phẩm cho mọi sản phẩm ashwagandha.',
    clm_62d80de74d95: 'Các thử nghiệm ngẫu nhiên ngắn hạn thường cho thấy khả năng dung nạp tốt, nhưng có thể xảy ra triệu chứng tiêu hóa nhẹ và buồn ngủ; bằng chứng hiện có chưa xác lập độ an toàn dài hạn giữa các sản phẩm hoặc quần thể khác nhau.',
    clm_78af0b376bf1: 'Các tổng quan hệ thống về thử nghiệm ngẫu nhiên cho thấy một số chiết xuất ashwagandha có thể làm giảm căng thẳng cảm nhận và triệu chứng lo âu ở người lớn, nhưng cần thận trọng vì công thức, liều, quần thể nghiên cứu và tiêu chí đánh giá khác nhau.',
    clm_9318758bf577: 'Nên tránh ashwagandha khi mang thai trừ khi được chuyên gia có trình độ chỉ định cụ thể; cần đặc biệt thận trọng với bệnh hoặc thuốc tuyến giáp, thuốc an thần, thuốc hạ huyết áp, thuốc tiểu đường và thuốc ức chế miễn dịch vì dữ liệu an toàn và tương tác ở người còn hạn chế.',
    clm_d6711d6cd0c9: 'Các trường hợp hiếm và chuỗi ca tổn thương gan có ý nghĩa lâm sàng đã được liên hệ với sản phẩm ashwagandha, thường theo kiểu ứ mật hoặc hỗn hợp; ngừng sử dụng và đi đánh giá y tế nếu xuất hiện vàng da, nước tiểu sẫm màu, ngứa nhiều hoặc triệu chứng vùng bụng trên kéo dài.',
    clm_ead0ae0bd2e4: 'Một tổng quan hệ thống và phân tích gộp ghi nhận cải thiện tổng thể khiêm tốn về kết quả giấc ngủ với chiết xuất ashwagandha, rõ hơn ở người lớn bị mất ngủ, dù số thử nghiệm còn hạn chế và không thể đánh giá đáng tin cậy sai lệch công bố.'
  },
  th: {
    clm_554b74f570d4: 'ฐานหลักฐานทางคลินิกยังมีข้อจำกัดจากการศึกษาขนาดเล็ก สารสกัดและขนาดยาที่แตกต่างกัน ตัวชี้วัดผลลัพธ์ที่หลากหลาย และความกังวลเรื่องความเสี่ยงของอคติ ดังนั้นไม่ควรนำผลจากผลิตภัณฑ์หนึ่งไปใช้กับผลิตภัณฑ์อัชวากันธาทั้งหมด',
    clm_62d80de74d95: 'การทดลองแบบสุ่มระยะสั้นมักรายงานว่าสามารถทนได้ดี แต่บางคนอาจมีอาการทางเดินอาหารเล็กน้อยหรือมีอาการง่วง และหลักฐานที่มีอยู่ยังไม่ยืนยันความปลอดภัยระยะยาวของผลิตภัณฑ์หรือประชากรทุกกลุ่ม',
    clm_78af0b376bf1: 'การทบทวนอย่างเป็นระบบของการทดลองแบบสุ่มชี้ว่าสารสกัดอัชวากันธาบางชนิดอาจลดความเครียดที่รับรู้และอาการวิตกกังวลในผู้ใหญ่ แต่ควรตีความอย่างระมัดระวังเนื่องจากสูตร ขนาดยา กลุ่มตัวอย่าง และตัวชี้วัดผลแตกต่างกัน',
    clm_9318758bf577: 'ควรหลีกเลี่ยงอัชวากันธาระหว่างตั้งครรภ์ เว้นแต่ผู้เชี่ยวชาญที่มีคุณสมบัติจะแนะนำโดยเฉพาะ และควรระมัดระวังเป็นพิเศษเมื่อมีโรคหรือใช้ยาที่เกี่ยวกับไทรอยด์ ยากล่อมประสาท ยาลดความดัน ยารักษาเบาหวาน หรือยากดภูมิคุ้มกัน เพราะข้อมูลความปลอดภัยและปฏิกิริยาระหว่างยามีจำกัด',
    clm_d6711d6cd0c9: 'มีรายงานกรณีที่พบไม่บ่อยและชุดกรณีของการบาดเจ็บของตับที่มีนัยสำคัญทางคลินิกซึ่งเกี่ยวข้องกับผลิตภัณฑ์อัชวากันธา มักมีรูปแบบคั่งน้ำดีหรือแบบผสม ควรหยุดใช้และขอรับการประเมินทางการแพทย์หากมีตัวเหลือง ปัสสาวะสีเข้ม คันมาก หรืออาการบริเวณท้องส่วนบนต่อเนื่อง',
    clm_ead0ae0bd2e4: 'การทบทวนอย่างเป็นระบบและการวิเคราะห์อภิมานพบว่าผลลัพธ์ด้านการนอนหลับโดยรวมดีขึ้นเล็กน้อยจากสารสกัดอัชวากันธา โดยมีสัญญาณชัดกว่าในผู้ใหญ่ที่มีภาวะนอนไม่หลับ แม้จำนวนการทดลองจะจำกัดและไม่สามารถประเมินอคติจากการตีพิมพ์ได้อย่างน่าเชื่อถือ'
  },
  sv: {
    clm_554b74f570d4: 'Den kliniska evidensbasen är fortfarande begränsad av små studier, heterogena extrakt och doseringsscheman, varierande utfallsmått och oro för bias. Resultat från ett preparat bör därför inte generaliseras till alla ashwagandhaprodukter.',
    clm_62d80de74d95: 'Kortvariga randomiserade studier rapporterar oftast god tolerabilitet, men milda mag-tarmsymtom och dåsighet kan förekomma. Tillgängliga data fastställer inte långtidssäkerhet för olika produkter eller populationer.',
    clm_78af0b376bf1: 'Systematiska översikter av randomiserade studier tyder på att vissa ashwagandhaextrakt kan minska upplevd stress och ångestsymtom hos vuxna, men evidensen bör tolkas försiktigt eftersom formuleringar, doser, populationer och utfall varierar.',
    clm_9318758bf577: 'Undvik ashwagandha under graviditet om det inte uttryckligen rekommenderats av kvalificerad vårdpersonal. Var särskilt försiktig vid sköldkörtelsjukdom eller sköldkörtelmedicinering samt med lugnande, blodtrycks-, diabetes- och immundämpande läkemedel eftersom säkerhets- och interaktionsdata hos människor är begränsade.',
    clm_d6711d6cd0c9: 'Sällsynta fall och fallserier av kliniskt betydande leverskada har kopplats till ashwagandhaprodukter, ofta med kolestatiska eller blandade mönster. Sluta använda produkten och sök medicinsk bedömning vid gulsot, mörk urin, kraftig klåda eller ihållande besvär i övre delen av buken.',
    clm_ead0ae0bd2e4: 'En systematisk översikt och metaanalys fann en måttlig övergripande förbättring av sömnutfall med ashwagandhaextrakt, med starkare signal hos vuxna med insomnia, även om antalet studier var begränsat och publikationsbias inte kunde bedömas tillförlitligt.'
  },
}

const PROFILE_BASE = {
  dosage: {
    ar: 'لا تدعم التجارب جرعة عالمية لجميع المنتجات؛ تختلف التركيبات والتركيزات، ويجب تفسير الجرعة وفق المستخلص المحدد الذي دُرس وسياق السلامة.',
    ru: 'Исследования не подтверждают универсальную дозировку для всех продуктов. Формы и концентрации различаются, поэтому дозу следует интерпретировать в контексте конкретного изученного экстракта и его безопасности.',
    vi: 'Các thử nghiệm không xác lập một liều dùng chung cho mọi sản phẩm. Công thức và nồng độ khác nhau; liều nên được diễn giải theo chiết xuất cụ thể đã được nghiên cứu và bối cảnh an toàn.',
    th: 'การทดลองยังไม่สนับสนุนขนาดยาสากลสำหรับผลิตภัณฑ์ทุกชนิด สูตรและความเข้มข้นแตกต่างกัน จึงควรตีความขนาดยาตามสารสกัดที่ศึกษาและบริบทด้านความปลอดภัย',
    sv: 'Studierna motiverar inte en universell dos för alla produkter. Formuleringar och koncentrationer varierar och dosen bör tolkas utifrån det specifika extrakt som studerats och säkerhetskontexten.',
  },
  safety: {
    ar: 'تُظهر التجارب قصيرة المدى تحملاً جيداً غالباً، لكن قد تحدث أعراض هضمية خفيفة ونعاس. توجد أيضاً إشارات نادرة إلى تحفيز الغدة الدرقية وإصابة الكبد، لذلك يهم السياق الفردي.',
    ru: 'Краткосрочные исследования обычно показывают хорошую переносимость, но возможны лёгкие желудочно-кишечные симптомы и сонливость. Также существуют редкие сигналы стимуляции щитовидной железы и поражения печени.',
    vi: 'Các thử nghiệm ngắn hạn thường cho thấy khả năng dung nạp tốt, nhưng có thể xảy ra triệu chứng tiêu hóa nhẹ và buồn ngủ. Cũng có tín hiệu hiếm gặp về kích thích tuyến giáp và tổn thương gan.',
    th: 'การทดลองระยะสั้นมักพบว่าสามารถทนได้ดี แต่อาจมีอาการทางเดินอาหารเล็กน้อยและง่วงนอน นอกจากนี้ยังมีสัญญาณที่พบไม่บ่อยเกี่ยวกับการกระตุ้นไทรอยด์และการบาดเจ็บของตับ',
    sv: 'Kortvariga studier visar oftast god tolerabilitet, men milda mag-tarmsymtom och dåsighet kan förekomma. Det finns också sällsynta signaler om sköldkörtelstimulering och leverskada.',
  },
  contraindications: {
    ar: ['يُتجنب أثناء الحمل ما لم توجد إرشادات سريرية محددة.', 'الحذر مع أمراض أو أدوية الغدة الدرقية والمهدئات وأدوية ضغط الدم والسكري ومثبطات المناعة.', 'أوقف الاستخدام واطلب تقييماً طبياً عند اليرقان أو البول الداكن أو الحكة الشديدة أو الأعراض البطنية المستمرة.'],
    ru: ['Избегать во время беременности, если нет специального клинического указания.', 'Особая осторожность при заболеваниях или препаратах щитовидной железы, с седативными, гипотензивными, противодиабетическими и иммунодепрессивными средствами.', 'Прекратите приём и обратитесь за медицинской оценкой при желтухе, тёмной моче, сильном зуде или стойких симптомах в верхней части живота.'],
    vi: ['Tránh sử dụng khi mang thai trừ khi có chỉ định lâm sàng cụ thể.', 'Thận trọng khi có bệnh hoặc dùng thuốc tuyến giáp, thuốc an thần, thuốc hạ huyết áp, thuốc tiểu đường hoặc thuốc ức chế miễn dịch.', 'Ngừng sử dụng và đi đánh giá y tế nếu có vàng da, nước tiểu sẫm màu, ngứa nhiều hoặc triệu chứng bụng trên kéo dài.'],
    th: ['หลีกเลี่ยงระหว่างตั้งครรภ์ เว้นแต่มีคำแนะนำทางคลินิกเฉพาะ', 'ใช้ความระมัดระวังเมื่อมีโรคหรือใช้ยาเกี่ยวกับไทรอยด์ ยากล่อมประสาท ยาลดความดัน ยารักษาเบาหวาน หรือยากดภูมิ', 'หยุดใช้และขอรับการประเมินทางการแพทย์หากมีตัวเหลือง ปัสสาวะสีเข้ม คันมาก หรือมีอาการท้องส่วนบนต่อเนื่อง'],
    sv: ['Undvik under graviditet om det inte finns en specifik klinisk rekommendation.', 'Var särskilt försiktig vid sköldkörtelsjukdom eller sköldkörtelmedicinering samt med lugnande, blodtrycks-, diabetes- och immundämpande läkemedel.', 'Sluta använda och sök medicinsk bedömning vid gulsot, mörk urin, kraftig klåda eller ihållande besvär i övre delen av buken.'],
  },
}

export const EXPANDED_ASHWAGANDHA: Record<ExpandedProfileLocale, LocalizedProfileTranslation> = {
  ar: { kind: 'herb', slug: 'ashwagandha', path: '/ar/herbs/ashwagandha/', title: 'أشواغاندا (Withania somnifera): الأدلة والسلامة', summary: 'الأشواغاندا مستخلص جذور دُرس أساساً للتوتر المستمر والقلق المرتبط بالتوتر والنوم، وليس للتخفيف الفوري. تشير التحليلات التلوية إلى فائدة محتملة، لكن المستخلصات والجرعات تختلف وتظل درجة اليقين محدودة.', dosage: PROFILE_BASE.dosage.ar, safetyNotes: PROFILE_BASE.safety.ar, contraindications: PROFILE_BASE.contraindications.ar, claims: CLAIMS.ar, originalPath: '/herbs/ashwagandha/' },
  ru: { kind: 'herb', slug: 'ashwagandha', path: '/ru/travy/ashwagandha/', title: 'Ашваганда (Withania somnifera): доказательства и безопасность', summary: 'Ашваганда — экстракт корня, который в основном изучался при устойчивом стрессе, связанных со стрессом симптомах тревоги и проблемах сна, а не для немедленного облегчения. Метаанализы указывают на возможную пользу, но экстракты и дозы различаются, а определённость остаётся ограниченной.', dosage: PROFILE_BASE.dosage.ru, safetyNotes: PROFILE_BASE.safety.ru, contraindications: PROFILE_BASE.contraindications.ru, claims: CLAIMS.ru, originalPath: '/herbs/ashwagandha/' },
  vi: { kind: 'herb', slug: 'ashwagandha', path: '/vi/thao-duoc/ashwagandha/', title: 'Ashwagandha (Withania somnifera): bằng chứng và an toàn', summary: 'Ashwagandha là chiết xuất từ rễ được nghiên cứu chủ yếu đối với căng thẳng kéo dài, triệu chứng lo âu liên quan đến căng thẳng và giấc ngủ, không phải để giảm triệu chứng tức thời. Phân tích gộp cho thấy lợi ích có thể có, nhưng chiết xuất và liều dùng khác nhau và mức độ chắc chắn còn hạn chế.', dosage: PROFILE_BASE.dosage.vi, safetyNotes: PROFILE_BASE.safety.vi, contraindications: PROFILE_BASE.contraindications.vi, claims: CLAIMS.vi, originalPath: '/herbs/ashwagandha/' },
  th: { kind: 'herb', slug: 'ashwagandha', path: '/th/herbs/ashwagandha/', title: 'อัชวากันธา (Withania somnifera): หลักฐานและความปลอดภัย', summary: 'อัชวากันธาเป็นสารสกัดจากรากที่ศึกษาหลัก ๆ ในเรื่องความเครียดต่อเนื่อง อาการวิตกกังวลที่เกี่ยวข้องกับความเครียด และการนอนหลับ ไม่ใช่การบรรเทาอาการทันที การวิเคราะห์อภิมานชี้ถึงประโยชน์ที่อาจเกิดขึ้น แต่สารสกัดและขนาดยาแตกต่างกันและความแน่นอนของหลักฐานยังจำกัด', dosage: PROFILE_BASE.dosage.th, safetyNotes: PROFILE_BASE.safety.th, contraindications: PROFILE_BASE.contraindications.th, claims: CLAIMS.th, originalPath: '/herbs/ashwagandha/' },
  sv: { kind: 'herb', slug: 'ashwagandha', path: '/sv/orter/ashwagandha/', title: 'Ashwagandha (Withania somnifera): evidens och säkerhet', summary: 'Ashwagandha är ett rotextrakt som främst har studerats vid långvarig stress, stressrelaterade ångestsymtom och sömn, inte för omedelbar lindring. Metaanalyser antyder en möjlig nytta, men extrakt och doser skiljer sig och evidensens säkerhet är begränsad.', dosage: PROFILE_BASE.dosage.sv, safetyNotes: PROFILE_BASE.safety.sv, contraindications: PROFILE_BASE.contraindications.sv, claims: CLAIMS.sv, originalPath: '/herbs/ashwagandha/' },
}
