import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Helmet } from 'react-helmet-async';
import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { Home, ArrowLeft } from 'lucide-react';
const NotFound = () => {
    return (_jsxs(_Fragment, { children: [_jsxs(Helmet, { children: [_jsx("title", { children: "404 - Page Not Found | The Hippie Scientist" }), _jsx("meta", { name: "description", content: "The page you're looking for doesn't exist." })] }), _jsx("div", { className: "min-h-screen pt-20 px-4 flex items-center justify-center", children: _jsx("div", { className: "max-w-2xl mx-auto text-center", children: _jsxs(motion.div, { initial: { opacity: 0, scale: 0.8 }, animate: { opacity: 1, scale: 1 }, transition: { duration: 0.8 }, className: "glass-card p-12", children: [_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.2 }, className: "mb-8", children: [_jsx("h1", { className: "text-8xl font-bold psychedelic-text mb-4", children: "404" }), _jsx("h2", { className: "text-3xl font-bold text-white mb-4", children: "Page Not Found" }), _jsx("p", { className: "text-xl text-gray-300 mb-8", children: "Looks like this page got lost in the cosmic void. Let's get you back on track!" })] }), _jsxs(motion.div, { initial: { opacity: 0, y: 20 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.8, delay: 0.4 }, className: "flex flex-col sm:flex-row gap-4 justify-center", children: [_jsxs(Link, { to: "/", className: "glass-button px-8 py-4 rounded-lg text-white font-medium hover:scale-105 transition-all flex items-center justify-center space-x-2", children: [_jsx(Home, { className: "h-5 w-5" }), _jsx("span", { children: "Go Home" })] }), _jsxs("button", { onClick: () => window.history.back(), className: "glass-button px-8 py-4 rounded-lg text-white font-medium hover:scale-105 transition-all flex items-center justify-center space-x-2", children: [_jsx(ArrowLeft, { className: "h-5 w-5" }), _jsx("span", { children: "Go Back" })] })] })] }) }) })] }));
};
export default NotFound;
