import type { Metadata } from 'next'
import { getHerbs, getCompounds } from '@/lib/runtime-data'
import { getRuntimeVisibility } from '@/lib/runtime-visibility'
import RegimenPlannerClient from '@/components/protocols/RegimenPlannerClient'
import AuthorityJsonLd from '@/components/seo/AuthorityJsonLd'

export const metadata: Metadata = {
  title: 'Personalized Daily Protocol Planner & Schedule Builder',
  description: 'Design, audit, and export your custom daily supplement schedule. Group ingredients by Morning, Afternoon, Evening, and Night, auditing caffeine levels and sedative overlaps.',
  robots: { index: false, follow: true },
}

export default async function RegimenPlannerPage() {
  const [rawHerbs, rawCompounds] = await Promise.all([getHerbs(), getCompounds()])

  const herbs = rawHerbs.filter((h: any) => {
    try {
      return getRuntimeVisibility(h).canRender
    } catch {
      return true
    }
  })

  const compounds = rawCompounds.filter((c: any) => {
    try {
      return getRuntimeVisibility(c).canRender
    } catch {
      return true
    }
  })

  return (
    <main className='mx-auto max-w-6xl space-y-8 px-4 py-8 sm:py-10'>
      <AuthorityJsonLd
        title="Personalized Daily Protocol Planner & Schedule Builder"
        description="Plan and audit your custom daily herb and compound schedule with safety constituent thresholds."
        url="https://thehippiescientist.net/protocols/planner"
        type="MedicalWebPage"
      />

      <section className='rounded-[2rem] border border-brand-900/10 bg-white/90 p-6 shadow-sm sm:p-8 space-y-4 print:hidden'>
        <p className='eyebrow-label'>Clinical Schedule Planner</p>
        <h1 className='text-3xl font-bold tracking-tight text-ink sm:text-5xl mt-2'>
          Daily Protocol Planner
        </h1>
        <p className='mt-4 max-w-3xl text-base leading-7 text-muted sm:text-lg'>
          Construct a personalized intake regimen, mapping botanical supplements to specific times of day. Our audit checker monitors caffeine thresholds, sleep disruptors, and sedative loads.
        </p>
      </section>

      {/* Print only header */}
      <section className='hidden print:block space-y-2 border-b border-slate-350 pb-5'>
        <h1 className='text-3xl font-bold text-slate-800'>My Daily Supplement Protocol</h1>
        <p className='text-xs text-slate-500'>Generated by The Hippie Scientist · Scientific Supplement Decision Engine</p>
      </section>

      <RegimenPlannerClient herbs={herbs} compounds={compounds} />

      <section className='rounded-2xl border border-brand-900/15 bg-slate-50 p-5 text-xs leading-relaxed text-slate-600 print:hidden'>
        <p className='font-bold text-slate-800'>Regimen Building Safeguards:</p>
        <p className='mt-1.5'>
          Times of ingestion should align with circadian rhythms and physiological demands. Stimulants are best targeted to the morning and early afternoon, while GABAergic calming agents or sleep aids are appropriate for the evening and pre-bed intervals. Export your schedule to a JSON file or copy a shareable link to preserve your plan offline or share it with your healthcare professional.
        </p>
      </section>
    </main>
  )
}
