export const HERB_RUNTIME_FIELDS = [
  'slug',
  'name',
  'summary',
  'evidence_summary',
  'primary_effects',
  'evidence_grade',
  'safety_notes',
  'profile_status',
  'summary_quality',
  'runtime_export_decision',
  'mechanisms',
  'mechanism_targets',
  'compound_profile',
  'available_forms',
  'affiliate_ready',
  'affiliate_query',
  'default_product_type',
  'buying_criteria',
  'faq_q1',
  'faq_a1',
  'faq_q2',
  'faq_a2',
  'faq_q3',
  'faq_a3',
] as const
