const seedTickets = [
  { id: 'THS-001', priority: 'critical', area: 'Design', task: 'Redesign homepage hero', why: 'First impression + trust', doneWhen: 'Hero is clean on mobile/desktop with clear headline, subhead, and no more than 2 primary CTAs', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-002', priority: 'critical', area: 'Navigation', task: 'Simplify main navigation', why: 'Reduces choice overload and improves discovery', doneWhen: 'Primary navigation contains only highest-value destinations while deeper destinations remain discoverable', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-003', priority: 'critical', area: 'Typography', task: 'Standardize typography system', why: 'Improves readability and visual coherence', doneWhen: 'Global heading/body/font-size rules are centralized and consistently applied in both themes', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-004', priority: 'critical', area: 'Layout', task: 'Increase whitespace and normalize spacing', why: 'Dense pages feel unfinished and are harder to scan', doneWhen: 'A consistent spacing system is applied across priority surfaces and responsive widths', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-005', priority: 'critical', area: 'Page Templates', task: 'Standardize monograph template', why: 'Hundreds of pages need one intentional hierarchy', doneWhen: 'Herb and compound profiles share a canonical information hierarchy and reusable primitives where practical', status: 'in_progress', workRefs: ['#3999', 'branch:ths/compound-profile-parity'] },
  { id: 'THS-006', priority: 'critical', area: 'UX', task: 'Improve page scanning', why: 'Visitors should not have to read walls of text', doneWhen: 'Priority profiles expose summaries, quick facts, headings, jump navigation, and scannable evidence/safety blocks', status: 'in_progress', workRefs: ['#3999', 'branch:ths/compound-profile-parity'] },
  { id: 'THS-007', priority: 'critical', area: 'Evidence', task: 'Make evidence grades prominent', why: 'Evidence quality is a core differentiator', doneWhen: 'Evidence grade/status and explanation are visible near the top of relevant profiles without overstating certainty', status: 'in_progress', workRefs: ['#3999', 'branch:ths/compound-profile-parity'] },
  { id: 'THS-008', priority: 'critical', area: 'Safety', task: 'Improve safety presentation', why: 'Safety clarity is central to credibility and user protection', doneWhen: 'Contraindications, interactions, warnings, and uncertainty are understandable and visible early; missing data is never framed as safe', status: 'in_progress', workRefs: ['#3999', 'branch:ths/compound-profile-parity'] },
  { id: 'THS-009', priority: 'high', area: 'Mobile', task: 'Audit mobile experience', why: 'A large share of visits are mobile and poor responsive behavior destroys trust', doneWhen: 'Priority routes have no overflow, tiny text, broken cards, awkward navigation, or undersized controls', status: 'in_progress', workRefs: ['#3999', '#4011'] },
  { id: 'THS-010', priority: 'high', area: 'Content Quality', task: 'Improve weak introductions', why: 'Search visitors need a useful answer immediately', doneWhen: 'Priority search-entry pages quickly state what the subject is, what evidence says, and key uncertainty/safety boundaries', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-011', priority: 'high', area: 'Internal Linking', task: 'Improve related-content blocks', why: 'Contextual discovery increases usefulness and depth', doneWhen: 'Relevant alternatives, comparisons, and research paths appear contextually without arbitrary link dumps', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-012', priority: 'high', area: 'Conversion', task: 'Create clear next actions', why: 'Useful traffic needs a safe next step', doneWhen: 'Appropriate next actions exist at decision points without spam and respect risk/monetization suppression policy', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-013', priority: 'medium', area: 'Design System', task: 'Standardize cards', why: 'Arbitrary visual variants make the site feel unfinished', doneWhen: 'Reusable surface/card primitives replace unnecessary variants and semantic color retains meaning', status: 'verify_existing', workRefs: ['#3999', '#4002'] },
  { id: 'THS-014', priority: 'medium', area: 'Accessibility', task: 'Improve contrast and readability', why: 'Accessible design improves UX and reduces regressions', doneWhen: 'Contrast, focus, labels, text sizing, and keyboard behavior meet repository accessibility gates in both themes', status: 'in_progress', workRefs: ['#3999', '#4011'] },
  { id: 'THS-015', priority: 'medium', area: 'Performance', task: 'Reduce unnecessary page weight', why: 'Speed affects UX, crawlability, and conversions', doneWhen: 'Priority routes stay inside agreed Lighthouse, bundle, and runtime payload budgets on mobile and desktop', status: 'in_progress', workRefs: ['#3999', '#4011'] },
]

const areaConfig = {
  'Design System': {
    why: 'A coherent visual system reduces inconsistency, speeds future changes, and makes the site feel intentional.',
    dependencies: ['THS-003', 'THS-004', 'THS-013'], routes: ['sitewide'],
    verification: ['structural-test', 'visual-mobile', 'visual-desktop', 'dark-theme'],
    tasks: [
      'Define canonical surface hierarchy for page, section, card, inset, and warning layers',
      'Consolidate button variants into primary, secondary, ghost, and destructive roles',
      'Standardize pill and badge geometry, spacing, and semantic usage',
      'Standardize alert callouts for info, caution, warning, and critical states',
      'Normalize border radius tokens across cards, panels, images, and controls',
      'Normalize shadow tokens and remove decorative shadows with no hierarchy purpose',
      'Create one canonical divider and hairline treatment for editorial sections',
      'Standardize icon sizing and stroke weight by component role',
      'Audit decorative gradients and remove low-information visual noise',
      'Standardize empty-state visual treatment across search, filters, and datasets',
      'Standardize loading and skeleton states for interactive client surfaces',
      'Standardize selected, hover, focus, active, and disabled component states',
      'Create a reusable compact stat primitive for evidence, safety, and metadata',
      'Create a reusable key-value fact grid for profile summaries',
      'Standardize table containers, headers, zebra/row separators, and responsive overflow',
      'Standardize comparison visual language so winner/loser cues never imply unsupported science',
      'Standardize disclosure and footnote visual treatment',
      'Audit dark-theme surfaces for accidental pure-white or low-contrast islands',
      'Remove one-off component styling that duplicates existing design primitives',
      'Document design-token ownership and the allowed path for adding a new visual primitive',
    ],
  },
  'Navigation & IA': {
    why: 'Clear information architecture helps visitors reach high-value evidence, safety, and comparison destinations with less friction.',
    dependencies: ['THS-002'], routes: ['sitewide'], verification: ['structural-test', 'keyboard-qa', 'visual-mobile', 'visual-desktop'],
    tasks: [
      'Create a canonical site information-architecture map from all indexable route families',
      'Audit top-level navigation labels against actual search and user intent',
      'Add breadcrumbs consistently to every indexable deep page type',
      'Ensure breadcrumb labels use canonical human-readable entity names',
      'Audit mobile navigation depth so no critical destination requires excessive taps',
      'Provide a clear route from every profile back to its parent library',
      'Provide a clear route from every guide back to its topic or goal hub',
      'Remove navigation entries that lead to thin, duplicate, or transitional destinations',
      'Audit footer navigation for duplication and low-value clutter',
      'Group research tools under a consistent research/navigation taxonomy',
      'Group safety tools under a consistent safety/navigation taxonomy',
      'Create canonical navigation rules for localized routes',
      'Validate active-nav state across aliases, redirects, and nested route families',
      'Prevent mega-menu panels from overflowing narrow desktop viewports',
      'Ensure menus remain keyboard operable without hover dependency',
      'Add skip-to-content behavior consistently across site shells',
      'Audit anchor targets against sticky-header offsets on all long-form templates',
      'Eliminate broken or stale in-page table-of-contents links',
      'Create an automated route-to-navigation reachability audit for priority destinations',
      'Measure navigation exits and high-friction loops after IA changes',
    ],
  },
  'Typography & Readability': {
    why: 'Readable scientific content increases comprehension and reduces fatigue on dense evidence pages.',
    dependencies: ['THS-003'], routes: ['sitewide'], verification: ['structural-test', 'visual-mobile', 'visual-desktop', 'dark-theme'],
    tasks: [
      'Define a bounded responsive type scale for display, H1, H2, H3, body, small, and micro text',
      'Set canonical reading line length for long-form scientific content',
      'Normalize paragraph leading across profile, guide, article, and learn templates',
      'Normalize heading spacing so section hierarchy is visually predictable',
      'Prevent microcopy from dropping below the minimum readable mobile size',
      'Audit all-caps labels for excessive tracking and low legibility',
      'Standardize numeric typography for grades, counts, doses, and statistics',
      'Use tabular numerals where changing widths harm scanability',
      'Standardize citation typography and prevent citation markers from dominating prose',
      'Normalize link styling inside long-form content and cards',
      'Ensure underlines remain visible in high-contrast and dark modes',
      'Audit italic usage and remove long italic passages that reduce readability',
      'Standardize list indentation and marker spacing in editorial content',
      'Standardize blockquote and evidence-excerpt typography',
      'Standardize code, formula, chemical identifier, and monospaced text treatment',
      'Audit font-weight usage to prevent synthetic or muddy hierarchy',
      'Ensure fallback fonts preserve layout closely before web fonts finish loading',
      'Reduce font payload to only weights/styles actually used',
      'Create visual regression fixtures for the typography scale',
      'Document editorial typography rules for future agents and content generators',
    ],
  },
  'Layout & Responsive': {
    why: 'Responsive layout quality protects usability across phones, tablets, laptops, and wide screens.',
    dependencies: ['THS-004', 'THS-009'], routes: ['sitewide'], verification: ['responsive-qa', 'visual-mobile', 'visual-desktop', 'lighthouse'],
    tasks: [
      'Define canonical max-widths for marketing, profile, article, tool, and data-heavy layouts',
      'Normalize horizontal page gutters across breakpoints',
      'Normalize vertical section rhythm across priority page templates',
      'Audit two-column layouts for safe collapse ordering on mobile',
      'Ensure sidebars and sticky TOCs never cover content at intermediate widths',
      'Ensure fixed and sticky UI respects iOS safe-area insets',
      'Remove horizontal overflow from wide tables, code blocks, diagrams, and chips',
      'Add responsive overflow affordances where data tables must scroll',
      'Audit long unbroken URLs, chemical names, and identifiers for wrapping behavior',
      'Ensure hero images reserve dimensions and do not cause layout shift',
      'Normalize image aspect ratios by component role',
      'Audit grid minimum widths so cards do not become unusably narrow',
      'Ensure touch controls remain reachable when mobile browser chrome changes height',
      'Audit landscape-phone layouts for header and modal clipping',
      'Audit tablet breakpoints instead of treating tablet as small desktop',
      'Ensure sticky headers do not create unusable viewport height on small screens',
      'Normalize modal/dialog widths and padding across breakpoints',
      'Ensure bottom-of-page CTAs do not collide with browser or device safe areas',
      'Create representative responsive route fixtures for homepage, herb, compound, guide, and tool pages',
      'Record responsive QA evidence at phone, tablet, laptop, and wide-desktop widths',
    ],
  },
  'Page Templates': {
    why: 'Shared page architecture keeps hundreds of generated and editorial pages consistent and maintainable.',
    dependencies: ['THS-005', 'THS-006'], routes: ['/herbs/:slug', '/compounds/:slug', '/guides/:cluster/:slug', '/learn/:slug'], verification: ['structural-test', 'visual-mobile', 'visual-desktop', 'build'],
    tasks: [
      'Extract a shared profile hero primitive for herb and compound pages',
      'Extract a shared profile quick-facts primitive for herb and compound pages',
      'Extract a shared profile safety-summary primitive',
      'Extract a shared profile jump-navigation primitive',
      'Align herb and compound section ordering where scientific differences do not require divergence',
      'Define canonical profile sections and optional-section rules',
      'Ensure optional missing data removes a section cleanly instead of leaving placeholders',
      'Standardize guide-page hero and first-answer hierarchy',
      'Standardize article-page hero, metadata, and author trust hierarchy',
      'Standardize learn-page educational hierarchy and next-step pattern',
      'Standardize comparison-page summary, tradeoff, evidence, safety, and source hierarchy',
      'Standardize goal-hub hierarchy from intent to evidence-ranked choices',
      'Standardize library/index page filter, summary, and result-card hierarchy',
      'Standardize tool-page instructions, input, result, methodology, and caveat hierarchy',
      'Create canonical footer blocks for author, review, disclaimer, and update metadata',
      'Remove duplicate page-shell wrappers that create inconsistent width or spacing',
      'Audit every page type for one H1 and logical heading hierarchy',
      'Ensure profile and guide templates expose stable anchor IDs for deep links',
      'Create template-level structural tests for required sections and landmarks',
      'Document allowed template deviations for high-risk or regulatory-special-case pages',
    ],
  },
  'Content Quality': {
    why: 'Answer-first, precise copy improves search usefulness, trust, and scientific clarity.',
    dependencies: ['THS-010'], routes: ['priority-organic-entry-pages'], verification: ['content-lint', 'editorial-qa', 'build'],
    tasks: [
      'Build a priority-page introduction quality audit with minimum answer-first criteria',
      'Flag introductions that repeat the title without adding decision value',
      'Flag introductions dominated by marketing, history, or mechanism before the answer',
      'Ensure first-screen copy distinguishes human evidence from preclinical evidence',
      'Standardize plain-English summary length for herb and compound profiles',
      'Remove placeholder, research-pending, unknown, and internal workflow language from public copy',
      'Detect duplicated summary sentences across fields on the same page',
      'Detect near-duplicate introductions across different ingredients',
      'Flag unexplained technical terms in first-screen copy',
      'Add concise definitions for unavoidable pharmacology terminology',
      'Standardize evidence uncertainty language across editorial content',
      'Standardize safety uncertainty language across editorial content',
      'Flag absolute efficacy claims unsupported by the canonical evidence grade',
      'Flag vague superlatives such as best, powerful, proven, or miracle without explicit support',
      'Audit dose wording so product form is never mislabeled as dosing guidance',
      'Audit time-to-effect language for unsupported precision',
      'Normalize capitalization and naming of compounds, botanicals, and common aliases',
      'Ensure summaries do not contradict detailed evidence sections',
      'Create content-quality scores for priority organic landing pages',
      'Route low-scoring introductions and summaries into an editorial remediation queue',
    ],
  },
  Evidence: {
    why: 'Evidence presentation is a core product differentiator and must communicate strength, limits, and provenance accurately.',
    dependencies: ['THS-007'], routes: ['/herbs/:slug', '/compounds/:slug', '/evidence/:slug'], verification: ['evidence-validation', 'content-lint', 'editorial-qa', 'build'],
    tasks: [
      'Expose evidence grade plus plain-language meaning consistently near profile titles',
      'Make evidence-grade rationale available without requiring deep scrolling',
      'Show study-type mix beside evidence grade on priority profiles',
      'Show human-study count separately from total-source count',
      'Distinguish systematic reviews, RCTs, observational studies, and preclinical studies visually',
      'Surface contradictory or mixed evidence in the summary instead of burying it',
      'Prevent mechanism evidence from visually inheriting clinical-efficacy confidence',
      'Standardize no-evidence and insufficient-evidence states',
      'Standardize evidence freshness presentation and last-reviewed metadata',
      'Flag evidence conclusions supported primarily by stale reviews when newer syntheses exist',
      'Expose why an evidence grade is not higher on high-traffic profiles',
      'Expose why an evidence grade is not lower when confidence is strong',
      'Create outcome-specific evidence summaries instead of one undifferentiated ingredient score',
      'Ensure evidence badges never silently upgrade legacy grades',
      'Validate grade language against the canonical evidence enum',
      'Detect grade-versus-study-count anomalies',
      'Detect grade-versus-study-type anomalies',
      'Detect grade-versus-summary-language contradictions',
      'Create representative regression fixtures for A, B, C, D, and Avoid/Insufficient states',
      'Measure clicks into studies and evidence explainers to assess whether trust UI is discoverable',
    ],
  },
  'Safety & Trust': {
    why: 'Safety context and transparent trust signals are essential for responsible supplement decision support.',
    dependencies: ['THS-008'], routes: ['/herbs/:slug', '/compounds/:slug', '/safety-checker/'], verification: ['safety-validation', 'content-lint', 'editorial-qa', 'build'],
    tasks: [
      'Surface a one-line safety status near the top of every ingredient profile',
      'Standardize who-should-avoid summaries across herb and compound profiles',
      'Standardize medication-interaction entry points across profiles',
      'Ensure missing interaction data is labeled unknown or incomplete rather than none',
      'Distinguish contraindication, caution, common side effect, and severe risk',
      'Surface pregnancy and breastfeeding uncertainty consistently',
      'Surface liver and kidney cautions consistently where canonical data supports them',
      'Surface sedation, bleeding, serotonergic, stimulant, and cardiovascular risk families consistently',
      'Ensure controlled, prescription, unapproved, or regulatory-special-case compounds suppress inappropriate commerce',
      'Standardize legal/regulatory warning hierarchy for affected compounds',
      'Add last-checked dates to regulatory claims where supported',
      'Separate legal status from medical safety status in UI and schema',
      'Standardize product-quality caveats for supplements versus approved medicines',
      'Ensure affiliate disclosures appear before or adjacent to monetized recommendations',
      'Ensure author/reviewer credentials are visible on decision-relevant pages',
      'Ensure editorial methodology is reachable from evidence and safety surfaces',
      'Create an automated missing-safety-context audit for indexable profiles',
      'Create an automated high-risk monetization suppression regression test',
      'Create a trust checklist for new page templates before they can ship',
      'Measure safety-checker and interaction-checker usage from profile pages',
    ],
  },
  'SEO & Discovery': {
    why: 'Technical and intent-aligned SEO helps the right pages earn visibility without creating duplicate or low-value indexation.',
    dependencies: [], routes: ['indexable-routes'], verification: ['seo-validation', 'route-test', 'build', 'search-console-measurement'],
    tasks: [
      'Audit canonical tags across every indexable route family',
      'Audit redirect-only routes so they never remain indexable duplicates',
      'Audit sitemap inclusion against canonical visibility rules',
      'Audit robots directives for thin, redirected, or canonicalized-away pages',
      'Ensure titles communicate entity plus evidence/use intent without keyword stuffing',
      'Ensure meta descriptions answer search intent and include uncertainty where material',
      'Audit duplicate titles across profile, guide, article, and localized routes',
      'Audit duplicate meta descriptions across large generated page families',
      'Create query-intent mappings for top-impression Search Console pages',
      'Prioritize pages sitting in positions 4–15 with meaningful impressions',
      'Prioritize high-impression pages with weak click-through rate',
      'Create content refresh queues from traffic decline plus evidence freshness',
      'Audit orphaned indexable pages',
      'Audit crawl depth for priority organic landing pages',
      'Audit canonical trailing-slash consistency',
      'Audit hreflang and localized canonical relationships',
      'Ensure internal search pages do not create uncontrolled indexable URL combinations',
      'Validate Open Graph and social metadata on priority page templates',
      'Create SEO regression fixtures for canonical, redirect, noindex, and localized cases',
      'Measure organic clicks, CTR, average position, and landing-page engagement after major template changes',
    ],
  },
  'Internal Linking': {
    why: 'Contextual internal links improve discovery, crawl paths, and useful next-step behavior without manufacturing scientific claims.',
    dependencies: ['THS-011'], routes: ['indexable-routes'], verification: ['link-graph-test', 'route-test', 'build', 'click-measurement'],
    tasks: [
      'Create a canonical related-content relationship taxonomy',
      'Prefer evidence-aware related links over lexical similarity alone',
      'Add context-aware alternatives to ingredient profiles',
      'Add context-aware comparisons to ingredient profiles',
      'Add goal-hub links only when the relationship is supported by canonical mapping',
      'Add condition-guide links without implying treatment efficacy',
      'Connect guides back to the ingredient profiles they discuss',
      'Connect comparisons back to both compared entities',
      'Connect safety pages to affected profiles and vice versa',
      'Connect evidence explainers to profiles where users encounter grades',
      'Detect internal links to redirects and replace them with canonical targets',
      'Detect internal links to noindex or removed destinations',
      'Detect orphan pages in the generated route graph',
      'Detect pages with suspiciously excessive internal-link counts',
      'Limit related-content blocks to high-relevance choices rather than link walls',
      'Use descriptive anchor text instead of generic read more labels',
      'Keep mobile related-content blocks scannable and touch-friendly',
      'Create graph diagnostics for isolated high-value pages',
      'Create graph diagnostics for over-connected low-value hubs',
      'Measure related-link clickthrough and downstream engagement by block type',
    ],
  },
  'Conversion & Monetization': {
    why: 'Conversion systems should create value and revenue without outranking evidence, safety, or user fit.',
    dependencies: ['THS-012'], routes: ['monetized-and-decision-routes'], verification: ['policy-test', 'visual-mobile', 'visual-desktop', 'conversion-measurement'],
    tasks: [
      'Define safe conversion goals by page intent instead of using one CTA everywhere',
      'Keep primary educational actions visually stronger than affiliate actions on evidence pages',
      'Suppress purchase CTAs when safety or regulatory policy requires it',
      'Suppress purchase CTAs when evidence is Avoid/Insufficient where policy requires it',
      'Standardize product recommendation disclosure language',
      'Standardize sourcing CTA hierarchy and placement',
      'Prevent duplicate affiliate CTA blocks on the same viewport segment',
      'Limit email capture frequency and prevent repeated interruption within one session',
      'Match email-capture copy to the page topic rather than generic newsletter language',
      'Create non-commercial next steps for users who should avoid an ingredient',
      'Add compare-before-buying paths for commoditized supplement categories',
      'Add product-quality checklist links adjacent to commercial recommendations',
      'Ensure external affiliate links include required rel attributes',
      'Audit affiliate URLs for dead destinations and unintended redirects',
      'Audit monetized pages for evidence/safety language drift',
      'Create conversion events for safe next-step interactions',
      'Separate commercial conversion metrics from evidence-study engagement metrics',
      'Measure revenue per organic landing page without optimizing away safety',
      'Create experiments only when they preserve evidence and safety hierarchy',
      'Document monetization red lines that agents may never override for CTR or revenue',
    ],
  },
  Accessibility: {
    why: 'Accessible interaction and readable presentation are release-quality requirements, not optional polish.',
    dependencies: ['THS-014'], routes: ['sitewide'], verification: ['a11y-test', 'keyboard-qa', 'visual-mobile', 'visual-desktop'],
    tasks: [
      'Enforce one visible keyboard focus treatment across all interactive primitives',
      'Audit every modal for focus containment, Escape handling, and focus restoration',
      'Audit dropdown menus for keyboard-only operation',
      'Ensure touch targets meet the minimum target-size policy',
      'Ensure icon-only buttons have accessible names',
      'Ensure decorative icons and images are hidden from assistive technology',
      'Ensure meaningful images have useful alt text without keyword stuffing',
      'Audit form controls for labels, descriptions, and error associations',
      'Ensure validation errors are announced to assistive technology',
      'Audit heading order across every page template',
      'Audit landmark usage and unique main content region',
      'Audit table captions and header associations for scientific tables',
      'Ensure horizontal-scroll data regions are keyboard reachable and understandable',
      'Audit color contrast in both light and dark themes',
      'Ensure evidence and safety meaning is not conveyed by color alone',
      'Respect reduced-motion preferences for animations and transitions',
      'Audit zoom to 200 percent without clipped content or lost controls',
      'Audit text spacing overrides without layout breakage',
      'Create automated accessibility coverage for representative localized routes',
      'Track accessibility regressions as release blockers rather than warnings',
    ],
  },
  Performance: {
    why: 'Fast, stable pages improve user experience, crawl efficiency, and conversion while limiting regressions.',
    dependencies: ['THS-015'], routes: ['priority-routes'], verification: ['lighthouse-mobile', 'lighthouse-desktop', 'bundle-budget', 'runtime-budget'],
    tasks: [
      'Run Lighthouse performance gates on both mobile and desktop representative routes',
      'Set explicit LCP budgets for homepage, herb, compound, guide, and tool templates',
      'Set explicit CLS budgets for all image- and data-heavy templates',
      'Set explicit total-blocking-time budgets for client-heavy tools',
      'Audit client component boundaries and remove unnecessary use-client declarations',
      'Reduce unused JavaScript in global navigation and search surfaces',
      'Lazy-load noncritical interactive widgets below the fold',
      'Reserve dimensions for all content images and charts',
      'Prefer optimized responsive images over oversized source assets',
      'Audit font loading and remove unused font weights',
      'Audit global CSS size and remove dead framework or legacy layers',
      'Audit third-party scripts for blocking, duplication, and unnecessary early load',
      'Defer analytics and affiliate scripts until they do not compete with primary rendering',
      'Set runtime JSON payload budgets for profile pages',
      'Set generated search-index payload budgets',
      'Set bundle budgets for interactive tools',
      'Detect accidental import of large datasets into client bundles',
      'Measure cold-cache and warm-cache production behavior separately',
      'Track performance budgets over time rather than only current pass/fail',
      'Block regressions that exceed agreed hard performance thresholds',
    ],
  },
  'Structured Data & AI': {
    why: 'Consistent machine-readable entities, claims, and citations improve search/AI understanding without inventing certainty.',
    dependencies: [], routes: ['indexable-routes', '/data/*'], verification: ['schema-validation', 'ai-readiness-audit', 'build'],
    tasks: [
      'Define one canonical schema graph owner per page to prevent duplicate entities',
      'Validate Article schema on editorial long-form pages',
      'Validate MedicalWebPage or appropriate evidence-page schema where applicable',
      'Validate BreadcrumbList schema against visible breadcrumbs',
      'Validate FAQ schema only when substantive visible Q&A exists',
      'Remove FAQ schema from pages without enough meaningful questions',
      'Validate author and publisher identity consistently across schema graphs',
      'Expose dateModified from truthful editorial review metadata',
      'Expose citation relationships without inventing review dates',
      'Keep canonical entity IDs stable across generated endpoints',
      'Expose structured evidence direction as supporting, contradicting, mixed, or context',
      'Expose safety flags in machine-readable ingredient endpoints without implying medical advice',
      'Ensure mechanism relationships are not serialized as clinical causal claims',
      'Validate structured data on redirected and canonicalized-away routes',
      'Audit JSON-LD payload size and duplication',
      'Create representative schema snapshots for herb, compound, guide, comparison, and article pages',
      'Create AI-answer-readiness checks for concise sourced claims',
      'Create citation-readiness checks for source identity and claim traceability',
      'Ensure public machine-readable endpoints preserve provenance but hide internal workflow notes',
      'Monitor external citation/referral growth from AI answer engines where measurable',
    ],
  },
  'Analytics & Measurement': {
    why: 'Reliable measurement is required to know whether merged work actually improves outcomes.',
    dependencies: [], routes: ['sitewide'], verification: ['analytics-test', 'event-qa', 'measurement-review'],
    tasks: [
      'Define a canonical analytics event naming convention',
      'Define page-type and entity metadata attached to relevant events',
      'Track homepage hero CTA choice',
      'Track navigation destination choice by viewport',
      'Track profile jump-navigation usage',
      'Track evidence-grade explainer opens',
      'Track study-list opens and outbound source clicks',
      'Track safety-section and interaction-checker engagement',
      'Track related-content block clicks by relationship type',
      'Track compare-page entry sources',
      'Track safety-checker entry sources',
      'Track email signup impressions separately from successful signups',
      'Track affiliate CTA impressions separately from outbound clicks',
      'Track zero-result internal searches',
      'Track internal-search refinements and filter usage',
      'Track Core Web Vitals by page template in production',
      'Build a template-level engagement dashboard rather than relying only on sitewide averages',
      'Define pre/post measurement windows for major design or template changes',
      'Record baseline metrics in each high-impact ticket before experimentation',
      'Require a measurement note before moving merged work from observing to complete',
    ],
  },
  'Automation & Agent Ops': {
    why: 'A deterministic agent workflow prevents duplicate work, false completion, and uncontrolled changes.',
    dependencies: [], routes: ['repository-ops'], verification: ['backlog-validator', 'unit-test', 'workflow-qa'],
    tasks: [
      'Store the master backlog in a machine-readable canonical file',
      'Validate unique ticket IDs, required fields, and status enums in CI',
      'Validate every dependency references an existing ticket',
      'Detect dependency cycles before backlog changes can merge',
      'Provide a deterministic command that selects the highest-priority unblocked ticket',
      'Allow next-ticket selection to filter by area',
      'Allow next-ticket selection to cap blast radius by file or route family',
      'Require an implementation branch or PR reference when a ticket enters in-progress',
      'Require automated-test evidence before a ticket enters QA',
      'Require visual/behavior QA evidence before a ticket enters merged-observing',
      'Require merged commit evidence before a ticket enters merged-observing',
      'Require a measurement result before a ticket enters complete',
      'Prevent agents from silently marking blocked tickets complete',
      'Record blocker reasons and unblock conditions in the backlog',
      'Record ownership or agent identity while work is active',
      'Record affected routes for every implementation ticket',
      'Record verification commands for every implementation ticket',
      'Generate a compact backlog status report grouped by priority and area',
      'Generate a stale-in-progress report for abandoned work',
      'Document agent rules for surgical changes, regression coverage, merge, and measurement',
    ],
  },
  'Testing & QA': {
    why: 'Regression coverage turns design and content rules into enforceable product contracts.',
    dependencies: [], routes: ['repository-ci'], verification: ['unit-test', 'integration-test', 'visual-regression', 'release-qa'],
    tasks: [
      'Create structural smoke tests for homepage hierarchy',
      'Create structural smoke tests for herb profile hierarchy',
      'Create structural smoke tests for compound profile hierarchy',
      'Create structural smoke tests for guide hierarchy',
      'Create structural smoke tests for comparison hierarchy',
      'Create structural smoke tests for library and search hierarchy',
      'Create route-level tests for broken jump-navigation anchors',
      'Create tests for canonical internal links avoiding redirect targets',
      'Create tests for no duplicate H1 on representative templates',
      'Create tests for empty optional sections disappearing cleanly',
      'Create tests for evidence grade and explanation co-presence',
      'Create tests for missing safety data never rendering as safe',
      'Create tests for high-risk affiliate suppression',
      'Create tests for mobile navigation focus behavior',
      'Create tests for desktop navigation keyboard behavior',
      'Add screenshot or equivalent visual regression coverage for priority templates',
      'Add dark-theme visual regression coverage for priority templates',
      'Add narrow-mobile visual regression coverage for priority templates',
      'Add wide-desktop visual regression coverage for priority templates',
      'Create a release checklist that requires automated, visual, regression, merge, and measurement gates',
    ],
  },
  'Technical Debt': {
    why: 'Reducing duplication and clarifying source-of-truth boundaries makes future agent work safer and faster.',
    dependencies: [], routes: ['repository-source'], verification: ['typecheck', 'unit-test', 'build', 'regression-review'],
    tasks: [
      'Inventory duplicate profile helper functions across herb and compound routes',
      'Move shared profile presentation logic into typed reusable modules',
      'Inventory duplicated evidence terminology maps and remove local copies',
      'Inventory duplicated safety terminology maps and remove local copies',
      'Inventory duplicated route and canonical URL helpers',
      'Inventory one-off card components that can be retired',
      'Inventory obsolete CSS layers and identify safe deletion order',
      'Remove dead imports and unreachable feature branches',
      'Remove stale redirect aliases after the defined retention policy',
      'Remove generated files accidentally treated as hand-edited source',
      'Enforce source-of-truth boundaries between workbook, canonical data, runtime data, and presentation',
      'Replace permissive record casts at high-risk runtime boundaries',
      'Add runtime validation before malformed profile identity data reaches React',
      'Centralize display-name and alias policy',
      'Centralize visibility and indexability policy',
      'Centralize disclaimer selection policy',
      'Centralize monetization suppression policy',
      'Document intentional exceptions instead of encoding unexplained special cases',
      'Create dependency-update smoke gates for Next.js, React, Tailwind, and build tooling',
      'Maintain a debt-burn report showing removed duplication, retired code paths, and remaining hotspots',
    ],
  },
}

const fallbackPolicy = {
  why: 'The seed backlog defines a high-value acceptance contract that must be verified against the current implementation.',
  dependencies: [], routes: ['priority-routes'], verification: ['automated-tests', 'visual-mobile', 'visual-desktop', 'regression-review'],
}

const seedPolicyByArea = {
  Design: areaConfig['Design System'], Navigation: areaConfig['Navigation & IA'], Typography: areaConfig['Typography & Readability'],
  Layout: areaConfig['Layout & Responsive'], 'Page Templates': areaConfig['Page Templates'], UX: areaConfig['Page Templates'],
  Evidence: areaConfig.Evidence, Safety: areaConfig['Safety & Trust'], Mobile: areaConfig['Layout & Responsive'],
  'Content Quality': areaConfig['Content Quality'], 'Internal Linking': areaConfig['Internal Linking'],
  Conversion: areaConfig['Conversion & Monetization'], 'Design System': areaConfig['Design System'],
  Accessibility: areaConfig.Accessibility, Performance: areaConfig.Performance,
}

const completionGate = [
  'Implementation is present on the intended canonical source path.',
  'Relevant automated tests and repository gates pass.',
  'Desktop and mobile visual/behavior QA passes when the ticket affects rendered UI.',
  'Accessibility, evidence, safety, SEO, and performance regressions are ruled out where applicable.',
  'The change is merged successfully to main.',
  'A post-merge measurement or verification note is recorded.',
  'Only then may status become complete.',
]

function normalizeVerification(list = []) {
  return [...new Set([...list, 'merge', 'measure'])]
}

const tickets = seedTickets.map((ticket, index) => {
  const policy = seedPolicyByArea[ticket.area] || fallbackPolicy
  return {
    id: ticket.id,
    rank: index + 1,
    priority: ticket.priority,
    area: ticket.area,
    task: ticket.task,
    why: ticket.why,
    done_when: ticket.doneWhen,
    status: ticket.status,
    dependencies: [],
    affected_routes: policy.routes,
    verification: normalizeVerification(policy.verification),
    work_refs: ticket.workRefs,
  }
})

// Execution-state overrides for generated tickets.
//
// Generated tickets default to `backlog`. An agent that claims one records its
// live status and work refs here so this module stays the single source of
// truth for board state — the same role `seedTickets` plays for THS-001..015.
const generatedTicketOverrides = {
  'THS-178': {
    status: 'in_progress',
    work_refs: ['branch:ths/THS-178-sitemap-canonical-visibility'],
  },
}

let nextRank = tickets.length + 1
for (const [area, config] of Object.entries(areaConfig)) {
  for (const [taskIndex, task] of config.tasks.entries()) {
    const priority = taskIndex < 6 ? 'high' : taskIndex < 15 ? 'medium' : 'low'
    tickets.push({
      id: `THS-${String(nextRank).padStart(3, '0')}`,
      rank: nextRank,
      priority,
      area,
      task,
      why: config.why,
      done_when: `${task}. The change is covered by the listed verification gates and produces no regression on applicable routes.`,
      status: 'backlog',
      dependencies: config.dependencies,
      affected_routes: config.routes,
      verification: normalizeVerification(config.verification),
      work_refs: [],
      ...(generatedTicketOverrides[`THS-${String(nextRank).padStart(3, '0')}`] || {}),
    })
    nextRank += 1
  }
}

export const masterBacklog = {
  version: 1,
  name: 'The Hippie Scientist Master Backlog',
  scope: 'Site quality, UX, evidence, safety, SEO, internal linking, conversion, accessibility, performance, structured data, analytics, automation, testing, and technical debt.',
  ticket_count: tickets.length,
  status_model: {
    backlog: 'Defined but not yet selected.',
    verify_existing: 'Implementation appears to exist and must still clear acceptance, automated, visual/behavior, merge-state, and measurement checks.',
    ready: 'Dependencies are complete and the ticket is ready to claim.',
    in_progress: 'An agent is actively implementing or verifying the ticket.',
    blocked: 'Work cannot continue until an explicit blocker is resolved.',
    qa: 'Implementation exists on a branch/PR and is undergoing automated and visual/behavior QA.',
    merged_observing: 'Merged successfully; measurement window is still open.',
    complete: 'All completion gates, including measurement, are evidenced.',
  },
  completion_gate: completionGate,
  tickets,
}

export default masterBacklog
