export function sanitizeHerb(herb: any): import('../types').Herb {
  return {
    name: typeof herb?.name === 'string' ? herb.name : 'Unnamed Herb',
    scientificName: herb?.scientificName || '',
    category: herb?.category || 'Other',
    effects: Array.isArray(herb?.effects) ? herb.effects : [],
    tags: Array.isArray(herb?.tags) ? herb.tags : [],
    description: herb?.description || '',
    mechanismOfAction: herb?.mechanismOfAction || '',
    preparation: herb?.preparation || '',
    therapeuticUses: herb?.therapeuticUses || '',
    pharmacokinetics: herb?.pharmacokinetics || '',
    sideEffects: herb?.sideEffects || '',
    contraindications: herb?.contraindications || '',
    drugInteractions: herb?.drugInteractions || '',
    intensity: herb?.intensity || '',
    onset: herb?.onset || '',
    duration: herb?.duration || '',
    legalStatus: herb?.legalStatus || '',
    region: herb?.region || '',
    toxicity: herb?.toxicity || '',
    toxicityLD50: herb?.toxicityLD50 || '',
    safetyRating: herb?.safetyRating ?? null,
  } as import('../types').Herb
}
