name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Run site prebuild
        run: npm run prebuild

      - name: Run lint
        run: npm run lint --if-present

      - name: Run stylelint
        run: npm run stylelint --if-present

      - name: Run build
        run: npm run build

      - name: Verify built links
        run: node tools/check-links.mjs
