import type { StackSummary } from '@/utils/stack/buildStackSummary'

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

function asList(values: string[]): string {
  if (values.length === 0) return '<li>None</li>'
  return values.map(value => `<li>${escapeHtml(value)}</li>`).join('')
}

export function exportStackPDF(summary: StackSummary) {
  if (typeof window === 'undefined') return

  const printWindow = window.open('', '_blank', 'noopener,noreferrer,width=860,height=900')
  if (!printWindow) return

  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(summary.name)} - Stack Guide</title>
    <style>
      body { font-family: Inter, Arial, sans-serif; color: #0f172a; margin: 28px; line-height: 1.45; }
      h1 { margin: 0 0 6px; font-size: 28px; }
      h2 { margin: 18px 0 8px; font-size: 16px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
      p, li { font-size: 13px; }
      ul { margin: 6px 0 0; padding-left: 18px; }
      .muted { color: #475569; }
      .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 10px; padding: 12px; }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(summary.name)}</h1>
    <p class="muted">Generated by The Hippie Scientist Stack Builder</p>

    <h2>Items</h2>
    <ul>${asList(summary.items)}</ul>

    <h2>Intended Goal</h2>
    <p>${escapeHtml(summary.goal || 'Not specified')}</p>

    <h2>Effects Summary</h2>
    <p>${escapeHtml(summary.effectsSummary)}</p>

    <h2>Interaction Verdict</h2>
    <p><strong>${escapeHtml(summary.interactionVerdict)}</strong></p>

    <h2>Safety Notes</h2>
    <p>${escapeHtml(summary.safetySummary)}</p>

    <h2>What to watch for</h2>
    <ul>${asList(summary.topSignals)}</ul>

    <h2>Basic Dosage Guidance</h2>
    <p>${escapeHtml(summary.basicDosageGuidance || 'Start low, adjust slowly, and avoid introducing multiple new items at once.')}</p>

    <h2>Disclaimer</h2>
    <div class="card">
      <ul>${asList(summary.disclaimers)}</ul>
    </div>
  </body>
</html>`

  printWindow.document.open()
  printWindow.document.write(html)
  printWindow.document.close()
  printWindow.focus()
  printWindow.print()
}
